export interface Question {
  week?: number;
  domain: string;
  topic: string;
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_answer: string;
  explanation: string;
  difficulty?: string;
}

export const topic9Questions: Question[] = [
  // Context window sizes and limits (15 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your enterprise contract specifies 500K context window capacity. During negotiation, the client asks which Claude models support this. You clarify that...",
    option_a: "All Claude models support 500K by default",
    option_b: "Only Enterprise tier provides 500K (standard models: 200K, newest models: 1M)",
    option_c: "500K requires special API configuration",
    option_d: "All models support 1M tokens now",
    correct_answer: "B",
    explanation: "The standard context window for Claude models is 200K tokens. Enterprise users have access to 500K tokens, and Opus 4.6+ and Sonnet 4.6 support up to 1M tokens.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your legal tech platform processes contracts averaging 800K tokens. Clients experience errors with standard Claude. You need to specify minimum model requirements. Which models support documents this large?",
    option_a: "All Claude models with compaction enabled",
    option_b: "Enterprise 500K models",
    option_c: "Only Opus 4.6+ and Sonnet 4.6 with 1M context window",
    option_d: "Requires document splitting regardless of model",
    correct_answer: "C",
    explanation: "Opus 4.6 and later versions, as well as Sonnet 4.6, support a 1M token context window. This is the only option that can handle 800K token contracts in a single request.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During a pitch, prospects ask about processing 600K token quarterly reports. Your sales engineer should recommend...",
    option_a: "Standard Claude with document splitting",
    option_b: "Enterprise 500K tier (insufficient), upgrade to Opus 4.6+ or Sonnet 4.6 with 1M context",
    option_c: "Prompt caching to extend context window",
    option_d: "Multiple API calls with summarization",
    correct_answer: "B",
    explanation: "Since the document is 600K tokens, it exceeds both the standard 200K and Enterprise 500K limits. Only Opus 4.6+ or Sonnet 4.6 with 1M context windows can handle this in a single request. Prompt caching doesn't extend the context window size.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your 4-hour debugging session with a customer approaches the 200K context limit at 180K tokens. To continue the conversation without losing important context, you should...",
    option_a: "Immediately upgrade to Enterprise 500K",
    option_b: "Enable server-side compaction (which activates automatically)",
    option_c: "Manually summarize and restart the conversation",
    option_d: "Switch to Opus 4.6 mid-conversation",
    correct_answer: "B",
    explanation: "When approaching the context window limit, Claude uses server-side compaction to automatically summarize content, allowing the conversation to continue without hitting hard limits. At 180K of a 200K window, compaction will handle this.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your SaaS platform experiences context window errors during peak usage. Cost optimization is critical. What is the most cost-effective solution?",
    option_a: "Upgrade all users to Opus 4.6 immediately",
    option_b: "Rely on server-side compaction for standard models",
    option_c: "Implement client-side summarization logic",
    option_d: "Purchase Enterprise 500K for all customers",
    correct_answer: "B",
    explanation: "The most cost-effective solution is to rely on server-side compaction, which automatically handles summarization when approaching limits. This avoids the cost of upgrading models or Enterprise plans and is simpler than implementing client-side summarization.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During a technical review, stakeholders ask about context window consistency across Claude models. You explain that...",
    option_a: "All Claude 3 models have identical 200K windows",
    option_b: "Context windows vary by model version and pricing tier (200K standard, 500K Enterprise, 1M for Opus 4.6+/Sonnet 4.6)",
    option_c: "Newer models have smaller windows for efficiency",
    option_d: "All models now support 1M tokens universally",
    correct_answer: "B",
    explanation: "Context windows vary significantly: standard models have 200K, Enterprise has 500K, and Opus 4.6+/Sonnet 4.6 have 1M tokens. The window size depends on both model version and pricing tier.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your customer support chatbot maintains full conversation history. With a 200K context window and 500 tokens per exchange (question + response), approximately how many exchanges can you maintain before hitting limits?",
    option_a: "100 exchanges",
    option_b: "200 exchanges",
    option_c: "400 exchanges (200,000 ÷ 500)",
    option_d: "Unlimited with server-side compaction",
    correct_answer: "C",
    explanation: "With 200K tokens and 500 tokens per exchange, you can fit approximately 400 exchanges (200,000 / 500 = 400). While server-side compaction helps, it's not truly unlimited and still has practical limits.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "A Fortune 500 client asks about the primary advantage of 1M token context windows in Opus 4.6+ for their M&A due diligence workflow. You emphasize...",
    option_a: "Faster response times for complex queries",
    option_b: "Lower per-token processing costs",
    option_c: "Ability to process entire merger agreements and financial statements in single requests without splitting",
    option_d: "Improved accuracy on all tasks",
    correct_answer: "C",
    explanation: "The primary advantage of the 1M token context window is the ability to process much larger documents, codebases, or conversation histories in a single request without splitting or summarization, which is critical for comprehensive M&A analysis.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your finance team asks how context window size affects monthly API costs. You clarify that...",
    option_a: "Larger windows cost less per token",
    option_b: "Context window size doesn't directly affect per-token pricing, but larger windows may require more expensive models (e.g., Opus 4.6+)",
    option_c: "You're charged based on window size allocated, not usage",
    option_d: "Enterprise 500K windows double token costs",
    correct_answer: "B",
    explanation: "Context window size itself doesn't change per-token pricing, but larger windows (like 1M) are available on newer, potentially more expensive models like Opus 4.6+. You're always charged for actual tokens used, not window size.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "When should you advise a client to upgrade from 200K to 500K context window capacity?",
    option_a: "When they need faster model inference",
    option_b: "When they regularly hit context limits even with server-side compaction",
    option_c: "When they want improved model quality",
    option_d: "When they want to reduce API costs",
    correct_answer: "B",
    explanation: "You should consider upgrading to a larger context window when you regularly hit context limits even with server-side compaction, indicating your use case genuinely needs more context capacity.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "A prospect claims 'larger context windows = better outputs.' You correct this misconception by explaining...",
    option_a: "Larger windows always produce better outputs",
    option_b: "Larger windows provide capacity, not better reasoning; model quality depends on the model itself",
    option_c: "Window size directly correlates with accuracy",
    option_d: "Smaller windows actually perform better",
    correct_answer: "B",
    explanation: "A common misconception is that larger context windows always produce better outputs. In reality, model quality depends on the model itself, not just context window size. Larger windows provide capacity, not necessarily better reasoning.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your document analysis system processes varying file sizes from 50K to 900K tokens. What architecture optimizes both cost and performance?",
    option_a: "Always use Opus 4.6 with 1M window for all requests",
    option_b: "Route to different models based on document size (standard for <200K, Opus 4.6+/Sonnet 4.6 for >500K)",
    option_c: "Split all documents to fit standard 200K window",
    option_d: "Use Enterprise 500K for everything",
    correct_answer: "B",
    explanation: "The optimal approach is to route requests to different models based on document size: use standard models for smaller documents and Opus 4.6+/Sonnet 4.6 only for documents exceeding 500K tokens. This optimizes cost and performance.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During architecture review, a technical lead asks about the relationship between context windows and model inference speed. You clarify that...",
    option_a: "Larger windows enable proportionally faster inference",
    option_b: "Larger context windows don't provide faster inference; processing more tokens typically takes longer",
    option_c: "Window size has no relationship to speed",
    option_d: "1M windows are 5x faster than 200K windows",
    correct_answer: "B",
    explanation: "Larger context windows do not provide faster model inference. In fact, processing more tokens can take longer. The benefits are about capacity (processing more content) not speed.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "A legal tech startup processes contracts averaging 800K tokens. What's the minimum context window required for their MVP?",
    option_a: "200K (standard) with splitting",
    option_b: "500K (Enterprise)",
    option_c: "1M (Opus 4.6+ or Sonnet 4.6) is minimum for 800K contracts",
    option_d: "Impossible, contracts must always be split",
    correct_answer: "C",
    explanation: "For 800K token documents, you need the 1M context window available in Opus 4.6+ or Sonnet 4.6. The 500K Enterprise window would be insufficient.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What happens when Claude approaches the context window limit during a multi-turn conversation?",
    option_a: "API returns 400 error immediately",
    option_b: "Server-side compaction automatically summarizes older content to make room",
    option_c: "Oldest messages are silently dropped without summarization",
    option_d: "Request is queued until space becomes available",
    correct_answer: "B",
    explanation: "When approaching the context window limit, Claude uses server-side compaction to automatically summarize content, allowing the conversation to continue without hitting hard limits.",
    difficulty: "medium"
  },

  // Server-side compaction (15 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During a product demo, prospects ask how Claude handles conversations approaching context limits. You explain server-side compaction as...",
    option_a: "Manual compression triggered by API parameters",
    option_b: "Automatic summarization when approaching context limits without manual intervention",
    option_c: "Client-side reduction of message history",
    option_d: "Token-level compression algorithm",
    correct_answer: "B",
    explanation: "Server-side compaction is Claude's automatic summarization mechanism that activates when approaching the context window limit, allowing conversations to continue without manual intervention.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your support chatbot conversation has grown to 180K tokens of a 200K window. What should your system do?",
    option_a: "Manually summarize and restart conversation",
    option_b: "Delete oldest 50K tokens before next request",
    option_c: "Let server-side compaction handle it automatically",
    option_d: "Upgrade to Enterprise 500K mid-conversation",
    correct_answer: "C",
    explanation: "At 180K tokens with a 200K window, you're approaching the limit but server-side compaction will handle this automatically. There's no need for manual intervention at this stage.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "When implementing server-side compaction, which content does Claude prioritize for summarization first?",
    option_a: "Most recent messages",
    option_b: "System prompts are summarized first",
    option_c: "Older conversation history (preserving recent context)",
    option_d: "Tool use results are always prioritized",
    correct_answer: "C",
    explanation: "Server-side compaction prioritizes older conversation history for summarization, preserving more recent context which is typically more relevant to the current interaction.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "A customer reports that Claude 'forgot' specific details from early in a 4-hour debugging session. The most likely cause is...",
    option_a: "API bug requiring ticket submission",
    option_b: "Server-side compaction summarized early messages as conversation approached limits",
    option_c: "Separate memory limit unrelated to context window",
    option_d: "Client-side message truncation error",
    correct_answer: "B",
    explanation: "In long conversations, server-side compaction summarizes older messages when approaching context limits. This can make it seem like Claude 'forgot' specific details that were compressed in the summarization process.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During technical due diligence, investors ask about limitations of server-side compaction. You acknowledge that...",
    option_a: "Compaction requires explicit API parameters to enable",
    option_b: "Summarization inherently may lose some nuanced details from the original conversation",
    option_c: "Compaction only works for Enterprise accounts",
    option_d: "Compaction increases response latency by 50%",
    correct_answer: "B",
    explanation: "While server-side compaction is automatic and helpful, summarization inherently may lose some nuanced details from the original conversation. This is a trade-off for maintaining conversation continuity.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does server-side compaction balance conversation continuity with information retention?",
    option_a: "It always degrades quality significantly",
    option_b: "It maintains recent context intact while compressing older content",
    option_c: "It has no effect on quality",
    option_d: "It improves quality by removing redundant information",
    correct_answer: "B",
    explanation: "Server-side compaction is designed to maintain conversation quality by keeping recent context intact while compressing older content. This minimizes quality impact while managing context limits.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your engineering team asks if server-side compaction can be disabled for compliance reasons. You inform them that...",
    option_a: "Yes, via disable_compaction API parameter",
    option_b: "Yes, but only for Enterprise accounts",
    option_c: "No, it's automatic and cannot be disabled",
    option_d: "Yes, by using 1M context windows",
    correct_answer: "C",
    explanation: "Server-side compaction is an automatic feature that cannot be disabled. It's part of Claude's built-in context management system to ensure conversations can continue smoothly.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your legal compliance team requires maintaining exact conversation history for regulatory audits. Since server-side compaction can't be disabled, you must...",
    option_a: "Disable compaction via API settings",
    option_b: "Store full conversation history client-side separately from Claude's API interactions",
    option_c: "Use only Opus 4.6 with 1M context to avoid compaction",
    option_d: "Request Enterprise exemption from compaction rules",
    correct_answer: "B",
    explanation: "Since server-side compaction cannot be disabled, applications requiring exact conversation history must store it client-side separately. The compacted version in Claude is for operational purposes, not legal records.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During integration planning, developers ask about the relationship between prompt caching and server-side compaction. You explain they...",
    option_a: "Are mutually exclusive features",
    option_b: "Work independently: cached content is never subject to compaction",
    option_c: "Work independently for different purposes (cost reduction vs context management)",
    option_d: "Caching prevents compaction from ever triggering",
    correct_answer: "C",
    explanation: "Prompt caching and server-side compaction work independently. Caching reduces costs for repeated content, while compaction manages context limits. They serve different purposes and don't interfere with each other.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "When onboarding new developers, how transparent is server-side compaction to API users?",
    option_a: "Completely transparent with notifications on each compaction",
    option_b: "Mostly transparent; happens automatically without explicit notification",
    option_c: "Not transparent; requires constant token monitoring",
    option_d: "Transparent only for Enterprise users with dashboard",
    correct_answer: "B",
    explanation: "Server-side compaction is mostly transparent to users, happening automatically in the background without explicit notifications. The conversation continues smoothly from the user's perspective.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "For applications needing fine-grained control over what gets summarized or removed, what's the recommended approach?",
    option_a: "Configure compaction rules via API parameters",
    option_b: "Implement client-side message management before sending to API",
    option_c: "Use Enterprise compaction controls",
    option_d: "Disable compaction and manage context manually",
    correct_answer: "B",
    explanation: "Since server-side compaction is automatic and non-configurable, applications needing fine-grained control should implement client-side message management, deciding what to keep, summarize, or remove before sending to the API.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During a system design review, architects ask how server-side compaction treats system prompts. You explain that...",
    option_a: "System prompts are compacted first to save space",
    option_b: "System prompts are typically preserved as they define assistant behavior",
    option_c: "System prompts must be resent after each compaction",
    option_d: "System prompts are cached separately from compaction",
    correct_answer: "B",
    explanation: "Server-side compaction typically preserves system prompts as they define the assistant's behavior and role. The compaction focuses on conversation history rather than foundational instructions.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What happens to token counts after server-side compaction occurs during a conversation?",
    option_a: "Token counts reset to zero",
    option_b: "Token counts decrease as content is summarized into more compact form",
    option_c: "Token counts remain unchanged",
    option_d: "Token counts increase due to summarization overhead",
    correct_answer: "B",
    explanation: "After server-side compaction, token counts decrease because content has been summarized into a more compact form. This creates room for the conversation to continue within the context window.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "In what scenario would server-side compaction be insufficient for maintaining conversation continuity?",
    option_a: "Casual 10-turn conversation",
    option_b: "When you need to reference specific quotes or exact details from 100+ messages ago",
    option_c: "Multi-turn technical dialogue",
    option_d: "Any conversation with 500K or larger context window",
    correct_answer: "B",
    explanation: "Server-side compaction would be insufficient when you need to reference specific quotes or exact details from much earlier in the conversation, as summarization loses verbatim content. In such cases, client-side storage or larger context windows are better.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During capacity planning, your team asks about compaction triggering. You explain it happens...",
    option_a: "After every 10 messages automatically",
    option_b: "When explicitly requested via compaction API parameter",
    option_c: "When approaching the context window limit (not at fixed intervals)",
    option_d: "At the start of every new conversation",
    correct_answer: "C",
    explanation: "Server-side compaction triggers automatically when the conversation is approaching the context window limit, not at fixed intervals or on demand.",
    difficulty: "easy"
  },

  // Automatic context management (10 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During a technical deep-dive, prospects ask about automatic context management. You explain it as...",
    option_a: "Manual tracking of conversation tokens",
    option_b: "Built-in handling of context specifically for code execution users",
    option_c: "Third-party context optimization service",
    option_d: "Client-side compression utility",
    correct_answer: "B",
    explanation: "Automatic context management is a built-in feature for code execution users that handles context automatically, reducing the need for manual context tracking and management.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Which user segment benefits most from automatic context management in Claude?",
    option_a: "All API users get identical benefits",
    option_b: "Code execution users (developers using code interpreter features)",
    option_c: "Enterprise customers exclusively",
    option_d: "Users with 1M context windows only",
    correct_answer: "B",
    explanation: "Automatic context management is specifically designed for code execution users, providing automatic handling of context without manual intervention.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What does automatic context management handle for qualifying users?",
    option_a: "Only system messages",
    option_b: "Context tracking and optimization automatically",
    option_c: "Only tool use results",
    option_d: "Manual prompt engineering",
    correct_answer: "B",
    explanation: "Automatic context management handles context tracking and optimization automatically, removing the burden of manual context management from developers.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During architecture review, a technical lead asks how automatic context management differs from server-side compaction. You clarify that...",
    option_a: "They are identical features with different names",
    option_b: "Automatic management is for code execution; compaction is universal across all users",
    option_c: "Compaction is manual; automatic management is API-driven",
    option_d: "Automatic management only works with caching enabled",
    correct_answer: "B",
    explanation: "Automatic context management is specifically for code execution users and provides comprehensive context handling, while server-side compaction is a universal feature that summarizes content when approaching limits.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "A startup using Claude for code execution asks about the key benefit of automatic context management. You emphasize...",
    option_a: "Lower per-token API costs",
    option_b: "Faster code execution response times",
    option_c: "Reduced complexity in application code (no manual context tracking)",
    option_d: "Unlimited context windows for code tasks",
    correct_answer: "C",
    explanation: "The key benefit of automatic context management is reduced complexity in application code, as developers don't need to implement their own context tracking and optimization logic.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your development team asks if automatic context management can be overridden with manual controls. You inform them...",
    option_a: "Yes, it's fully configurable via API",
    option_b: "No, it's always automatic for code execution users",
    option_c: "Yes, but only for Enterprise accounts",
    option_d: "No, but you can disable it entirely",
    correct_answer: "B",
    explanation: "Automatic context management is designed to be automatic for code execution users. The system handles it without configuration or override options, simplifying the developer experience.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your application uses Claude for code execution and teams are concerned about context limits. What should you advise?",
    option_a: "Implement custom context management immediately",
    option_b: "Rely on automatic context management built into code execution",
    option_c: "Manually track all token counts",
    option_d: "Upgrade to Enterprise for manual control",
    correct_answer: "B",
    explanation: "For code execution users, relying on automatic context management is the recommended approach. It's designed to handle these concerns without custom implementation.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is NOT a feature of automatic context management?",
    option_a: "Automatic context optimization without configuration",
    option_b: "Built-in for code execution users",
    option_c: "Manual configuration of retention policies and thresholds",
    option_d: "Simplified developer experience",
    correct_answer: "C",
    explanation: "Automatic context management does not offer manual configuration of retention policies. It's designed to work automatically without developer configuration.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does automatic context management affect application architecture for code execution workflows?",
    option_a: "Requires significant architectural changes",
    option_b: "Simplifies architecture by removing need for context management code",
    option_c: "Has no effect on architecture",
    option_d: "Requires dedicated context management microservices",
    correct_answer: "B",
    explanation: "Automatic context management simplifies application architecture by removing the need for custom context management code, tracking systems, and optimization logic.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "When would you need to implement custom context management despite automatic context management being available?",
    option_a: "When using code execution features",
    option_b: "When building non-code-execution use cases with specific context requirements (e.g., legal compliance)",
    option_c: "When using standard API calls",
    option_d: "Never; automatic management handles all cases",
    correct_answer: "B",
    explanation: "You'd need custom context management when your use case isn't code execution or has specific context requirements that automatic management doesn't address. Automatic management is specifically for code execution users.",
    difficulty: "hard"
  },

  // Prompt caching strategies (20 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your enterprise system sends 50K token system prompts across 10,000 daily requests. Caching implementation saves approximately...",
    option_a: "Nothing; caching doesn't reduce costs",
    option_b: "$200-500/day by paying cache read rates instead of full processing for 9,999 requests",
    option_c: "10% on total costs",
    option_d: "Caching only benefits Enterprise accounts",
    correct_answer: "B",
    explanation: "Prompt caching reduces costs by avoiding reprocessing of repeated content across requests. With a 50K token system prompt across 10K requests, you pay full price once, then reduced cache read rates for 9,999 subsequent requests, saving $200-500/day.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During integration planning, developers ask how to enable prompt caching. You instruct them to...",
    option_a: "Set enable_caching: true parameter",
    option_b: "Use the cache_control field to mark content for caching",
    option_c: "Caching is automatic for all requests",
    option_d: "Contact Enterprise support for activation",
    correct_answer: "B",
    explanation: "Prompt caching is enabled by using the cache_control field in your API request to mark content that should be cached. This gives you explicit control over what gets cached.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your system sends 20K token system prompts plus 100K token product documentation across all requests. To maximize cache benefits, you should...",
    option_a: "Don't cache; files are too large",
    option_b: "Cache both using cache_control and place at prompt beginning",
    option_c: "Only cache system prompts (documentation is too large)",
    option_d: "Split both into smaller non-cached chunks",
    correct_answer: "B",
    explanation: "A large, stable system prompt and documentation are perfect for caching. Use cache_control to mark both for caching and place at the beginning of the prompt for optimal efficiency and substantial cost savings.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Where should cached content be placed for optimal cache utilization?",
    option_a: "At the end of prompts",
    option_b: "Scattered throughout the prompt",
    option_c: "At the beginning of prompts before variable content",
    option_d: "Placement doesn't matter for caching",
    correct_answer: "C",
    explanation: "Cached content should be placed at the beginning of the prompt. This allows Claude to process and cache it efficiently before encountering new, variable content.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your multi-turn customer support conversations use Claude. Does prompt caching work automatically across conversation turns?",
    option_a: "No, you must explicitly enable for each turn",
    option_b: "Yes, it automatically caches conversation history across turns",
    option_c: "Only for Enterprise accounts",
    option_d: "Only for conversations under 50K tokens",
    correct_answer: "B",
    explanation: "Prompt caching works automatically for multi-turn conversations, caching the conversation history across turns without requiring explicit cache_control on every message.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What happens if you change a single word in your 50K token cached system prompt?",
    option_a: "Cache automatically updates that word incrementally",
    option_b: "Entire cache is invalidated and must be rebuilt",
    option_c: "Only changed section is reprocessed",
    option_d: "Change is ignored to maintain cache efficiency",
    correct_answer: "B",
    explanation: "If cached content changes at all, the entire cache is invalidated and must be rebuilt. This is why caching works best for stable content that rarely changes.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How long does cached content remain available before expiring?",
    option_a: "Forever until explicitly cleared",
    option_b: "24 hours from last use",
    option_c: "5 minutes (TTL documented in API docs)",
    option_d: "Until server restart",
    correct_answer: "C",
    explanation: "Cached content has a specific time-to-live (TTL), which is documented in the API documentation (5 minutes). After this period, the cache expires and content must be reprocessed.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is a common mistake when implementing prompt caching?",
    option_a: "Caching stable, large content",
    option_b: "Placing cached content at prompt beginning",
    option_c: "Caching frequently changing per-request content",
    option_d: "Using cache_control field correctly",
    correct_answer: "C",
    explanation: "A common mistake is caching frequently changing content. Since any change invalidates the entire cache, this provides no benefit and adds complexity. Cache only stable content.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your application sends 1000 requests/day with the same 100K token API documentation. Estimated monthly cost savings with caching?",
    option_a: "Minimal; caching doesn't significantly affect costs",
    option_b: "Substantial; paying cache read rates instead of full processing for 999 daily requests (~$3,000-6,000/month)",
    option_c: "None; cached tokens cost the same",
    option_d: "100%; cached tokens are free",
    correct_answer: "B",
    explanation: "With the same 100K token documentation across 1000 daily requests (30K/month), caching provides substantial savings. After the first request, subsequent requests pay the reduced cache read rate instead of full processing costs, saving $3K-6K/month.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Can you cache tool definitions to optimize agentic workflows?",
    option_a: "No, tool definitions cannot be cached",
    option_b: "Yes, tool definitions are ideal for caching since they're stable",
    option_c: "Only function-based tools, not code-based",
    option_d: "Only for Enterprise accounts",
    correct_answer: "B",
    explanation: "Tool definitions are ideal for caching since they're typically stable and reused across many requests. Caching them reduces costs when the same tools are used repeatedly.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the relationship between prompt caching and context window limits?",
    option_a: "Caching increases the effective context window by 2x",
    option_b: "Caching reduces available context window by cache overhead",
    option_c: "Cached tokens still count toward the context window limit",
    option_d: "Caching completely replaces context window mechanism",
    correct_answer: "C",
    explanation: "Cached tokens still count toward the context window limit. Caching is about cost efficiency, not increasing capacity. It doesn't change how much content you can include in a request.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your product documentation updates weekly (every Monday). Is prompt caching beneficial?",
    option_a: "No, updates too frequently for cache benefits",
    option_b: "Yes, even weekly changes benefit from 6 days of cache reuse",
    option_c: "Only if changes are minor",
    option_d: "Only with automatic cache invalidation",
    correct_answer: "B",
    explanation: "Even with weekly changes, prompt caching is beneficial. You get cost savings for all requests during that week (6 days). The cache is only rebuilt once when the documentation changes, then reused until the next change.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What content should NOT be cached?",
    option_a: "System instructions (stable across requests)",
    option_b: "Tool definitions (reused frequently)",
    option_c: "User-specific queries that change each request",
    option_d: "Large 100K token documentation",
    correct_answer: "C",
    explanation: "User-specific queries that change with each request should not be cached. Caching works best for content that's reused across multiple requests, not unique per-request content.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How should you structure a prompt with both cached and non-cached content?",
    option_a: "Non-cached first, then cached",
    option_b: "Cached content first, then non-cached variable content",
    option_c: "Interleave for best performance",
    option_d: "Use separate API calls for each",
    correct_answer: "B",
    explanation: "Structure prompts with cached content first (at the beginning), followed by non-cached, variable content. This allows efficient cache utilization while accommodating request-specific information.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What happens when you use cache_control on content that's never reused across requests?",
    option_a: "API returns validation error",
    option_b: "You pay cache write costs with no read benefits (wasting money)",
    option_c: "Content is automatically uncached by Claude",
    option_d: "Performance degrades significantly",
    correct_answer: "B",
    explanation: "If you cache content that's not reused, you pay the cache write cost without getting the benefit of cache reads. This increases costs rather than reducing them. Only cache content that will be reused.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "A chatbot has a 20K token system prompt and 50K token knowledge base, both static across all conversations. Optimal caching strategy?",
    option_a: "Only cache system prompt",
    option_b: "Only cache knowledge base",
    option_c: "Cache both system prompt and knowledge base",
    option_d: "Cache neither; focus on user messages",
    correct_answer: "C",
    explanation: "Both the system prompt and knowledge base should be cached since they're static and reused across all conversations. Place both at the prompt beginning and mark with cache_control for maximum savings.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does prompt caching interact with streaming responses?",
    option_a: "Caching disables streaming",
    option_b: "Streaming disables caching",
    option_c: "They work independently; cache input while streaming output",
    option_d: "Caching only works with complete (non-streamed) responses",
    correct_answer: "C",
    explanation: "Prompt caching and streaming work independently. You can cache input content while still receiving streamed responses. They serve different purposes and don't interfere with each other.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What metrics should you monitor to optimize prompt caching effectiveness?",
    option_a: "Only total token usage",
    option_b: "Cache hit rate (% of requests using cache) and cost per request",
    option_c: "Only response latency",
    option_d: "Only cache size in bytes",
    correct_answer: "B",
    explanation: "Monitor cache hit rate (how often cached content is reused) and cost per request to optimize caching. These metrics show whether your caching strategy is effective and cost-efficient.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your cached 150K token system prompt expires mid-conversation. What happens?",
    option_a: "Conversation immediately fails with cache error",
    option_b: "Content is reprocessed and recached transparently on next request",
    option_c: "You must restart the conversation from scratch",
    option_d: "API returns 429 cache expiration error",
    correct_answer: "B",
    explanation: "If cached content expires mid-conversation, it's transparently reprocessed and recached on the next request. The conversation continues normally, though that request will pay full processing costs to rebuild the cache.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the minimum content size worth caching for cost-effectiveness?",
    option_a: "Any size; even 100 tokens benefit from caching",
    option_b: "At least 1000 tokens for cost-effective caching",
    option_c: "At least 10K tokens minimum",
    option_d: "Only content larger than 50K tokens",
    correct_answer: "B",
    explanation: "While there's no hard minimum, caching becomes cost-effective typically around 1000+ tokens. Very small content may not justify the cache write overhead. The exact threshold depends on reuse frequency.",
    difficulty: "medium"
  },

  // Cache placement and optimization (15 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your cost monitoring shows $5K/month Claude spend with 60% from cache misses. To optimize, you should prioritize...",
    option_a: "Disabling caching entirely",
    option_b: "Placing all cacheable content at prompt beginning, adding jitter to cache writes",
    option_c: "Reducing prompt sizes",
    option_d: "Switching to smaller models",
    correct_answer: "B",
    explanation: "Placing cached content at the beginning allows Claude to efficiently process and utilize the cache before encountering new content. This is an optimization best practice, not a hard requirement.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What happens if you place cached content at the end of the prompt instead of the beginning?",
    option_a: "API returns cache placement error",
    option_b: "Caching is automatically disabled",
    option_c: "It works but may be less efficient than beginning placement",
    option_d: "No difference from placing at beginning",
    correct_answer: "C",
    explanation: "Placing cached content at the end will still work and the content will be cached, but it may be less efficient than placing it at the beginning where it can be processed first.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How should you structure multiple cached sections (system prompt, tool definitions, knowledge base) in a single prompt?",
    option_a: "Scatter throughout prompt for load balancing",
    option_b: "Group all cached content together at the beginning",
    option_c: "Alternate cached and non-cached content",
    option_d: "Place largest cached content last",
    correct_answer: "B",
    explanation: "Group all cached content together at the beginning of the prompt. This creates a clear cached prefix that's efficiently processed before the variable content in each request.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "You have system instructions (10K), tool definitions (30K), and knowledge base (100K) all cacheable. Optimal ordering?",
    option_a: "Order matters: smallest to largest (system, tools, knowledge)",
    option_b: "Order doesn't matter as long as all are at the beginning before non-cached content",
    option_c: "Largest to smallest for efficiency",
    option_d: "Alphabetical order",
    correct_answer: "B",
    explanation: "When all content is cacheable and at the beginning, the specific order among cached sections doesn't significantly impact caching efficiency. What matters is that they're all grouped at the start before non-cached content.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does cache placement affect API latency?",
    option_a: "Beginning placement significantly reduces latency",
    option_b: "Placement has minimal impact on latency",
    option_c: "End placement reduces latency more",
    option_d: "Cache placement doubles latency",
    correct_answer: "B",
    explanation: "Cache placement has minimal impact on latency. The main benefit of caching is cost reduction, not latency improvement. Proper placement optimizes processing efficiency but doesn't dramatically change response times.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Should you cache few-shot examples in your system prompt?",
    option_a: "No, examples change too frequently",
    option_b: "Yes, if examples are stable across requests",
    option_c: "Only for Enterprise accounts",
    option_d: "Only if examples exceed 50K tokens",
    correct_answer: "B",
    explanation: "Cache few-shot examples if they're stable and reused across requests. Like other system prompt content, stable examples are ideal candidates for caching to reduce costs.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your prompt has: system instructions (stable), user context (per-user), query (per-request). What should be cached?",
    option_a: "All three sections",
    option_b: "Only system instructions",
    option_c: "System instructions and user context",
    option_d: "Nothing; too much variation",
    correct_answer: "B",
    explanation: "Only cache the system instructions, as they're stable across all requests. User context varies per user and query varies per request, so caching them provides no benefit.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How can you optimize cache utilization in a multi-tenant SaaS application serving 50,000 customers?",
    option_a: "Use separate caches for each tenant",
    option_b: "Cache only tenant-agnostic content (system instructions, tool definitions)",
    option_c: "Disable caching for multi-tenant scenarios",
    option_d: "Cache everything including tenant-specific data",
    correct_answer: "B",
    explanation: "In multi-tenant applications, cache only tenant-agnostic content like system instructions and tool definitions. Tenant-specific content varies per tenant and won't benefit from caching.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's a sign that your cache placement strategy needs optimization?",
    option_a: "High API costs despite using cache_control on stable content",
    option_b: "Slower response times than expected",
    option_c: "More accurate responses than baseline",
    option_d: "Longer context windows than configured",
    correct_answer: "A",
    explanation: "If you're using cache_control but still seeing high costs, your cache placement or content selection may need optimization. You might be caching content that's not reused or structured inefficiently.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Should you cache conversation history in a multi-turn chatbot?",
    option_a: "Yes, always explicitly cache all history",
    option_b: "No, conversation history is unique per conversation",
    option_c: "Yes, Claude automatically caches conversation history in multi-turn (no explicit cache_control needed)",
    option_d: "Only cache the most recent 5 messages",
    correct_answer: "C",
    explanation: "For multi-turn conversations, Claude automatically caches conversation history across turns. You don't need to explicitly cache it. However, the history is unique per conversation, so it's not shared across different users' conversations.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the best practice for caching versioned content like API documentation (v1.0, v1.1, v2.0)?",
    option_a: "Cache all versions together",
    option_b: "Don't cache versioned content",
    option_c: "Cache each version separately with version identifier in cache strategy",
    option_d: "Only cache the latest version",
    correct_answer: "C",
    explanation: "For versioned content, cache each version separately. Include the version in your cache strategy (implementation-dependent) so different versions don't invalidate each other's caches. This allows efficient caching across versions.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How often should you review and optimize your caching strategy based on production metrics?",
    option_a: "After every API call",
    option_b: "Weekly or when usage patterns change significantly",
    option_c: "Once during initial implementation, never again",
    option_d: "Hourly to catch all changes",
    correct_answer: "B",
    explanation: "Review caching strategy weekly or when usage patterns change significantly. This balances the need for optimization with practical development cycles. Monitor metrics to identify when optimization is needed.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your application has 5 different system prompts for different use cases (customer support, sales, technical). How should you approach caching?",
    option_a: "Cache all prompts in a single cache",
    option_b: "Cache each prompt separately for its respective use case",
    option_c: "Don't cache; too much variation",
    option_d: "Merge all prompts and cache the combined version",
    correct_answer: "B",
    explanation: "Cache each system prompt separately for its respective use case. Each use case benefits from caching its own prompt independently. Don't merge them as that would send unnecessary content for each request.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the impact of caching very large content (e.g., 150K tokens)?",
    option_a: "API rejects requests with content over 100K",
    option_b: "Higher cache write cost initially, but proportionally greater savings on reuse (if frequently reused)",
    option_c: "Large content cannot be cached",
    option_d: "Cache efficiency decreases with size",
    correct_answer: "B",
    explanation: "Caching very large content has a higher initial cache write cost, but provides proportionally greater savings when reused multiple times. The cost-benefit improves with content size, assuming frequent reuse.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "A startup reports high costs despite implementing caching. Investigation reveals they cache user queries. You advise them to...",
    option_a: "Increase cache size limits",
    option_b: "Stop caching per-request content like user queries; only cache stable shared content",
    option_c: "Upgrade to Enterprise for better caching",
    option_d: "Add more cache_control fields",
    correct_answer: "B",
    explanation: "Caching per-request content like user queries that's never reused wastes money (paying cache write costs with no read benefits). Only cache stable content shared across multiple requests (system prompts, tool definitions, knowledge bases).",
    difficulty: "medium"
  },

  // Context editing strategies (15 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During architecture review, you explain context editing as...",
    option_a: "Manual modification of conversation history",
    option_b: "Strategies for managing context size by selectively removing content",
    option_c: "Automatic grammar correction in context",
    option_d: "Version control for prompts",
    correct_answer: "B",
    explanation: "Context editing refers to strategies for managing context size by selectively removing or modifying content, helping keep conversations within context window limits.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your agentic workflow generates 5,000 tool_use results filling 95% of context with old outputs. To continue the workflow without hitting limits, configure...",
    option_a: "Client-side manual result deletion",
    option_b: "clear_tool_uses_20250919 strategy to automatically clear old tool results",
    option_c: "Larger context window",
    option_d: "Disable all tools",
    correct_answer: "B",
    explanation: "The clear_tool_uses_20250919 strategy is a context editing approach that automatically clears old tool results, helping manage context size in agentic workflows with many tool calls.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does clear_tool_uses_20250919 determine which tool results to clear?",
    option_a: "Random selection to distribute clearing",
    option_b: "Clears tool results chronologically from oldest to newest",
    option_c: "Removes largest results first by token count",
    option_d: "Clears all results simultaneously at threshold",
    correct_answer: "B",
    explanation: "The clear_tool_uses_20250919 strategy clears tool results chronologically, removing the oldest tool results first. This preserves recent context while managing overall context size.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "When is context editing most valuable for production systems?",
    option_a: "Short single-turn interactions",
    option_b: "Long-running agentic workflows with many tool calls accumulating results",
    option_c: "Only when approaching 1M token limit",
    option_d: "When using streaming responses exclusively",
    correct_answer: "B",
    explanation: "Context editing is most valuable in long-running agentic workflows where many tool calls accumulate large amounts of tool results, potentially filling the context window.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What content does clear_tool_uses_20250919 NOT remove?",
    option_a: "Old tool results from initial workflow steps",
    option_b: "Recent tool results and conversation messages",
    option_c: "System messages",
    option_d: "User queries from early turns",
    correct_answer: "B",
    explanation: "The clear_tool_uses_20250919 strategy specifically removes old tool results while preserving recent tool results and other conversation content like messages, ensuring context continuity.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your AI agent makes 50 tool calls in a complex workflow, each returning 5K tokens (250K total). Strategy to prevent context overflow?",
    option_a: "Immediately upgrade to 1M context window",
    option_b: "Use clear_tool_uses_20250919 to clear old tool results while maintaining recent ones",
    option_c: "Disable tool use after 10 calls",
    option_d: "Cache all tool results permanently",
    correct_answer: "B",
    explanation: "With 50 tool calls producing 250K tokens of results, use clear_tool_uses_20250919 to clear old tool results. This prevents context overflow while maintaining recent results needed for the workflow.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Can you customize which specific tool results are preserved vs cleared in context editing?",
    option_a: "Yes, via priority flags on individual tools",
    option_b: "No, clear_tool_uses_20250919 follows its built-in chronological logic",
    option_c: "Yes, but only for Enterprise accounts",
    option_d: "Yes, by setting retention policies per tool",
    correct_answer: "B",
    explanation: "The clear_tool_uses_20250919 strategy follows its built-in chronological logic and cannot be customized. It systematically clears oldest results first without user control over specific results.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the primary trade-off of using context editing strategies?",
    option_a: "Increased API costs per request",
    option_b: "Slower response times for all queries",
    option_c: "Potential loss of information from cleared content",
    option_d: "Reduced model accuracy significantly",
    correct_answer: "C",
    explanation: "The main trade-off of context editing is potential loss of information from cleared content. While it helps manage context size, the model no longer has access to removed tool results.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "During technical design, architects ask how context editing differs from server-side compaction. You explain...",
    option_a: "They are identical features with different names",
    option_b: "Context editing is manual via API; compaction is automatic",
    option_c: "Context editing removes content entirely; compaction summarizes it",
    option_d: "Compaction only works for tool results",
    correct_answer: "C",
    explanation: "Context editing strategies like clear_tool_uses_20250919 remove content entirely, while server-side compaction summarizes content. Both manage context size but use different approaches.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "When should you implement custom context editing instead of using clear_tool_uses_20250919?",
    option_a: "Never; always use built-in strategies",
    option_b: "When you need domain-specific logic (e.g., always preserve financial calculation results)",
    option_c: "When using fewer than 10 tools",
    option_d: "When using Enterprise accounts",
    correct_answer: "B",
    explanation: "Implement custom context editing when you need domain-specific logic, such as keeping certain critical tool results while removing others, or using non-chronological prioritization. Use built-in strategies when chronological clearing suffices.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What happens if you don't implement context editing in a long agentic workflow with 100+ tool calls?",
    option_a: "API automatically applies default editing",
    option_b: "You may hit context limits requiring workflow restart or manual management",
    option_c: "Performance improves with more context",
    option_d: "Costs decrease due to better optimization",
    correct_answer: "B",
    explanation: "Without context editing in long workflows, tool results accumulate and may eventually hit context limits, forcing you to restart the workflow or manually manage context. Context editing prevents this.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Can context editing be combined with prompt caching?",
    option_a: "No, they are mutually exclusive features",
    option_b: "Yes, they address different concerns (cost optimization vs context management)",
    option_c: "Only for Enterprise accounts",
    option_d: "Yes, but only for tool definitions",
    correct_answer: "B",
    explanation: "Context editing and prompt caching address different concerns and can work together. Caching reduces costs for stable content, while editing manages dynamic tool results in workflows.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How should you design tools to work optimally with context editing?",
    option_a: "Make tools return maximum possible detail",
    option_b: "Design tools to return concise, essential information only",
    option_c: "Avoid using tools in workflows with editing",
    option_d: "Make all tool results identical in size",
    correct_answer: "B",
    explanation: "Design tools to return concise, essential information. This minimizes context usage and reduces the need for aggressive context editing, while still providing necessary data.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the recommended approach for critical tool results that shouldn't be cleared (e.g., security credentials retrieved early in workflow)?",
    option_a: "Use clear_tool_uses_20250919 and hope they're preserved",
    option_b: "Store them client-side and reinject when needed",
    option_c: "Disable context editing entirely",
    option_d: "Mark them with no-clear flag in API",
    correct_answer: "B",
    explanation: "For critical tool results, store them client-side and reinject when needed. Built-in strategies don't have exemption mechanisms, so client-side management gives you control over what to preserve.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does context editing impact debugging agentic workflows in production?",
    option_a: "No impact; full history always available in logs",
    option_b: "Makes debugging harder since cleared results aren't visible in API conversation history",
    option_c: "Improves debugging by reducing noise",
    option_d: "Only affects production, not development",
    correct_answer: "B",
    explanation: "Context editing makes debugging harder because cleared tool results aren't visible in the conversation history. For development, consider logging full history client-side before editing occurs.",
    difficulty: "medium"
  },

  // Tool result management (10 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Why are tool results a common source of context bloat in production agentic systems?",
    option_a: "Tools always return maximum-size responses by design",
    option_b: "Tool results can be very large (API responses, file contents) and accumulate quickly in workflows",
    option_c: "Tool results are duplicated in context automatically",
    option_d: "Tool results cannot be compressed",
    correct_answer: "B",
    explanation: "Tool results can be very large (e.g., API responses, file contents) and accumulate quickly in multi-step agentic workflows, making them a primary source of context bloat.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the best practice for tool design regarding context management?",
    option_a: "Return all available data for completeness",
    option_b: "Return only essential information needed for the task",
    option_c: "Always limit results to exactly 100 characters",
    option_d: "Compress results using gzip algorithms",
    correct_answer: "B",
    explanation: "Best practice is to design tools that return only essential information needed for the task. This minimizes context usage while providing necessary functionality.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How should you handle tools that potentially return very large results (e.g., database queries returning 10K rows)?",
    option_a: "Disable those tools entirely",
    option_b: "Implement pagination or filtering within the tool",
    option_c: "Only use with 1M context windows",
    option_d: "Automatically cache all results",
    correct_answer: "B",
    explanation: "For tools with potentially large results, implement pagination or filtering so the tool can return subsets of data rather than everything at once. This gives control over context usage.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your search_documentation tool returns 50K tokens of results, but Claude only uses the first 2K tokens. What's the problem?",
    option_a: "Claude has a bug processing tool results",
    option_b: "The tool is returning too much unnecessary information; refine to return targeted results",
    option_c: "You need a larger context window",
    option_d: "The tool results aren't formatted correctly",
    correct_answer: "B",
    explanation: "If Claude only uses a fraction of large tool results, the tool is returning too much unnecessary information. Refine the tool to return more targeted, relevant results to optimize context usage.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Should tool results be cached?",
    option_a: "Yes, always cache all tool results",
    option_b: "No, tool results are inherently too dynamic",
    option_c: "Only if the same tool with same parameters is called repeatedly with identical results",
    option_d: "Only for Enterprise accounts",
    correct_answer: "C",
    explanation: "Cache tool results only if the same tool with the same parameters is called repeatedly and returns the same data. Most tool results are dynamic and don't benefit from caching.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How can you monitor tool result impact on context usage?",
    option_a: "Monitoring isn't possible for tool results",
    option_b: "Track token counts of tool results separately from other context",
    option_c: "Only available in Enterprise dashboards",
    option_d: "Automatically monitored by clear_tool_uses_20250919",
    correct_answer: "B",
    explanation: "Monitor tool result impact by tracking token counts of tool results separately from other context. This helps identify which tools consume the most context and need optimization.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's a good heuristic for maximum tool result size?",
    option_a: "No limit; return everything available",
    option_b: "Keep under 5-10K tokens unless larger results are essential",
    option_c: "Exactly 1000 tokens always",
    option_d: "50% of total context window",
    correct_answer: "B",
    explanation: "A good heuristic is keeping tool results under 5-10K tokens unless larger results are essential. This prevents individual tools from consuming disproportionate context while allowing flexibility when needed.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your agent uses 10 different tools with varying result sizes. How should you approach tool result management?",
    option_a: "Limit all tools to identical size",
    option_b: "Optimize each tool individually based on its purpose and typical usage",
    option_c: "Only optimize the single largest tool",
    option_d: "Rely entirely on clear_tool_uses_20250919",
    correct_answer: "B",
    explanation: "Optimize each tool individually based on its purpose. Different tools have different needs; some naturally return more data. The goal is right-sized results for each tool's function.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the relationship between tool result size and workflow complexity?",
    option_a: "No relationship exists",
    option_b: "Larger results enable more complex workflows",
    option_c: "Smaller, focused results allow longer workflows within context limits",
    option_d: "Complex workflows require disabling tools",
    correct_answer: "C",
    explanation: "Smaller, focused tool results allow longer, more complex workflows within context limits. Each tool call consumes less context, enabling more steps before hitting limits.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How should error messages in tool results be handled for context management?",
    option_a: "Return full stack traces always for debugging",
    option_b: "Return concise error messages with essential details only",
    option_c: "Suppress all error messages to save context",
    option_d: "Error messages don't affect context",
    correct_answer: "B",
    explanation: "Error messages should be concise with essential details. Full stack traces consume significant context unnecessarily. Provide enough information for Claude to understand and handle the error without excess verbosity.",
    difficulty: "medium"
  }
];
