export interface Question {
  week?: number;
  domain: string;
  topic: string;
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_answer: string;
  explanation: string;
  difficulty?: string;
}

export const topic7Questions: Question[] = [
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the primary benefit of using XML tags like <context>, <task>, and <instructions> in Claude prompts?',
    option_a: 'They reduce API costs by 50%',
    option_b: 'They enable multimodal outputs',
    option_c: 'They make prompts easier to read for humans',
    option_d: 'They improve output consistency by 20-40%',
    correct_answer: 'D',
    explanation: 'XML tags provide clear structural boundaries that help Claude parse and understand different sections of a prompt, leading to 20-40% more consistent outputs according to Anthropic\'s documentation.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which of the following is a valid XML tag commonly used in Claude prompt engineering?',
    option_a: '<header>',
    option_b: '<metadata>',
    option_c: '<context>',
    option_d: '<prompt>',
    correct_answer: 'C',
    explanation: '<context> is one of the standard XML tags recommended for Claude prompts. Other common tags include <task>, <instructions>, and <output_format>.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'When using XML tags in prompts, which tag should you use to specify how Claude should format its response?',
    option_a: '<response>',
    option_b: '<format>',
    option_c: '<style>',
    option_d: '<output_format>',
    correct_answer: 'D',
    explanation: '<output_format> is the standard XML tag used to specify how Claude should structure and format its response. This helps ensure consistent output formatting.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which XML tag structure would be most appropriate for providing background information to Claude?',
    option_a: '<background>',
    option_b: '<context>',
    option_c: '<info>',
    option_d: '<data>',
    correct_answer: 'B',
    explanation: '<context> is the recommended XML tag for providing background information and contextual details that Claude needs to understand before executing the task.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the correct syntax for using an XML tag in a Claude prompt?',
    option_a: 'Opening and closing tags with content between them',
    option_b: 'Single self-closing tags only',
    option_c: 'Tags with attributes but no closing tags',
    option_d: 'Tags must be nested at least three levels deep',
    correct_answer: 'A',
    explanation: 'XML tags in Claude prompts use standard XML syntax: opening tag (<tag>), content, and closing tag (</tag>). This provides clear boundaries for different sections.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which statement about XML tags in prompts is most accurate?',
    option_a: 'They are required for all Claude API calls',
    option_b: 'They work only with Claude Opus models',
    option_c: 'They improve parsing but are not strictly required',
    option_d: 'They automatically enable caching',
    correct_answer: 'A',
    explanation: 'XML tags are a best practice that improves Claude\'s ability to parse and understand prompts, but they are not technically required. Claude can process prompts without them, though with potentially less consistency.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What percentage improvement in output consistency can XML tags provide according to Anthropic\'s guidelines?',
    option_a: '10-15%',
    option_b: '20-40%',
    option_c: '50-60%',
    option_d: '70-80%',
    correct_answer: 'B',
    explanation: 'According to Anthropic\'s documentation, using XML tags to structure prompts can lead to 20-40% more consistent outputs by providing clear boundaries between different prompt sections.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which of the following best describes the <task> XML tag\'s purpose?',
    option_a: 'To specify the model version',
    option_b: 'To provide examples',
    option_c: 'To enable streaming',
    option_d: 'To define what Claude should accomplish',
    correct_answer: 'D',
    explanation: 'The <task> XML tag is used to clearly define the specific task or objective that Claude should accomplish. This helps separate the task definition from context, examples, or formatting instructions.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'In a well-structured prompt using XML tags, where should step-by-step procedures be placed?',
    option_a: 'In the <context> tag',
    option_b: 'In the <task> tag',
    option_c: 'In the <examples> tag',
    option_d: 'In the <instructions> tag',
    correct_answer: 'D',
    explanation: 'Step-by-step procedures and detailed instructions on how to complete the task should be placed in the <instructions> tag, separate from the task definition and context.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'When using multiple XML tags in a prompt, what is the recommended organization?',
    option_a: 'Random order is fine',
    option_b: 'Alphabetical order',
    option_c: 'Most important information last',
    option_d: 'Logical flow: context, task, instructions, output format',
    correct_answer: 'D',
    explanation: 'The recommended organization follows a logical flow: <context> for background, <task> for objectives, <instructions> for how to complete it, and <output_format> for formatting. This matches how humans naturally process information.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can you nest XML tags within each other in Claude prompts?',
    option_a: 'Yes, and it can help organize complex prompts',
    option_b: 'No, all tags must be at the same level',
    option_c: 'Only with Extended Thinking enabled',
    option_d: 'Only in Opus models',
    correct_answer: 'A',
    explanation: 'XML tags can be nested in Claude prompts, which is useful for organizing complex information hierarchically. For example, you might have multiple <example> tags nested within a <examples> container tag.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which is a best practice when using XML tags in prompts?',
    option_a: 'Use as many tags as possible for maximum clarity',
    option_b: 'Always close tags properly to maintain structure',
    option_c: 'Mix XML tags with other markup languages',
    option_d: 'Avoid using tags in system prompts',
    correct_answer: 'A',
    explanation: 'Properly closing XML tags is essential to maintain the structural integrity of the prompt. Unclosed tags can confuse Claude about where sections begin and end.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What happens if you use inconsistent XML tag names throughout a prompt?',
    option_a: 'The API will reject the request',
    option_b: 'Claude may have difficulty parsing the prompt structure',
    option_c: 'Automatic tag correction occurs',
    option_d: 'No impact on performance',
    correct_answer: 'B',
    explanation: 'While the API won\'t reject inconsistent tag names, using different names for similar purposes (e.g., <task> and <objective> interchangeably) can reduce Claude\'s ability to consistently parse the prompt structure.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which of the following is NOT a standard XML tag recommended by Anthropic for prompt engineering?',
    option_a: '<context>',
    option_b: '<task>',
    option_c: '<instructions>',
    option_d: '<reasoning>',
    correct_answer: 'D',
    explanation: 'While <context>, <task>, <instructions>, and <output_format> are standard recommended tags, <reasoning> is not a standard tag. For reasoning, you would use thinking tags or Extended Thinking, not a <reasoning> XML tag.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How do XML tags in prompts interact with prompt caching?',
    option_a: 'Tags prevent caching from working',
    option_b: 'Tags have no effect on caching',
    option_c: 'Tagged sections can be cached as coherent units',
    option_d: 'Only untagged content is cached',
    correct_answer: 'C',
    explanation: 'XML tags help define coherent sections that can be cached as logical units. This makes prompt caching more effective as tagged sections form natural cache boundaries.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the Extended Thinking API feature in Claude?',
    option_a: 'An API parameter that enables multi-step reasoning',
    option_b: 'A separate API endpoint for complex queries',
    option_c: 'A token multiplier for longer outputs',
    option_d: 'A caching mechanism for thoughts',
    correct_answer: 'A',
    explanation: 'The Extended Thinking API is enabled via the `thinking` parameter in API requests, allowing Claude to engage in extended multi-step reasoning before providing a response.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which parameter enables Extended Thinking in Claude API calls?',
    option_a: 'thinking: {type: "adaptive"}',
    option_b: 'extended_thinking: true',
    option_c: 'reasoning_mode: "extended"',
    option_d: 'cognitive_depth: "high"',
    correct_answer: 'A',
    explanation: 'Extended Thinking is enabled by setting the `thinking` parameter with `{type: "adaptive"}` in the API request. This is the correct parameter structure.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which Claude models support the Extended Thinking API feature?',
    option_a: 'Only Opus 4.8',
    option_b: 'Opus 4.8, Opus 4.7, Opus 4.6, Sonnet 4.6',
    option_c: 'All Claude 3 and 4 models',
    option_d: 'Opus 4.8, Mythos Preview, Opus 4.7/4.6, Sonnet 4.6/4.5, Haiku 4.5',
    correct_answer: 'D',
    explanation: 'Extended Thinking is supported on Opus 4.8, Mythos Preview, Opus 4.7, Opus 4.6, Sonnet 4.6, Sonnet 4.5, and Haiku 4.5. This covers a wide range of recent Claude models.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What type of value does the Extended Thinking API parameter accept?',
    option_a: 'Boolean (true/false)',
    option_b: 'String ("enabled"/"disabled")',
    option_c: 'Object with type property',
    option_d: 'Integer (0-10 scale)',
    correct_answer: 'A',
    explanation: 'The `thinking` parameter accepts an object with a `type` property, like `{type: "adaptive"}`. This is not a simple boolean or string value.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'When Extended Thinking is enabled, where does Claude\'s reasoning appear?',
    option_a: 'In the system prompt',
    option_b: 'In metadata fields',
    option_c: 'In a separate thinking block in the response',
    option_d: 'It\'s hidden and not returned',
    correct_answer: 'C',
    explanation: 'When Extended Thinking is enabled, Claude\'s reasoning process is visible in a separate thinking block within the API response, allowing you to see the multi-step reasoning.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the primary use case for Extended Thinking?',
    option_a: 'Reducing API latency',
    option_b: 'Enabling multimodal inputs',
    option_c: 'Improving performance on complex reasoning tasks',
    option_d: 'Compressing output tokens',
    correct_answer: 'D',
    explanation: 'Extended Thinking is designed for complex reasoning tasks that benefit from multi-step deliberation, such as mathematical problems, code debugging, or intricate analysis.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How does Extended Thinking differ from regular Claude responses?',
    option_a: 'It uses a different model',
    option_b: 'It allows Claude to show its reasoning process explicitly',
    option_c: 'It requires fewer input tokens',
    option_d: 'It only works with JSON outputs',
    correct_answer: 'B',
    explanation: 'Extended Thinking allows Claude to explicitly show its step-by-step reasoning process in a thinking block, whereas regular responses only show the final answer without the intermediate reasoning.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can Extended Thinking be combined with Structured Outputs?',
    option_a: 'No, they are mutually exclusive',
    option_b: 'Yes, but only with JSON mode',
    option_c: 'Yes, thinking happens before structured output generation',
    option_d: 'Only in Opus 4.8',
    correct_answer: 'C',
    explanation: 'Extended Thinking can be combined with Structured Outputs. Claude performs its reasoning in the thinking block first, then generates the structured output based on that reasoning.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What happens to thinking blocks when prompt caching is enabled?',
    option_a: 'Thinking blocks cannot be cached',
    option_b: 'Thinking blocks are cached on Opus 4.5+ and Sonnet 4.6+',
    option_c: 'Only the final answer is cached, not thinking',
    option_d: 'Caching automatically disables Extended Thinking',
    correct_answer: 'B',
    explanation: 'On Opus 4.5 and later, and Sonnet 4.6 and later, thinking blocks can be cached along with other prompt content, preserving them for the 1-hour cache duration.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which effort level setting is NOT valid for Opus 4.8?',
    option_a: 'low',
    option_b: 'medium',
    option_c: 'high',
    option_d: 'extreme',
    correct_answer: 'A',
    explanation: 'Opus 4.8 supports effort levels of low, medium, high, and xhigh (extra high), not "extreme". The model respects these effort levels strictly.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'When should you use the Extended Thinking API?',
    option_a: 'For all API calls to improve quality',
    option_b: 'When tasks require multi-step reasoning or complex analysis',
    option_c: 'Only for mathematical calculations',
    option_d: 'When you need faster responses',
    correct_answer: 'B',
    explanation: 'Extended Thinking is most beneficial for tasks requiring multi-step reasoning, complex analysis, or deliberation. It adds overhead, so it should be used selectively for tasks that truly benefit from explicit reasoning.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the correct parameter structure for enabling Extended Thinking?',
    option_a: 'thinking: true',
    option_b: 'thinking: "adaptive"',
    option_c: 'thinking: {enabled: true}',
    option_d: 'thinking: {type: "adaptive"}',
    correct_answer: 'A',
    explanation: 'The correct structure is `thinking: {type: "adaptive"}`, where thinking is an object with a type property set to "adaptive". This is the documented API parameter format.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Does Extended Thinking affect token usage?',
    option_a: 'No, thinking is free',
    option_b: 'Yes, thinking tokens are counted in output',
    option_c: 'Only input tokens increase',
    option_d: 'It reduces overall token usage',
    correct_answer: 'B',
    explanation: 'Extended Thinking generates additional output tokens for the thinking block, which are counted and billed as part of the output. This can significantly increase costs for complex reasoning tasks.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can you access individual thinking steps from Extended Thinking output?',
    option_a: 'Yes, they are exposed in the API response structure',
    option_b: 'No, only the final answer is accessible',
    option_c: 'Only in streaming mode',
    option_d: 'Only with special API keys',
    correct_answer: 'A',
    explanation: 'The thinking block in Extended Thinking responses is part of the API response structure and can be accessed, parsed, and analyzed. This allows you to see Claude\'s reasoning process.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the relationship between Extended Thinking and effort levels in Opus 4.8?',
    option_a: 'They are the same feature',
    option_b: 'Effort levels are ignored when Extended Thinking is on',
    option_c: 'Extended Thinking enables effort level control',
    option_d: 'Opus 4.8 strictly respects effort levels (low/medium/high/xhigh)',
    correct_answer: 'D',
    explanation: 'Opus 4.8 strictly respects effort levels (low, medium, high, xhigh), which can be used with or without Extended Thinking. Effort levels control how much computational effort the model applies.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the primary difference between Extended Thinking (API feature) and thinking tags (prompt technique)?',
    option_a: 'They are the same thing with different names',
    option_b: 'Extended Thinking is an API parameter; thinking tags are prompt instructions',
    option_c: 'Extended Thinking is free; thinking tags cost tokens',
    option_d: 'Extended Thinking only works in JSON mode',
    correct_answer: 'B',
    explanation: 'Extended Thinking is enabled via API parameters (thinking: {type: "adaptive"}), while thinking tags are a prompting technique where you instruct Claude to use <thinking> tags in its output through the prompt itself.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'When using thinking tags as a prompting technique, where do you specify them?',
    option_a: 'In the API parameters',
    option_b: 'In the model selection',
    option_c: 'In the prompt content itself',
    option_d: 'In the metadata field',
    correct_answer: 'C',
    explanation: 'Thinking tags as a prompting technique are specified in the prompt content itself. You instruct Claude in the prompt to use <thinking> tags to show its reasoning, rather than using an API parameter.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can you use thinking tags technique without Extended Thinking API enabled?',
    option_a: 'Yes, they are independent techniques',
    option_b: 'No, Extended Thinking must be enabled',
    option_c: 'Only in Opus models',
    option_d: 'Only with streaming disabled',
    correct_answer: 'A',
    explanation: 'Thinking tags as a prompting technique can be used independently without enabling the Extended Thinking API. You simply instruct Claude in your prompt to use <thinking> tags in its output.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How would you instruct Claude to use thinking tags in its output?',
    option_a: 'Set thinking: true in API parameters',
    option_b: 'Enable it in model configuration',
    option_c: 'Include instructions in the prompt like "Show your reasoning in <thinking> tags"',
    option_d: 'Use a special API endpoint',
    correct_answer: 'C',
    explanation: 'To use thinking tags as a prompting technique, you include instructions in your prompt content, such as "Show your reasoning inside <thinking> tags before your final answer." This is a prompt-based technique, not an API parameter.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is a key advantage of thinking tags technique over Extended Thinking API?',
    option_a: 'Thinking tags are faster',
    option_b: 'Thinking tags work on all models, not just specific versions',
    option_c: 'Thinking tags are free of charge',
    option_d: 'Thinking tags provide better reasoning',
    correct_answer: 'B',
    explanation: 'Thinking tags as a prompting technique work on any Claude model since they\'re just prompt instructions, whereas Extended Thinking API is only available on specific model versions (Opus 4.8, Mythos Preview, etc.).',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'When using thinking tags in multishot prompting, where should they appear?',
    option_a: 'Only in the final user message',
    option_b: 'In the system prompt only',
    option_c: 'In example responses to demonstrate the pattern',
    option_d: 'They cannot be used in multishot prompting',
    correct_answer: 'A',
    explanation: 'When using thinking tags with multishot prompting (few-shot examples), you can include <thinking> tags in the example responses to show Claude the expected pattern of showing reasoning before the final answer.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can thinking tags be used in combination with Extended Thinking API?',
    option_a: 'No, they conflict with each other',
    option_b: 'Yes, but it may result in redundant reasoning output',
    option_c: 'Only in Opus 4.8',
    option_d: 'Only in streaming mode',
    correct_answer: 'B',
    explanation: 'You can technically use both, but it may result in redundant reasoning output: Extended Thinking provides its thinking block, and the prompt instructions ask for <thinking> tags, potentially duplicating the reasoning display.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is a best practice for using thinking tags in prompts?',
    option_a: 'Use them for every single query',
    option_b: 'Provide examples showing the expected thinking tag format',
    option_c: 'Always combine with Extended Thinking API',
    option_d: 'Use nested thinking tags for complex tasks',
    correct_answer: 'B',
    explanation: 'Best practice is to provide clear examples (few-shot prompting) showing how you want Claude to use <thinking> tags, including where they should appear and what content should go inside them.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How do thinking tags affect token usage compared to Extended Thinking API?',
    option_a: 'Thinking tags use more tokens',
    option_b: 'Extended Thinking uses more tokens',
    option_c: 'They use approximately the same number of tokens',
    option_d: 'Thinking tags are not counted in token usage',
    correct_answer: 'C',
    explanation: 'Both techniques result in similar token usage since both cause Claude to generate reasoning text before the answer. The main difference is in control and reliability, not token count.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which scenario is better suited for thinking tags technique rather than Extended Thinking API?',
    option_a: 'When you need guaranteed thinking block structure',
    option_b: 'When using older Claude models that don\'t support Extended Thinking',
    option_c: 'When you want to minimize costs',
    option_d: 'When processing images',
    correct_answer: 'B',
    explanation: 'Thinking tags technique is better when using older Claude models (like Claude 3 models) that don\'t support the Extended Thinking API parameter, or when you want portability across all model versions.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What happens if you instruct Claude to use thinking tags but also enable Extended Thinking API?',
    option_a: 'The API request fails',
    option_b: 'Only Extended Thinking output is shown',
    option_c: 'You may get both API thinking blocks and prompted thinking tags',
    option_d: 'Thinking tags override Extended Thinking',
    correct_answer: 'C',
    explanation: 'If you use both, Claude may produce both the API-level thinking block (from Extended Thinking) and the prompted <thinking> tags in the content, resulting in redundant reasoning output.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How many few-shot examples are typically recommended for effective multishot prompting with thinking tags?',
    option_a: '1-2 examples',
    option_b: '3-5 examples',
    option_c: '10-15 examples',
    option_d: 'At least 20 examples',
    correct_answer: 'B',
    explanation: 'Anthropic recommends 3-5 examples for effective multishot (few-shot) prompting. This provides enough pattern demonstration without excessive token usage or diminishing returns.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'When using thinking tags in prompts, should the tags appear in the user message or assistant message in examples?',
    option_a: 'User message',
    option_b: 'Assistant message',
    option_c: 'System prompt',
    option_d: 'Both user and assistant messages',
    correct_answer: 'B',
    explanation: 'Thinking tags should appear in the assistant message examples to show Claude how it should structure its own responses with reasoning before the final answer.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can thinking tags contain nested XML or other structured markup?',
    option_a: 'No, only plain text is allowed',
    option_b: 'Yes, you can nest structures within thinking tags',
    option_c: 'Only JSON is allowed inside',
    option_d: 'Only with Extended Thinking enabled',
    correct_answer: 'B',
    explanation: 'Thinking tags can contain nested XML, bullet points, or other structured markup to organize the reasoning. This helps Claude structure complex multi-step reasoning clearly.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the main disadvantage of using thinking tags technique compared to Extended Thinking API?',
    option_a: 'Higher cost',
    option_b: 'Slower response time',
    option_c: 'Less reliable - Claude may not always follow the instruction',
    option_d: 'Incompatible with streaming',
    correct_answer: 'C',
    explanation: 'The main disadvantage of thinking tags as a prompting technique is that it relies on Claude following your instructions, which may be less reliable than the API-enforced Extended Thinking feature.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What are the two main approaches for getting structured outputs from Claude?',
    option_a: 'XML mode and JSON mode',
    option_b: 'JSON mode and strict tool use',
    option_c: 'Extended Thinking and caching',
    option_d: 'Streaming and batch processing',
    correct_answer: 'B',
    explanation: 'The two main approaches for structured outputs are JSON mode (using output_config.format) and strict tool use (using strict: true in tool definitions). Both enforce schema compliance.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How do you enable JSON mode for structured outputs in Claude API?',
    option_a: 'Set output_format: "json"',
    option_b: 'Set output_config: {format: "json"}',
    option_c: 'Set json_mode: true',
    option_d: 'Set structured: {type: "json"}',
    correct_answer: 'B',
    explanation: 'JSON mode is enabled by setting output_config with format: "json" in the API request. This is the correct parameter structure for requesting JSON-formatted outputs.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What happens when you use strict tool use with a JSON schema?',
    option_a: 'The schema is ignored',
    option_b: 'The schema is compiled to a grammar that restricts token generation',
    option_c: 'The schema is only validated after generation',
    option_d: 'Multiple schemas can be combined',
    correct_answer: 'B',
    explanation: 'When using strict tool use, the JSON schema is compiled into a grammar that constrains token generation at the model level, guaranteeing schema-compliant output rather than just validating after generation.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the primary difference between JSON mode and strict tool use?',
    option_a: 'JSON mode is faster',
    option_b: 'Strict tool use provides stronger schema compliance guarantees',
    option_c: 'JSON mode supports more complex schemas',
    option_d: 'Strict tool use is only for Opus models',
    correct_answer: 'B',
    explanation: 'Strict tool use provides stronger schema compliance guarantees by compiling schemas to grammars that constrain generation, while JSON mode encourages JSON output but with slightly less rigid enforcement.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which parameter enables strict mode for tool use?',
    option_a: 'strict_mode: true',
    option_b: 'strict: true in the tool definition',
    option_c: 'enforce_schema: true',
    option_d: 'validation: "strict"',
    correct_answer: 'B',
    explanation: 'Strict mode for tool use is enabled by setting strict: true within the individual tool definition, not as a global parameter. This enables schema-constrained generation for that tool.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can you combine JSON mode with Extended Thinking?',
    option_a: 'No, they are incompatible',
    option_b: 'Yes, thinking happens before JSON generation',
    option_c: 'Only in Opus 4.8',
    option_d: 'Only without strict mode',
    correct_answer: 'B',
    explanation: 'JSON mode can be combined with Extended Thinking. Claude performs its reasoning in the thinking block, then generates JSON-formatted output based on that reasoning.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is a key limitation of using citations with JSON schema structured outputs?',
    option_a: 'Citations are automatically removed',
    option_b: 'Citations can conflict with strict JSON schema requirements',
    option_c: 'Citations double the token cost',
    option_d: 'Citations only work in XML mode',
    correct_answer: 'B',
    explanation: 'Citations can conflict with strict JSON schema requirements because citation metadata and reference structures may not fit within the defined schema constraints, making them incompatible with strict structured outputs.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How does schema complexity affect structured output generation?',
    option_a: 'Complex schemas generate faster',
    option_b: 'Schema complexity has no effect',
    option_c: 'More complex schemas take longer to compile to grammar',
    option_d: 'Complex schemas are not supported',
    correct_answer: 'C',
    explanation: 'More complex JSON schemas take longer to compile into the constraint grammar used for token generation. This can add latency to the first token, especially for very large or deeply nested schemas.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What type of JSON schemas are supported in structured outputs?',
    option_a: 'Only basic types (string, number, boolean)',
    option_b: 'JSON Schema Draft 7 and compatible subsets',
    option_c: 'Only custom Anthropic schema format',
    option_d: 'Any JSON format',
    correct_answer: 'B',
    explanation: 'Claude supports JSON Schema (typically Draft 7 and compatible subsets) for structured outputs. This is a standard schema format with defined types, properties, and validation rules.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can you use multiple tools with strict mode enabled in a single API call?',
    option_a: 'No, only one strict tool per call',
    option_b: 'Yes, multiple tools can each have strict: true',
    option_c: 'Only in Opus models',
    option_d: 'Only with JSON mode disabled',
    correct_answer: 'B',
    explanation: 'You can define multiple tools in a single API call, and each can independently have strict: true enabled. Claude can then choose which tool to use while respecting each tool\'s schema constraints.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What happens if Claude cannot generate output that satisfies a strict JSON schema?',
    option_a: 'It falls back to unstructured output',
    option_b: 'The API returns an error',
    option_c: 'It modifies the schema automatically',
    option_d: 'It retries with a simpler schema',
    correct_answer: 'B',
    explanation: 'If Claude cannot generate output that satisfies the strict schema constraints (e.g., the schema is impossible to satisfy given the task), the API will return an error rather than producing invalid output.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which of the following is a valid use case for JSON mode structured outputs?',
    option_a: 'Extracting structured data from unstructured text',
    option_b: 'Generating images',
    option_c: 'Reducing token costs',
    option_d: 'Enabling multimodal inputs',
    correct_answer: 'A',
    explanation: 'Extracting structured data from unstructured text is a perfect use case for JSON mode. For example, extracting product details, contact information, or metadata from documents into a consistent JSON format.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How should you provide the JSON schema when using strict tool use?',
    option_a: 'In the system prompt',
    option_b: 'In the tool definition\'s input_schema field',
    option_c: 'As a separate API parameter',
    option_d: 'In the user message',
    correct_answer: 'B',
    explanation: 'The JSON schema for strict tool use is provided in the tool definition\'s input_schema field. This schema defines the structure and validation rules for the tool\'s input parameters.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Does JSON mode guarantee 100% schema compliance?',
    option_a: 'Yes, always',
    option_b: 'No, it strongly encourages but doesn\'t guarantee compliance',
    option_c: 'Only with strict: true',
    option_d: 'Only in Opus models',
    correct_answer: 'B',
    explanation: 'JSON mode (output_config.format: "json") strongly encourages JSON output and schema compliance but doesn\'t provide the same hard guarantees as strict tool use. For 100% compliance, use strict tool use.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the benefit of schema compilation to grammar in strict mode?',
    option_a: 'Faster generation speed',
    option_b: 'Guaranteed schema compliance at generation time, not just validation after',
    option_c: 'Lower token costs',
    option_d: 'Support for more schema types',
    correct_answer: 'B',
    explanation: 'Schema compilation to grammar constrains token generation at the model level, guaranteeing that only schema-compliant outputs can be generated. This is more robust than generating output and then validating it.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can you request both text and JSON output in the same response?',
    option_a: 'Yes, using mixed mode',
    option_b: 'No, outputs must be entirely JSON or entirely text',
    option_c: 'Only with thinking enabled',
    option_d: 'Only in streaming mode',
    correct_answer: 'B',
    explanation: 'When JSON mode is enabled, the entire response content must be JSON. You cannot mix freeform text and JSON in the same response content (though thinking blocks are separate from response content).',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is a recommended practice for complex JSON schemas?',
    option_a: 'Use deeply nested structures (10+ levels)',
    option_b: 'Keep schemas as simple as possible while meeting requirements',
    option_c: 'Always use arrays instead of objects',
    option_d: 'Avoid required fields',
    correct_answer: 'B',
    explanation: 'Best practice is to keep JSON schemas as simple as possible while meeting your requirements. Overly complex schemas increase compilation time, reduce reliability, and make debugging harder.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which models support structured outputs with JSON mode and strict tool use?',
    option_a: 'Only Claude 4 models',
    option_b: 'All Claude 3 and 4 models',
    option_c: 'Opus 4.8, Mythos Preview, Opus 4.7/4.6, Sonnet 4.6/4.5, Haiku 4.5',
    option_d: 'Only Opus 4.8 and Sonnet 4.6',
    correct_answer: 'C',
    explanation: 'Structured outputs are supported on the same models as Extended Thinking: Opus 4.8, Mythos Preview, Opus 4.7, Opus 4.6, Sonnet 4.6, Sonnet 4.5, and Haiku 4.5.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What happens to arrays in JSON schema strict mode?',
    option_a: 'Arrays are not supported',
    option_b: 'Array items must conform to the defined schema',
    option_c: 'Arrays are automatically limited to 10 items',
    option_d: 'Arrays are converted to objects',
    correct_answer: 'B',
    explanation: 'In strict mode, array items must conform to the schema defined in the "items" field. The schema compiler ensures each array element matches the specified type and structure.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is a common limitation when using very complex JSON schemas?',
    option_a: 'They don\'t work at all',
    option_b: 'Increased compilation time and potential timeout',
    option_c: 'They produce faster results',
    option_d: 'They reduce accuracy',
    correct_answer: 'B',
    explanation: 'Very complex JSON schemas can have increased compilation time as they are converted to constraint grammars. Extremely complex schemas may even timeout or fail to compile.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How deep can nested objects be in a JSON schema for structured outputs?',
    option_a: 'Maximum 3 levels',
    option_b: 'No hard limit, but practical limits exist due to complexity',
    option_c: 'Maximum 10 levels',
    option_d: 'Nesting is not allowed',
    correct_answer: 'B',
    explanation: 'There is no hard-coded limit on nesting depth, but practical limits exist. Very deep nesting increases schema complexity, compilation time, and the likelihood of errors or timeouts.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can you use regex patterns in JSON schema for structured outputs?',
    option_a: 'No, regex is not supported',
    option_b: 'Yes, using the "pattern" property for strings',
    option_c: 'Only in Opus models',
    option_d: 'Only for email validation',
    correct_answer: 'B',
    explanation: 'JSON Schema supports regex patterns using the "pattern" property for string fields. This allows you to enforce formats like email addresses, phone numbers, or custom patterns.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the impact of using enum constraints in JSON schemas?',
    option_a: 'They are ignored by Claude',
    option_b: 'They restrict output to specific allowed values',
    option_c: 'They increase token costs',
    option_d: 'They only work with strings',
    correct_answer: 'B',
    explanation: 'Enum constraints restrict the output to a specific set of allowed values. The schema compiler ensures Claude can only generate tokens matching one of the enum values for that field.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Why might citations conflict with strict JSON schemas?',
    option_a: 'Citations use XML format',
    option_b: 'Citation metadata structures may not fit the defined schema',
    option_c: 'Citations require a separate API parameter',
    option_d: 'Citations are deprecated',
    correct_answer: 'B',
    explanation: 'Citations add metadata and reference structures to the output. In strict JSON schema mode, these additional structures may not match the defined schema, creating a conflict between citation requirements and schema constraints.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What happens if you define required fields in a JSON schema?',
    option_a: 'They are treated as optional',
    option_b: 'Claude must include them in the output',
    option_c: 'The schema is rejected',
    option_d: 'Only Opus models respect required fields',
    correct_answer: 'B',
    explanation: 'Required fields in the JSON schema must be included in Claude\'s output. The constraint grammar ensures that all required fields are present in the generated JSON.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can you use conditional schemas (if/then/else) in structured outputs?',
    option_a: 'No, only basic schemas are supported',
    option_b: 'Yes, but they increase schema complexity',
    option_c: 'Only in JSON mode, not strict tool use',
    option_d: 'Only with Extended Thinking enabled',
    correct_answer: 'B',
    explanation: 'JSON Schema conditional logic (if/then/else) is supported but increases schema complexity. This can impact compilation time and reliability, so simpler schemas are generally preferred.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the recommended approach when a task needs both free text and structured data?',
    option_a: 'Use two separate API calls',
    option_b: 'Include a text field in the JSON schema',
    option_c: 'Disable structured outputs',
    option_d: 'Use XML instead of JSON',
    correct_answer: 'B',
    explanation: 'The recommended approach is to include a text or description field in your JSON schema where free-form text can be placed. This keeps the output structured while allowing for narrative content.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the duration of prompt caching in Claude API?',
    option_a: '30 minutes',
    option_b: '1 hour',
    option_c: '6 hours',
    option_d: '24 hours',
    correct_answer: 'B',
    explanation: 'Prompt caching in Claude API lasts for 1 hour. Cached content remains available for reuse within this time window, after which it expires and must be cached again.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Which Claude models support caching of thinking blocks from Extended Thinking?',
    option_a: 'All models',
    option_b: 'Only Opus models',
    option_c: 'Opus 4.5+ and Sonnet 4.6+',
    option_d: 'Only Claude 4 models',
    correct_answer: 'C',
    explanation: 'Thinking blocks from Extended Thinking can be cached on Opus 4.5 and later versions, and Sonnet 4.6 and later versions. Earlier models don\'t support caching thinking blocks.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How does prompt caching interact with structured outputs?',
    option_a: 'Caching disables structured outputs',
    option_b: 'The schema can be cached as part of the system prompt',
    option_c: 'Structured outputs cannot be cached',
    option_d: 'Caching only works with JSON mode',
    correct_answer: 'B',
    explanation: 'JSON schemas and tool definitions can be cached as part of the system prompt or tool definitions. This reduces costs when using the same schema repeatedly across multiple requests.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What invalidates the prompt cache?',
    option_a: 'Using a different model version',
    option_b: 'Any change to the cached content',
    option_c: 'Adding new user messages',
    option_d: 'Enabling Extended Thinking',
    correct_answer: 'A',
    explanation: 'The cache is invalidated by any change to the cached content itself, including modifications to system prompts, tools, or other cached blocks. The cache is content-specific and exact-match.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can you cache few-shot examples in multishot prompting?',
    option_a: 'No, only system prompts can be cached',
    option_b: 'Yes, examples in the prompt can be cached',
    option_c: 'Only the first example is cached',
    option_d: 'Only with Extended Thinking enabled',
    correct_answer: 'B',
    explanation: 'Few-shot examples included in your prompt can be cached, which is particularly valuable since examples can consume many tokens. This makes multishot prompting more cost-effective when reused.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is a best practice for maximizing cache benefits?',
    option_a: 'Change prompts frequently',
    option_b: 'Put frequently changing content at the end',
    option_c: 'Use different models for each request',
    option_d: 'Disable caching for consistency',
    correct_answer: 'B',
    explanation: 'Put frequently changing content (like the specific user query) at the end of the prompt, and stable content (like instructions, examples, schemas) at the beginning where it can be cached.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How does caching affect token costs?',
    option_a: 'Cached tokens are free',
    option_b: 'Cached tokens cost about 90% less than regular input tokens',
    option_c: 'Caching increases costs',
    option_d: 'Caching only affects output token costs',
    correct_answer: 'B',
    explanation: 'Cached input tokens cost approximately 90% less than regular input tokens (exact discount varies by model). This provides significant cost savings for repeated content.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can thinking blocks from Extended Thinking be cached on Sonnet 4.5?',
    option_a: 'No, only Sonnet 4.6+ supports this',
    option_b: 'Yes, Sonnet 4.5 supports caching thinking blocks',
    option_c: 'Only if JSON mode is enabled',
    option_d: 'Only in streaming mode',
    correct_answer: 'B',
    explanation: 'Sonnet 4.5 and later versions support caching of thinking blocks from Extended Thinking, along with Opus 4.5 and later. Earlier models don\'t support this feature.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What happens when cached content expires after 1 hour?',
    option_a: 'The API returns an error',
    option_b: 'The content is automatically re-cached at full cost',
    option_c: 'Requests fail until manual re-caching',
    option_d: 'Cache duration extends automatically',
    correct_answer: 'B',
    explanation: 'When cached content expires after 1 hour, the next request with that content will be processed normally (at full input token cost) and the content will be re-cached for another hour.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can you cache part of a prompt while leaving other parts uncached?',
    option_a: 'No, it\'s all or nothing',
    option_b: 'Yes, using cache control markers',
    option_c: 'Only system prompts can be selectively cached',
    option_d: 'Only with Extended Thinking',
    correct_answer: 'B',
    explanation: 'You can selectively cache portions of a prompt using cache control markers, allowing you to cache stable content (like instructions) while keeping dynamic content (like the specific query) uncached.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is multishot prompting?',
    option_a: 'Sending multiple API requests in parallel',
    option_b: 'Providing multiple examples in the prompt to demonstrate desired behavior',
    option_c: 'Using multiple models simultaneously',
    option_d: 'Caching multiple prompts',
    correct_answer: 'B',
    explanation: 'Multishot (or few-shot) prompting involves providing multiple examples in the prompt to demonstrate the desired input-output pattern. This helps Claude understand the expected behavior.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How many examples are typically recommended for effective multishot prompting?',
    option_a: '1-2 examples',
    option_b: '3-5 examples',
    option_c: '10-15 examples',
    option_d: 'At least 50 examples',
    correct_answer: 'B',
    explanation: 'Anthropic recommends 3-5 examples for effective multishot prompting. This provides enough pattern demonstration without excessive token usage. More examples don\'t always improve results.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can multishot examples include thinking tags?',
    option_a: 'No, only final answers',
    option_b: 'Yes, showing reasoning in examples improves quality',
    option_c: 'Only with Extended Thinking enabled',
    option_d: 'Only in Opus models',
    correct_answer: 'B',
    explanation: 'Examples in multishot prompting can include thinking tags to demonstrate the reasoning process. This teaches Claude to show its work and improves response quality on complex tasks.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the primary benefit of multishot prompting over zero-shot?',
    option_a: 'Faster response time',
    option_b: 'Lower token costs',
    option_c: 'Improved accuracy and consistency through demonstration',
    option_d: 'Access to additional model features',
    correct_answer: 'C',
    explanation: 'Multishot prompting improves accuracy and consistency by demonstrating the exact pattern you want Claude to follow. Examples are more effective than instructions alone for complex formatting or reasoning patterns.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How should examples be formatted in multishot prompting?',
    option_a: 'As plain text only',
    option_b: 'As user/assistant message pairs',
    option_c: 'As JSON objects',
    option_d: 'In the system prompt only',
    correct_answer: 'B',
    explanation: 'Examples should be formatted as user/assistant message pairs in the conversation history. This shows Claude both the input pattern (user message) and the expected output pattern (assistant message).',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Can multishot examples be cached?',
    option_a: 'No, only system prompts are cached',
    option_b: 'Yes, and this is highly recommended for cost savings',
    option_c: 'Only the first example is cached',
    option_d: 'Only with JSON mode enabled',
    correct_answer: 'B',
    explanation: 'Multishot examples can and should be cached since they often consume many tokens and remain constant across requests. This provides significant cost savings for repeated use of the same examples.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is a common pitfall when creating multishot examples?',
    option_a: 'Using too many examples (diminishing returns)',
    option_b: 'Including reasoning in examples',
    option_c: 'Using real-world data',
    option_d: 'Showing diverse scenarios',
    correct_answer: 'A',
    explanation: 'A common pitfall is using too many examples. Beyond 3-5 examples, you typically get diminishing returns while consuming more tokens. Quality and diversity of examples matter more than quantity.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'Should multishot examples cover edge cases or typical cases?',
    option_a: 'Only edge cases',
    option_b: 'Only typical cases',
    option_c: 'A mix of both is ideal',
    option_d: 'Neither, examples should be abstract',
    correct_answer: 'C',
    explanation: 'A mix of typical and edge cases is ideal. Typical cases show the common pattern, while edge cases demonstrate how to handle unusual situations. This combination improves robustness.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How does multishot prompting interact with structured outputs?',
    option_a: 'They cannot be combined',
    option_b: 'Examples can demonstrate the expected JSON structure',
    option_c: 'Multishot disables schema validation',
    option_d: 'Only zero-shot works with structured outputs',
    correct_answer: 'B',
    explanation: 'Multishot prompting combines well with structured outputs. Examples can demonstrate the expected JSON structure and content patterns, complementing the schema constraints.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the difference between few-shot and multishot prompting?',
    option_a: 'They are different terms for the same concept',
    option_b: 'Few-shot uses 1-2 examples, multishot uses 3+',
    option_c: 'Few-shot is for Opus, multishot is for Sonnet',
    option_d: 'Few-shot requires caching, multishot doesn\'t',
    correct_answer: 'A',
    explanation: 'Few-shot and multishot are different terms for the same concept: providing multiple examples in the prompt to demonstrate the desired behavior. The terms are used interchangeably.',
    difficulty: 'easy'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is a best practice for combining XML tags with structured outputs?',
    option_a: 'Avoid XML when using JSON mode',
    option_b: 'Use XML tags to organize the prompt, JSON schema for output',
    option_c: 'XML and JSON are incompatible',
    option_d: 'Always prefer XML over JSON',
    correct_answer: 'B',
    explanation: 'Best practice is to use XML tags to organize your prompt (context, instructions, examples) while using JSON schema to define the output structure. These complement each other well.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'When should you use Extended Thinking vs thinking tags technique?',
    option_a: 'Always use Extended Thinking',
    option_b: 'Extended Thinking for supported models and guaranteed structure; thinking tags for older models or flexibility',
    option_c: 'Always use thinking tags',
    option_d: 'They should never be used together',
    correct_answer: 'B',
    explanation: 'Use Extended Thinking API when you need guaranteed thinking block structure on supported models. Use thinking tags prompting technique for older models, or when you need more flexibility in the reasoning format.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the recommended way to handle complex multi-step tasks?',
    option_a: 'Use only Extended Thinking',
    option_b: 'Combine Extended Thinking, structured outputs, and clear instructions',
    option_c: 'Split into multiple API calls',
    option_d: 'Use only thinking tags',
    correct_answer: 'B',
    explanation: 'For complex multi-step tasks, combine Extended Thinking (for reasoning), structured outputs (for consistent results), and clear XML-tagged instructions. This multi-layered approach produces the best results.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How should you optimize prompts for both quality and cost?',
    option_a: 'Use the shortest possible prompts',
    option_b: 'Cache stable content, use multishot examples, and leverage structured outputs',
    option_c: 'Avoid all advanced features',
    option_d: 'Always use the smallest model',
    correct_answer: 'B',
    explanation: 'Optimize by caching stable content (instructions, examples, schemas), using multishot examples efficiently, and leveraging structured outputs to reduce retry logic. This balances quality with cost-effectiveness.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What happens when you combine all advanced features: Extended Thinking, strict JSON schema, multishot examples, and caching?',
    option_a: 'API returns an error due to conflicts',
    option_b: 'They work together: cached examples, reasoning in thinking, structured output',
    option_c: 'Only the first enabled feature works',
    option_d: 'Performance degrades significantly',
    correct_answer: 'B',
    explanation: 'All these features can work together harmoniously: cached multishot examples reduce cost, Extended Thinking provides reasoning, and strict JSON schema ensures structured output. This is a powerful combination for complex tasks.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is the most common mistake when using JSON schemas?',
    option_a: 'Making them too simple',
    option_b: 'Making them overly complex beyond what\'s needed',
    option_c: 'Using required fields',
    option_d: 'Including examples',
    correct_answer: 'B',
    explanation: 'The most common mistake is creating overly complex schemas with deep nesting, excessive fields, or unnecessary complexity. Simpler schemas are more reliable, faster to compile, and easier to debug.',
    difficulty: 'medium'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'When should you use effort levels in Opus 4.8?',
    option_a: 'Always set to maximum (xhigh)',
    option_b: 'Match effort level to task complexity',
    option_c: 'Effort levels don\'t affect output',
    option_d: 'Only use with Extended Thinking',
    correct_answer: 'B',
    explanation: 'Match effort level to task complexity: low for simple tasks, medium for moderate complexity, high or xhigh for complex reasoning. Using higher effort than needed wastes resources; too low effort may reduce quality.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'What is an edge case to consider with prompt caching?',
    option_a: 'Cache applies across different API keys',
    option_b: 'Slight prompt modifications invalidate the entire cache',
    option_c: 'Caching works indefinitely',
    option_d: 'Cache is shared between all users',
    correct_answer: 'B',
    explanation: 'An important edge case: even slight modifications to cached content (like adding a space or changing punctuation) invalidate the entire cache for that block. The cache is exact-match only.',
    difficulty: 'hard'
  },
  {
    week: 7,
    domain: 'Prompt Engineering & Structured Output',
    topic: 'Prompt Engineering & Structured Output',
    question: 'How can you verify that your JSON schema is working correctly?',
    option_a: 'Schemas are automatically validated',
    option_b: 'Test with multiple examples and check output compliance',
    option_c: 'Use only simple schemas',
    option_d: 'Schema validation is not possible',
    correct_answer: 'B',
    explanation: 'Verify JSON schemas by testing with diverse inputs and checking that outputs consistently comply with the schema. Also test edge cases and invalid scenarios to ensure the schema behaves as expected.',
    difficulty: 'medium'
  }
];
