export interface Question {
  week?: number;
  domain: string;
  topic: string;
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_answer: string;
  explanation: string;
  difficulty?: string;
}

export const topic10Questions: Question[] = [
  // Citations feature basics (15 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What is the primary purpose of Claude's Citations feature?",
    option_a: "To improve response speed",
    option_b: "To provide automatic source attribution in responses",
    option_c: "To reduce token costs",
    option_d: "To increase context window size",
    correct_answer: "B",
    explanation: "The Citations feature provides automatic source attribution in Claude's responses, allowing users to trace answers back to specific sources in the provided documents.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What is document grounding in the context of Citations?",
    option_a: "Storing documents on servers",
    option_b: "Ensuring answers come from supplied documents",
    option_c: "Compressing document size",
    option_d: "Translating documents",
    correct_answer: "B",
    explanation: "Document grounding ensures that Claude's answers are based on the supplied documents, providing verifiable sources for the information in responses.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What type of references does Citations provide?",
    option_a: "Only document titles",
    option_b: "Traceable references with specific source spans",
    option_c: "General topic areas",
    option_d: "URL links only",
    correct_answer: "B",
    explanation: "Citations provides traceable references with specific source spans, such as page numbers in PDFs or character ranges in text, allowing precise verification of sources.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "By how much does Citations improve recall accuracy compared to custom implementations?",
    option_a: "5%",
    option_b: "10%",
    option_c: "15%",
    option_d: "25%",
    correct_answer: "C",
    explanation: "Citations provides approximately 15% improved recall accuracy compared to custom implementations, demonstrating the effectiveness of the built-in feature.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What happens when you use Citations with strict JSON schema?",
    option_a: "Citations are automatically formatted as JSON",
    option_b: "The API returns a 400 error",
    option_c: "Citations are disabled silently",
    option_d: "JSON schema is ignored",
    correct_answer: "B",
    explanation: "Citations conflict with strict JSON schema mode and will return a 400 error. You cannot use both features simultaneously.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your application requires both structured JSON output and source attribution. What should you do?",
    option_a: "Use Citations and ignore the JSON schema conflict",
    option_b: "Implement custom citation logic without strict JSON schema",
    option_c: "Use Citations and request JSON in the prompt",
    option_d: "Alternate between Citations and JSON schema per request",
    correct_answer: "B",
    explanation: "Since Citations conflicts with strict JSON schema, implement custom citation logic or use non-strict JSON output if you need both structured output and source attribution.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What is the primary benefit of Citations for enterprise applications?",
    option_a: "Reduced API costs",
    option_b: "Verifiable, auditable responses",
    option_c: "Faster response times",
    option_d: "Larger context windows",
    correct_answer: "B",
    explanation: "The primary benefit for enterprise applications is verifiable, auditable responses. Citations allow compliance, legal, and quality teams to verify that information comes from approved sources.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can Citations work with documents stored externally?",
    option_a: "Yes, by providing URLs",
    option_b: "No, documents must be included in the request",
    option_c: "Yes, through document IDs",
    option_d: "Only for Enterprise accounts",
    correct_answer: "B",
    explanation: "Citations requires documents to be included in the request. It doesn't fetch external documents or work with URLs alone; the content must be provided to Claude.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How does Citations affect token costs?",
    option_a: "Significantly increases costs due to extra processing",
    option_b: "Reduces costs through optimized processing",
    option_c: "Minimal impact; documents are tokenized normally",
    option_d: "Doubles token costs for cited content",
    correct_answer: "C",
    explanation: "Citations has minimal impact on token costs. Documents are tokenized normally as input, and the citation metadata adds minimal overhead to the output.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What types of content can Citations attribute sources for?",
    option_a: "Only factual statements",
    option_b: "Any content in Claude's response",
    option_c: "Only direct quotes",
    option_d: "Only numerical data",
    correct_answer: "B",
    explanation: "Citations can attribute sources for any content in Claude's response, including facts, analysis, summaries, and paraphrased content, as long as it's based on the provided documents.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How are citations presented in the API response?",
    option_a: "As inline markdown links",
    option_b: "As structured metadata with source references",
    option_c: "As footnotes at the end",
    option_d: "As HTML annotations",
    correct_answer: "B",
    explanation: "Citations are presented as structured metadata in the API response, including source references with specific location information like page numbers or character ranges.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can you use Citations for real-time data streams?",
    option_a: "Yes, Citations work with any input",
    option_b: "No, Citations require static documents",
    option_c: "Yes, but only for Enterprise accounts",
    option_d: "Yes, with special streaming citations mode",
    correct_answer: "B",
    explanation: "Citations work best with static documents that can be referenced consistently. Real-time data streams that change constantly aren't suitable for citation tracking as the sources become invalid.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's the relationship between Citations and prompt caching?",
    option_a: "They are mutually exclusive",
    option_b: "They work together; cache documents and cite them",
    option_c: "Caching disables Citations",
    option_d: "Citations automatically enable caching",
    correct_answer: "B",
    explanation: "Citations and prompt caching work together well. You can cache documents and still use Citations to reference them, combining cost savings with source attribution.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "When should you NOT use Citations?",
    option_a: "When processing multiple documents",
    option_b: "When you need strict JSON schema output",
    option_c: "When documents are over 50K tokens",
    option_d: "When using Enterprise accounts",
    correct_answer: "B",
    explanation: "Don't use Citations when you need strict JSON schema output, as they conflict and cause a 400 error. Also avoid if citation overhead isn't needed for your use case.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How does Citations help with hallucination prevention?",
    option_a: "It eliminates hallucinations completely",
    option_b: "It grounds responses in provided documents with traceable references",
    option_c: "It has no effect on hallucinations",
    option_d: "It only helps for numerical data",
    correct_answer: "B",
    explanation: "Citations helps prevent hallucinations by grounding responses in provided documents and requiring traceable references. This encourages Claude to base answers on supplied information rather than generating unsupported content.",
    difficulty: "medium"
  },

  // Document grounding (15 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What does document grounding ensure?",
    option_a: "Documents are stored permanently",
    option_b: "Answers are based on supplied documents",
    option_c: "Documents are compressed efficiently",
    option_d: "Documents are translated automatically",
    correct_answer: "B",
    explanation: "Document grounding ensures that Claude's answers are based on the supplied documents rather than general knowledge, providing verifiable, source-backed responses.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How many documents can you provide for grounding in a single request?",
    option_a: "Only 1 document",
    option_b: "Up to 5 documents",
    option_c: "Limited only by context window size",
    option_d: "Unlimited with pagination",
    correct_answer: "C",
    explanation: "You can provide as many documents as fit within the context window. There's no artificial limit on document count, only the practical constraint of total token count.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's the advantage of document grounding over asking Claude to cite sources manually?",
    option_a: "It's faster",
    option_b: "It provides structured, verifiable references automatically",
    option_c: "It uses fewer tokens",
    option_d: "It works with larger documents",
    correct_answer: "B",
    explanation: "Document grounding with Citations provides structured, verifiable references automatically with 15% better recall accuracy compared to manual citation prompts or custom implementations.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can document grounding work with documents in different formats in the same request?",
    option_a: "No, all documents must be the same format",
    option_b: "Yes, you can mix PDFs, text, and custom content",
    option_c: "Only PDF and text, not custom content",
    option_d: "Only with Enterprise accounts",
    correct_answer: "B",
    explanation: "Document grounding supports mixing different formats (PDFs, plain text, custom content) in the same request, each with appropriate citation formats.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your legal research assistant needs to answer questions using only case law documents. What's the best approach?",
    option_a: "Fine-tune Claude on case law",
    option_b: "Use document grounding with Citations",
    option_c: "Prompt Claude to only use provided documents",
    option_d: "Implement custom fact-checking",
    correct_answer: "B",
    explanation: "Document grounding with Citations is ideal for legal research, ensuring answers are based only on provided case law with traceable references to specific sections or pages.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What happens if Claude cannot find an answer in the grounded documents?",
    option_a: "It fabricates an answer from general knowledge",
    option_b: "It indicates it cannot find the information in the provided documents",
    option_c: "It returns an error",
    option_d: "It searches external sources automatically",
    correct_answer: "B",
    explanation: "When using document grounding, if Claude cannot find an answer in the provided documents, it will indicate that the information isn't available in the sources rather than using general knowledge.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How does document grounding affect response quality?",
    option_a: "It always reduces quality by restricting knowledge",
    option_b: "It improves reliability and verifiability of responses",
    option_c: "It has no effect on quality",
    option_d: "It only affects speed, not quality",
    correct_answer: "B",
    explanation: "Document grounding improves the reliability and verifiability of responses by ensuring they're based on provided sources, even if it sometimes means acknowledging when information isn't available.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can you partially ground responses (some from documents, some from general knowledge)?",
    option_a: "Yes, by default Claude mixes both",
    option_b: "No, grounding is all-or-nothing",
    option_c: "Yes, with specific prompt instructions",
    option_d: "Only for Enterprise accounts",
    correct_answer: "C",
    explanation: "You can partially ground responses through prompt instructions, asking Claude to use documents for certain information while allowing general knowledge for others, though this reduces the strict verification benefits.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's the recommended document size for optimal grounding?",
    option_a: "Under 1K tokens per document",
    option_b: "Under 10K tokens per document",
    option_c: "No specific limit; depends on use case",
    option_d: "Exactly 50K tokens per document",
    correct_answer: "C",
    explanation: "There's no specific recommended document size limit. Document size should be determined by your use case and context window constraints. Grounding works with documents of various sizes.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How should contradictory information across grounded documents be handled?",
    option_a: "Claude automatically resolves contradictions",
    option_b: "Claude can identify and cite contradictory sources",
    option_c: "Only the first document is used",
    option_d: "Contradictions cause API errors",
    correct_answer: "B",
    explanation: "Claude can identify contradictory information across documents and cite the different sources, allowing users to understand that sources disagree rather than hiding the contradiction.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's the benefit of document grounding for customer support applications?",
    option_a: "Faster response times",
    option_b: "Ensuring answers align with official documentation",
    option_c: "Reduced API costs",
    option_d: "Unlimited conversation length",
    correct_answer: "B",
    explanation: "For customer support, document grounding ensures answers align with official documentation, policies, and procedures, preventing incorrect information from general knowledge.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can document grounding work with documents that update frequently?",
    option_a: "No, only static documents are supported",
    option_b: "Yes, just provide the updated documents in each request",
    option_c: "Yes, Claude tracks document versions automatically",
    option_d: "Only with special versioning mode",
    correct_answer: "B",
    explanation: "Document grounding works with frequently updated documents by providing the current version in each request. There's no automatic version tracking; you manage which version to include.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How does document grounding interact with Claude's general knowledge?",
    option_a: "It completely replaces general knowledge",
    option_b: "It prioritizes documents but allows general knowledge for context",
    option_c: "It has no effect on general knowledge",
    option_d: "It merges documents with general knowledge equally",
    correct_answer: "B",
    explanation: "Document grounding prioritizes provided documents for factual answers but Claude can still use general knowledge for language understanding, reasoning, and contextual interpretation.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's a best practice for document preparation before grounding?",
    option_a: "Always summarize documents first",
    option_b: "Provide documents as-is with clear structure",
    option_c: "Convert everything to plain text",
    option_d: "Split documents into 1K token chunks",
    correct_answer: "B",
    explanation: "Best practice is providing documents as-is with clear structure (proper formatting, sections, metadata). This allows Citations to provide accurate references and Claude to understand document organization.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can you ground responses on code repositories?",
    option_a: "No, only text documents are supported",
    option_b: "Yes, code can be provided as documents",
    option_c: "Only with special code mode",
    option_d: "Only for Python code",
    correct_answer: "B",
    explanation: "Yes, code repositories can be provided as documents for grounding. Claude can cite specific files, functions, or line ranges when answering questions about the code.",
    difficulty: "medium"
  },

  // Citation formats (PDF, text, custom) (20 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How are PDF citations formatted?",
    option_a: "Character index range (0-indexed)",
    option_b: "Page number range (1-indexed)",
    option_c: "Paragraph numbers",
    option_d: "Line numbers",
    correct_answer: "B",
    explanation: "PDF citations use page number ranges with 1-indexed numbering (e.g., pages 5-7), making it easy to locate information in the original PDF document.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How are plain text citations formatted?",
    option_a: "Page numbers (1-indexed)",
    option_b: "Word count offsets",
    option_c: "Character index range (0-indexed)",
    option_d: "Line numbers",
    correct_answer: "C",
    explanation: "Plain text citations use character index ranges with 0-indexed numbering, allowing precise location of cited content within the text string.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How are custom content citations formatted?",
    option_a: "Page numbers",
    option_b: "Character indices",
    option_c: "Content block index range (0-indexed)",
    option_d: "Custom IDs from metadata",
    correct_answer: "C",
    explanation: "Custom content citations use content block index ranges with 0-indexed numbering, referencing which blocks or sections of the custom content were used.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Why are PDF citations 1-indexed while text citations are 0-indexed?",
    option_a: "It's a bug that will be fixed",
    option_b: "To match common conventions (PDF pages start at 1, string indices at 0)",
    option_c: "For backwards compatibility",
    option_d: "Random design choice",
    correct_answer: "B",
    explanation: "The indexing matches common conventions: PDF page numbers naturally start at 1 (as readers see them), while character indices in programming typically start at 0.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "You provide a 50-page PDF and Claude cites 'pages 10-12'. What does this mean?",
    option_a: "The 10th through 12th characters",
    option_b: "The actual pages numbered 10, 11, and 12 in the PDF",
    option_c: "The 10th through 12th content blocks",
    option_d: "Indices 10-12 in a 0-indexed array",
    correct_answer: "B",
    explanation: "For PDFs, page numbers refer to the actual pages as they appear in the PDF, using 1-indexed numbering. Pages 10-12 means the tenth, eleventh, and twelfth pages.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "You provide plain text and Claude cites 'characters 500-750'. How do you locate this?",
    option_a: "Count 500 words from the start",
    option_b: "Count 500 characters from the start (0-indexed)",
    option_c: "Go to page 500-750",
    option_d: "Use line 500 through line 750",
    correct_answer: "B",
    explanation: "For plain text, character indices are 0-indexed. Characters 500-750 means starting at the 501st character (index 500) through the 751st character (index 750) in the string.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What is custom content in the context of Citations?",
    option_a: "User-defined document formats",
    option_b: "Structured content with defined blocks or sections",
    option_c: "Encrypted documents",
    option_d: "Compressed documents",
    correct_answer: "B",
    explanation: "Custom content refers to structured content with defined blocks or sections (like JSON objects, XML elements, or structured data), where citations reference specific blocks by index.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can you mix PDF, text, and custom content in a single request?",
    option_a: "No, only one format per request",
    option_b: "Yes, Citations handles multiple formats with appropriate references",
    option_c: "Only PDF and text together",
    option_d: "Only with Enterprise accounts",
    correct_answer: "B",
    explanation: "You can mix different document formats in a single request, and Citations will use the appropriate citation format (page numbers, character indices, or block indices) for each document type.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your PDF has non-sequential page numbers (e.g., i, ii, 1, 2). How are citations formatted?",
    option_a: "Using the printed page numbers (i, ii, 1, 2)",
    option_b: "Using sequential 1-indexed numbers regardless of printed numbers",
    option_c: "Using 0-indexed positions",
    option_d: "Citations fail for such PDFs",
    correct_answer: "B",
    explanation: "Citations use sequential 1-indexed numbers based on physical page position, not the printed page numbers. The first page is 1, second is 2, regardless of what's printed on the page.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How precise are character-based text citations?",
    option_a: "Exact character ranges where cited content appears",
    option_b: "Approximate paragraph locations",
    option_c: "Whole document references only",
    option_d: "Line number approximations",
    correct_answer: "A",
    explanation: "Character-based text citations provide exact character ranges where the cited content appears, allowing precise verification of sources down to the specific characters.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's the advantage of content block citations for structured data?",
    option_a: "They're more accurate than page numbers",
    option_b: "They reference logical units rather than arbitrary character positions",
    option_c: "They use less memory",
    option_d: "They work with larger documents",
    correct_answer: "B",
    explanation: "Content block citations reference logical units (like JSON objects or XML elements), which is more meaningful for structured data than arbitrary character positions or page numbers.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "You provide a JSON array of 100 objects. Claude cites 'blocks 10-15'. What does this reference?",
    option_a: "Characters 10-15 in the JSON",
    option_b: "Pages 10-15",
    option_c: "The 11th through 16th objects (0-indexed)",
    option_d: "Lines 10-15",
    correct_answer: "C",
    explanation: "For custom content, block indices are 0-indexed. Blocks 10-15 reference the 11th through 16th elements (indices 10-15) in the array.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How should you prepare PDFs for optimal citation accuracy?",
    option_a: "Convert to plain text first",
    option_b: "Ensure text is extractable and well-formatted",
    option_c: "Split into single-page PDFs",
    option_d: "Remove all images",
    correct_answer: "B",
    explanation: "Ensure PDFs have extractable text and proper formatting. Scanned PDFs without OCR or poorly formatted PDFs may result in less accurate citations.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can citations span across multiple pages in a PDF?",
    option_a: "No, citations are always single pages",
    option_b: "Yes, citations can reference page ranges like 5-7",
    option_c: "Only for Enterprise accounts",
    option_d: "Only if pages are consecutive",
    correct_answer: "B",
    explanation: "Citations can span multiple pages when the cited content crosses page boundaries, indicated as page ranges like 5-7.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's a limitation of character-based text citations?",
    option_a: "They're not precise enough",
    option_b: "They don't work for multi-line content",
    option_c: "They can be difficult for humans to navigate without tooling",
    option_d: "They only work for English text",
    correct_answer: "C",
    explanation: "Character-based citations are very precise but can be difficult for humans to manually navigate without tooling (like a text editor that shows character positions).",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How do citations handle documents with complex layouts (tables, columns)?",
    option_a: "Citations fail for complex layouts",
    option_b: "Citations reference the extracted text order",
    option_c: "Only table cells are cited",
    option_d: "Complex layouts require manual annotation",
    correct_answer: "B",
    explanation: "For complex layouts, citations reference content in the order it's extracted as text. The accuracy depends on how well the extraction preserves meaningful reading order.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your application presents citations to end users. What's the best practice?",
    option_a: "Show raw citation data only",
    option_b: "Convert citations to user-friendly format with links or highlights",
    option_c: "Hide citations from users",
    option_d: "Only show citations for direct quotes",
    correct_answer: "B",
    explanation: "Convert raw citation data to user-friendly formats, such as clickable links to page numbers, highlighted text ranges, or expandable source previews, making verification easy for users.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can you customize the citation format returned by the API?",
    option_a: "Yes, via format parameter",
    option_b: "No, formats are fixed based on document type",
    option_c: "Yes, but only for Enterprise accounts",
    option_d: "Yes, through custom citation templates",
    correct_answer: "B",
    explanation: "Citation formats are fixed based on document type (pages for PDF, characters for text, blocks for custom content). You can't customize the format, but you can transform it client-side for display.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How do citations work with documents containing images?",
    option_a: "Images are automatically described and cited",
    option_b: "Images are skipped; only text is cited",
    option_c: "Images must be extracted separately",
    option_d: "Citations fail if images are present",
    correct_answer: "B",
    explanation: "Citations focus on text content. Images in documents are typically skipped for citation purposes, though Claude can process and reference them if they're relevant to the context.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's the most granular citation format available?",
    option_a: "Page numbers (PDFs)",
    option_b: "Character indices (plain text)",
    option_c: "Content blocks (custom content)",
    option_d: "All have equal granularity",
    correct_answer: "B",
    explanation: "Character-based citations for plain text are the most granular, pinpointing exact character ranges. Page-based citations are less granular, and block-based granularity depends on block size.",
    difficulty: "hard"
  },

  // Document metadata and context field (15 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What is the purpose of document metadata in Citations?",
    option_a: "To reduce document size",
    option_b: "To help understand document provenance",
    option_c: "To improve processing speed",
    option_d: "To encrypt document content",
    correct_answer: "B",
    explanation: "Document metadata, especially titles, helps Claude and users understand document provenance, making it clear which document a citation refers to when multiple documents are provided.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What is the context field used for?",
    option_a: "Primary content that will be cited",
    option_b: "Additional information that won't be cited",
    option_c: "System instructions",
    option_d: "Error handling",
    correct_answer: "B",
    explanation: "The context field provides additional information that Claude can use for understanding but won't be cited as a source. This is useful for background info that shouldn't appear in citations.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Should document titles be descriptive and unique?",
    option_a: "No, titles don't matter",
    option_b: "Yes, they help identify sources in citations",
    option_c: "Only for PDFs",
    option_d: "Only for Enterprise accounts",
    correct_answer: "B",
    explanation: "Descriptive, unique titles help identify which document is being cited, especially when multiple documents are provided. They improve clarity for both Claude and end users.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What should go in the context field vs the main document content?",
    option_a: "Everything should be in main content",
    option_b: "Citable facts in content; background information in context field",
    option_c: "Everything should be in context field",
    option_d: "It doesn't matter",
    correct_answer: "B",
    explanation: "Put citable facts and primary source material in the main document content, and use the context field for background information, clarifications, or metadata that shouldn't be cited.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "You have API documentation and internal notes about implementation. How should you structure this?",
    option_a: "Put everything in main content",
    option_b: "API documentation in content, internal notes in context field",
    option_c: "Everything in context field",
    option_d: "Keep them in separate requests",
    correct_answer: "B",
    explanation: "Put the official API documentation in the main content (so it can be cited), and internal implementation notes in the context field (to inform understanding without being cited as official sources).",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can Claude use information from the context field in its responses?",
    option_a: "No, context field is ignored",
    option_b: "Yes, but it won't be cited as a source",
    option_c: "Only for Enterprise accounts",
    option_d: "Only if explicitly referenced",
    correct_answer: "B",
    explanation: "Claude can use information from the context field to inform its understanding and responses, but this information won't appear in citations, maintaining a distinction between official sources and supporting context.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What metadata fields are most important for Citations?",
    option_a: "File size and creation date",
    option_b: "Title and document type",
    option_c: "Author and version",
    option_d: "All metadata is equally important",
    correct_answer: "B",
    explanation: "Title and document type are the most important metadata for Citations, as they help identify and reference the correct source. Other metadata can be useful but is less critical.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Should you include document version information in metadata?",
    option_a: "No, versions are tracked automatically",
    option_b: "Yes, especially for documents that change over time",
    option_c: "Only for Enterprise accounts",
    option_d: "Only for PDFs",
    correct_answer: "B",
    explanation: "Include version information in metadata for documents that change over time. This ensures citations reference the correct version and users can verify against the right source.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How does the context field affect token costs?",
    option_a: "Context field tokens are free",
    option_b: "Context field tokens are counted like regular content",
    option_c: "Context field tokens cost double",
    option_d: "Context field tokens are discounted 50%",
    correct_answer: "B",
    explanation: "Context field tokens are counted and billed like regular input content. The distinction is about citation behavior, not cost.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "You provide 10 documents without titles. How does Claude reference them in citations?",
    option_a: "Claude generates default titles",
    option_b: "Citations may be less clear, using generic identifiers",
    option_c: "Citations fail without titles",
    option_d: "Claude uses file paths as titles",
    correct_answer: "B",
    explanation: "Without titles, citations may use generic identifiers (like 'Document 1', 'Document 2'), making them less clear and harder to interpret, especially when reviewing citations.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's a best practice for structuring metadata in multi-document requests?",
    option_a: "Use identical metadata for all documents",
    option_b: "Use descriptive, unique metadata for each document",
    option_c: "Omit metadata to save tokens",
    option_d: "Only provide metadata for the largest document",
    correct_answer: "B",
    explanation: "Use descriptive, unique metadata for each document to clearly distinguish sources in citations. This is especially important when providing multiple similar documents.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can the context field contain structured data like JSON?",
    option_a: "No, only plain text",
    option_b: "Yes, any format the main content supports",
    option_c: "Only for Enterprise accounts",
    option_d: "Only if it's under 1K tokens",
    correct_answer: "B",
    explanation: "The context field can contain any format that main content supports, including structured data like JSON. The only difference is that it won't be cited.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How does document metadata help with debugging citation issues?",
    option_a: "It doesn't help with debugging",
    option_b: "It makes it easier to identify which document has problems",
    option_c: "It automatically fixes citation errors",
    option_d: "It only helps in development mode",
    correct_answer: "B",
    explanation: "Good metadata (especially descriptive titles) makes it easier to identify which document has citation issues when debugging, improving development and troubleshooting workflows.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's the maximum recommended size for the context field?",
    option_a: "1K tokens",
    option_b: "Limited only by total context window",
    option_c: "10K tokens",
    option_d: "Context field is not recommended",
    correct_answer: "B",
    explanation: "The context field is limited only by the total context window, just like main content. However, use it judiciously since it still consumes tokens while not being citable.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Should you use the context field for system instructions?",
    option_a: "Yes, always put system instructions there",
    option_b: "No, use the system parameter for instructions",
    option_c: "Only for short instructions",
    option_d: "Only with Citations enabled",
    correct_answer: "B",
    explanation: "System instructions should use the dedicated system parameter, not the context field. The context field is for supporting information related to documents, not behavioral instructions.",
    difficulty: "easy"
  },

  // Source provenance tracking (15 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What is source provenance?",
    option_a: "The location where documents are stored",
    option_b: "The origin and history of information sources",
    option_c: "The file format of documents",
    option_d: "The cost of processing documents",
    correct_answer: "B",
    explanation: "Source provenance refers to the origin and history of information sources, allowing you to trace where specific information came from and verify its authenticity.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Why is provenance tracking important in enterprise applications?",
    option_a: "To reduce API costs",
    option_b: "For compliance, auditing, and verification",
    option_c: "To improve response speed",
    option_d: "To increase context window size",
    correct_answer: "B",
    explanation: "Provenance tracking is crucial for compliance, auditing, and verification requirements. It allows organizations to prove that information came from approved, authoritative sources.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How do Citations support provenance tracking?",
    option_a: "By storing documents permanently",
    option_b: "By providing traceable references to specific source locations",
    option_c: "By encrypting source information",
    option_d: "By generating unique document IDs",
    correct_answer: "B",
    explanation: "Citations support provenance tracking by providing traceable references to specific locations in source documents, allowing verification of where each piece of information originated.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What information should you log to maintain full provenance tracking?",
    option_a: "Only the final response",
    option_b: "Request, response, citations, and document metadata",
    option_c: "Only error messages",
    option_d: "Only document titles",
    correct_answer: "B",
    explanation: "For full provenance tracking, log the complete request (including documents), response, citation data, and document metadata. This creates an auditable trail of information flow.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your healthcare application must prove all diagnoses come from medical literature. How do Citations help?",
    option_a: "Citations automatically validate medical accuracy",
    option_b: "Citations provide verifiable references to specific literature sources",
    option_c: "Citations replace the need for medical review",
    option_d: "Citations encrypt sensitive information",
    correct_answer: "B",
    explanation: "Citations provide verifiable references to specific locations in medical literature, allowing medical professionals to verify that information came from authoritative sources and wasn't hallucinated.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can you track provenance across multiple API calls in a conversation?",
    option_a: "No, provenance resets each call",
    option_b: "Yes, by maintaining citation logs client-side",
    option_c: "Yes, Claude tracks it automatically",
    option_d: "Only for Enterprise accounts",
    correct_answer: "B",
    explanation: "Track provenance across calls by maintaining citation logs client-side, associating each piece of information with its source across the conversation history.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's a challenge with provenance tracking in long workflows?",
    option_a: "Citations become inaccurate over time",
    option_b: "Managing references as context editing removes old tool results",
    option_c: "Provenance can't be tracked in workflows",
    option_d: "Citations are disabled after 10 turns",
    correct_answer: "B",
    explanation: "In long workflows, context editing may remove old tool results, making it challenging to maintain complete provenance. Store full citation history client-side if complete trails are required.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How should you handle provenance when documents are updated?",
    option_a: "Citations automatically track versions",
    option_b: "Include version information in document metadata",
    option_c: "Provenance doesn't apply to updated documents",
    option_d: "Previous citations remain valid automatically",
    correct_answer: "B",
    explanation: "Include version information in document metadata so citations reference specific versions. This ensures provenance remains accurate even as documents are updated.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's the benefit of traceable provenance for legal applications?",
    option_a: "Lower API costs",
    option_b: "Ability to verify information meets evidentiary standards",
    option_c: "Faster legal research",
    option_d: "Automatic legal compliance",
    correct_answer: "B",
    explanation: "Traceable provenance allows legal teams to verify that information meets evidentiary standards by confirming it came from authoritative legal sources and can be independently verified.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How can you display provenance information to end users?",
    option_a: "Don't show it; keep it internal",
    option_b: "Show citation data with links to original sources",
    option_c: "Only show it to administrators",
    option_d: "Provenance is automatic and invisible",
    correct_answer: "B",
    explanation: "Display provenance by showing citation data with links or references to original sources, allowing users to verify information themselves and building trust in the system.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's a best practice for provenance in multi-source responses?",
    option_a: "Only cite the primary source",
    option_b: "Cite all relevant sources for each claim",
    option_c: "Avoid multi-source responses",
    option_d: "Combine sources into one citation",
    correct_answer: "B",
    explanation: "Cite all relevant sources for each claim in multi-source responses. This provides complete provenance and allows users to cross-reference information across sources.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How does provenance tracking help detect hallucinations?",
    option_a: "It prevents hallucinations completely",
    option_b: "Lack of citations indicates potentially unsupported information",
    option_c: "It has no effect on hallucinations",
    option_d: "It only helps with numerical hallucinations",
    correct_answer: "B",
    explanation: "If Claude makes a claim without citations when using document grounding, it may indicate unsupported information or hallucination, as grounded responses should be traceable to sources.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Should you maintain provenance logs separately from application logs?",
    option_a: "No, they should be combined",
    option_b: "Yes, for specialized auditing and compliance requirements",
    option_c: "Only for Enterprise accounts",
    option_d: "Provenance logs aren't necessary",
    correct_answer: "B",
    explanation: "Maintain separate provenance logs for specialized auditing and compliance requirements. This allows focused analysis of information flow without sifting through general application logs.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How long should provenance records be retained?",
    option_a: "24 hours",
    option_b: "Based on industry regulations and compliance requirements",
    option_c: "1 week",
    option_d: "Indefinitely",
    correct_answer: "B",
    explanation: "Retention periods should be based on industry regulations and compliance requirements. Healthcare, legal, and financial sectors often have specific retention requirements (e.g., 7 years).",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's a key difference between Citations and custom provenance implementations?",
    option_a: "Custom implementations are always better",
    option_b: "Citations provide 15% better recall with less implementation effort",
    option_c: "Citations only work for PDFs",
    option_d: "No significant difference",
    correct_answer: "B",
    explanation: "Citations provide approximately 15% better recall accuracy with significantly less implementation effort compared to custom provenance systems, making it more effective and efficient.",
    difficulty: "medium"
  },

  // Citations vs structured outputs (10 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can Citations be used with strict JSON schema mode?",
    option_a: "Yes, they work together",
    option_b: "No, they conflict and cause a 400 error",
    option_c: "Yes, but only for Enterprise accounts",
    option_d: "Yes, with special configuration",
    correct_answer: "B",
    explanation: "Citations cannot be used with strict JSON schema mode; attempting to use both results in a 400 error. You must choose one approach or the other.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Why do Citations conflict with strict JSON schema?",
    option_a: "It's a temporary bug",
    option_b: "Citation metadata doesn't fit strict schema constraints",
    option_c: "JSON mode disables all features",
    option_d: "They use incompatible encoding",
    correct_answer: "B",
    explanation: "Citations add metadata and structured references that don't fit within strict JSON schema constraints, which require exact adherence to predefined schemas.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your application needs both structured JSON output and source citations. What's the best approach?",
    option_a: "Use Citations and accept non-strict JSON",
    option_b: "Use non-strict JSON mode with citation prompting",
    option_c: "Alternate between modes per request",
    option_d: "Use Enterprise mode that supports both",
    correct_answer: "B",
    explanation: "Use non-strict JSON mode (requesting JSON in the prompt) combined with citation prompting. This allows flexibility for both structured output and citation metadata without strict schema constraints.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can you request JSON output with Citations enabled?",
    option_a: "No, absolutely incompatible",
    option_b: "Yes, by requesting JSON in prompt (non-strict mode)",
    option_c: "Only for simple JSON structures",
    option_d: "Only for Enterprise accounts",
    correct_answer: "B",
    explanation: "You can request JSON output with Citations by asking for JSON in your prompt (non-strict mode) rather than using strict JSON schema. The output will include both JSON content and citation metadata.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's the trade-off between strict JSON schema and Citations?",
    option_a: "No trade-off; one is strictly better",
    option_b: "Strict schemas ensure format; Citations ensure provenance",
    option_c: "Only cost differences",
    option_d: "Only performance differences",
    correct_answer: "B",
    explanation: "Strict JSON schemas ensure exact output format for parsing, while Citations ensure source provenance and verifiability. Choose based on whether format guarantees or source tracking is more critical.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "When should you prioritize Citations over strict JSON schema?",
    option_a: "When parsing reliability is most important",
    option_b: "When source verification and compliance are critical",
    option_c: "When you need fastest responses",
    option_d: "Never; always use JSON schema",
    correct_answer: "B",
    explanation: "Prioritize Citations when source verification, compliance, and auditability are critical (e.g., legal, medical, financial applications), even if it means less strict output formatting.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How do citations appear when using non-strict JSON mode?",
    option_a: "Embedded within the JSON structure",
    option_b: "As separate metadata alongside JSON content",
    option_c: "They don't appear; incompatible",
    option_d: "As JSON comments",
    correct_answer: "B",
    explanation: "When using non-strict JSON mode with Citations, citation metadata appears separately from the JSON content in the response structure, maintaining both structured output and source references.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can you validate Citations output with a schema?",
    option_a: "No, Citations are unstructured",
    option_b: "Yes, citation metadata has a consistent structure",
    option_c: "Only for Enterprise accounts",
    option_d: "Only for PDF citations",
    correct_answer: "B",
    explanation: "Citation metadata has a consistent, documented structure that you can validate with a schema, even though it's separate from strict JSON schema mode for content.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's a workaround for applications that need both strict formatting and citations?",
    option_a: "There is no workaround",
    option_b: "Make two API calls: one for Citations, one for structured output",
    option_c: "Use Enterprise-only dual mode",
    option_d: "Use XML instead of JSON",
    correct_answer: "B",
    explanation: "A workaround is making two API calls: one with Citations for source-backed content, and another with strict JSON schema for formatted output based on the cited content.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How should API error handling differ when using Citations vs strict JSON?",
    option_a: "No difference",
    option_b: "Citations mode should handle citation-specific errors",
    option_c: "JSON mode requires more error handling",
    option_d: "Error handling is identical",
    correct_answer: "B",
    explanation: "With Citations, handle citation-specific scenarios like missing citations or citation parsing errors in addition to standard API errors, whereas strict JSON mode focuses on schema validation errors.",
    difficulty: "medium"
  },

  // Best practices and accuracy (10 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's the primary advantage of using Citations over prompt-based citation requests?",
    option_a: "Lower cost",
    option_b: "15% better recall accuracy and structured format",
    option_c: "Faster responses",
    option_d: "Larger context windows",
    correct_answer: "B",
    explanation: "Citations provide 15% better recall accuracy compared to prompt-based approaches, plus structured, machine-readable citation formats that are easier to parse and validate.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How should you structure documents for optimal citation accuracy?",
    option_a: "Merge all documents into one large document",
    option_b: "Keep documents well-formatted with clear structure",
    option_c: "Convert everything to plain text",
    option_d: "Split documents into 1K token chunks",
    correct_answer: "B",
    explanation: "Keep documents well-formatted with clear structure (headings, sections, proper formatting). This helps Citations accurately identify and reference specific content locations.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's a best practice for handling multiple documents with Citations?",
    option_a: "Provide unique, descriptive metadata for each",
    option_b: "Use identical metadata to simplify processing",
    option_c: "Omit metadata to save tokens",
    option_d: "Only provide the largest document",
    correct_answer: "A",
    explanation: "Provide unique, descriptive metadata (especially titles) for each document so citations clearly indicate which source is being referenced, avoiding confusion.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How can you validate citation accuracy in your application?",
    option_a: "Trust Citations completely without validation",
    option_b: "Implement spot-checking and human review processes",
    option_c: "Citations don't need validation",
    option_d: "Only validate on Enterprise accounts",
    correct_answer: "B",
    explanation: "Implement spot-checking and human review processes to validate citation accuracy, especially during initial deployment. While Citations are highly accurate, validation ensures they meet your quality standards.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What should you do if citations seem inaccurate or missing?",
    option_a: "Assume it's a model error",
    option_b: "Check document formatting and structure first",
    option_c: "Immediately switch to custom implementation",
    option_d: "Disable Citations",
    correct_answer: "B",
    explanation: "First check document formatting and structure. Poor formatting, scanned PDFs without OCR, or complex layouts can affect citation accuracy. Fix document quality before assuming model issues.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How should you prompt Claude when using Citations?",
    option_a: "Explicitly request citations in every prompt",
    option_b: "Citations work automatically; prompt for your actual task",
    option_c: "Avoid mentioning sources in prompts",
    option_d: "Use special citation prompts",
    correct_answer: "B",
    explanation: "When Citations are enabled, they work automatically. Prompt for your actual task (e.g., 'Analyze this document') without needing explicit citation requests. The feature handles attribution automatically.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's the relationship between document quality and citation accuracy?",
    option_a: "No relationship",
    option_b: "Higher quality documents enable more accurate citations",
    option_c: "Lower quality documents work better",
    option_d: "Quality only affects speed",
    correct_answer: "B",
    explanation: "Higher quality documents (clear formatting, extractable text, logical structure) enable more accurate citations by making it easier to identify and reference specific content locations.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Should you pre-process documents before providing them for Citations?",
    option_a: "No, always provide raw documents",
    option_b: "Yes, if needed to improve structure or text extraction",
    option_c: "Only for PDFs",
    option_d: "Only for documents over 50K tokens",
    correct_answer: "B",
    explanation: "Pre-process documents if needed to improve structure or text extraction (e.g., OCR for scanned PDFs, cleaning up formatting), but avoid unnecessary modifications that might introduce errors.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "How can you measure citation accuracy in production?",
    option_a: "It can't be measured",
    option_b: "Sample responses and manually verify citations match sources",
    option_c: "Only available in Enterprise dashboards",
    option_d: "Accuracy is guaranteed at 100%",
    correct_answer: "B",
    explanation: "Measure accuracy by sampling responses and manually verifying that citations correctly match the claimed source locations. Track accuracy over time to identify patterns or issues.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "What's a best practice for presenting citations to end users?",
    option_a: "Hide citations from users",
    option_b: "Make citations clickable/navigable with user-friendly formatting",
    option_c: "Show raw API citation data",
    option_d: "Only show citations on request",
    correct_answer: "B",
    explanation: "Present citations in user-friendly formats: clickable page numbers, highlighted text ranges, or expandable source previews. Make verification easy and intuitive for end users.",
    difficulty: "easy"
  }
];
