export interface Question {
  week?: number;
  domain: string;
  topic: string;
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_answer: string;
  explanation: string;
  difficulty?: string;
}

export const topic9Questions: Question[] = [
  // Context window sizes and limits (15 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is the standard context window size for Claude models?",
    option_a: "100K tokens",
    option_b: "200K tokens",
    option_c: "500K tokens",
    option_d: "1M tokens",
    correct_answer: "B",
    explanation: "The standard context window for Claude models is 200K tokens. Enterprise users have access to 500K tokens, and Opus 4.6+ and Sonnet 4.6 support up to 1M tokens.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Which Claude models support a 1M token context window?",
    option_a: "All Claude models",
    option_b: "Enterprise models only",
    option_c: "Opus 4.6+ and Sonnet 4.6",
    option_d: "Haiku 3.5 only",
    correct_answer: "C",
    explanation: "Opus 4.6 and later versions, as well as Sonnet 4.6, support a 1M token context window. This is the largest available context window for Claude models.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What context window size is available to Enterprise users?",
    option_a: "200K tokens",
    option_b: "500K tokens",
    option_c: "1M tokens",
    option_d: "2M tokens",
    correct_answer: "B",
    explanation: "Enterprise users have access to a 500K token context window, which is larger than the standard 200K but smaller than the 1M available in the newest models.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "A developer is building a document analysis system that needs to process 600K tokens. Which approach is most appropriate?",
    option_a: "Use the standard Claude model and split the document",
    option_b: "Use Opus 4.6+ or Sonnet 4.6 with 1M context window",
    option_c: "Request Enterprise access for 500K window",
    option_d: "Use prompt caching to extend the window",
    correct_answer: "B",
    explanation: "Since the document is 600K tokens, it exceeds both the standard 200K and Enterprise 500K limits. Only Opus 4.6+ or Sonnet 4.6 with 1M context windows can handle this in a single request. Prompt caching doesn't extend the context window size.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What happens when you approach the context window limit in Claude?",
    option_a: "The API returns a 400 error immediately",
    option_b: "Server-side compaction automatically summarizes content",
    option_c: "The oldest messages are silently dropped",
    option_d: "The request is queued until space is available",
    correct_answer: "B",
    explanation: "When approaching the context window limit, Claude uses server-side compaction to automatically summarize content, allowing the conversation to continue without hitting hard limits.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your application is experiencing context window limit errors with a standard Claude model. What is the most cost-effective solution?",
    option_a: "Upgrade to Opus 4.6 immediately",
    option_b: "Implement client-side summarization of older messages",
    option_c: "Rely on server-side compaction",
    option_d: "Switch to Enterprise with 500K window",
    correct_answer: "C",
    explanation: "The most cost-effective solution is to rely on server-side compaction, which automatically handles summarization when approaching limits. This avoids the cost of upgrading models or Enterprise plans and is simpler than implementing client-side summarization.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Which statement about context window limits across Claude models is correct?",
    option_a: "All Claude 3 models have the same context window",
    option_b: "Context windows decrease with newer model versions",
    option_c: "Context windows vary by model and pricing tier",
    option_d: "Context windows are fixed at 200K for all models",
    correct_answer: "C",
    explanation: "Context windows vary significantly: standard models have 200K, Enterprise has 500K, and Opus 4.6+/Sonnet 4.6 have 1M tokens. The window size depends on both model version and pricing tier.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "A customer chat application maintains conversation history. With a 200K context window, what is the approximate maximum conversation length assuming 500 tokens per exchange?",
    option_a: "100 exchanges",
    option_b: "200 exchanges",
    option_c: "400 exchanges",
    option_d: "Unlimited with server-side compaction",
    correct_answer: "C",
    explanation: "With 200K tokens and 500 tokens per exchange, you can fit approximately 400 exchanges (200,000 / 500 = 400). While server-side compaction helps, it's not truly unlimited and still has practical limits.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is the primary advantage of the 1M token context window in Opus 4.6+?",
    option_a: "Faster response times",
    option_b: "Lower cost per token",
    option_c: "Ability to process larger documents in single requests",
    option_d: "Better model accuracy",
    correct_answer: "C",
    explanation: "The primary advantage of the 1M token context window is the ability to process much larger documents, codebases, or conversation histories in a single request without splitting or summarization.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does context window size affect token costs?",
    option_a: "Larger windows cost less per token",
    option_b: "Context window size doesn't affect token pricing",
    option_c: "You're charged based on window size, not usage",
    option_d: "Larger windows may be available on more expensive models",
    correct_answer: "D",
    explanation: "Context window size itself doesn't change per-token pricing, but larger windows (like 1M) are available on newer, potentially more expensive models like Opus 4.6+. You're always charged for actual tokens used, not window size.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "When should you consider upgrading from a 200K to 500K context window?",
    option_a: "When you need faster responses",
    option_b: "When you regularly hit context limits with compaction",
    option_c: "When you want better model quality",
    option_d: "When you need to reduce costs",
    correct_answer: "B",
    explanation: "You should consider upgrading to a larger context window when you regularly hit context limits even with server-side compaction, indicating your use case genuinely needs more context capacity.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is NOT a benefit of larger context windows?",
    option_a: "Processing entire books in one request",
    option_b: "Maintaining longer conversation histories",
    option_c: "Faster model inference",
    option_d: "Analyzing large codebases without splitting",
    correct_answer: "C",
    explanation: "Larger context windows do not provide faster model inference. In fact, processing more tokens can take longer. The benefits are about capacity (processing more content) not speed.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "You're building a legal document analysis tool that processes contracts averaging 800K tokens. What is the minimum required context window?",
    option_a: "200K (standard)",
    option_b: "500K (Enterprise)",
    option_c: "1M (Opus 4.6+ or Sonnet 4.6)",
    option_d: "Not possible, must split documents",
    correct_answer: "C",
    explanation: "For 800K token documents, you need the 1M context window available in Opus 4.6+ or Sonnet 4.6. The 500K Enterprise window would be insufficient.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How should you architect a system that processes documents of varying sizes (50K to 900K tokens)?",
    option_a: "Always use Opus 4.6 with 1M window",
    option_b: "Route to different models based on document size",
    option_c: "Split all documents to fit 200K window",
    option_d: "Use Enterprise 500K for everything",
    correct_answer: "B",
    explanation: "The optimal approach is to route requests to different models based on document size: use standard models for smaller documents and Opus 4.6+/Sonnet 4.6 only for documents exceeding 500K tokens. This optimizes cost and performance.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is a common misconception about context windows?",
    option_a: "Larger windows always produce better outputs",
    option_b: "Context windows are measured in tokens",
    option_c: "Different models have different window sizes",
    option_d: "Windows can be exceeded with compaction",
    correct_answer: "A",
    explanation: "A common misconception is that larger context windows always produce better outputs. In reality, model quality depends on the model itself, not just context window size. Larger windows provide capacity, not necessarily better reasoning.",
    difficulty: "medium"
  },

  // Server-side compaction (15 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is server-side compaction in Claude?",
    option_a: "Manual compression of user messages",
    option_b: "Automatic summarization when approaching context limits",
    option_c: "Client-side reduction of message history",
    option_d: "Token-level compression algorithm",
    correct_answer: "B",
    explanation: "Server-side compaction is Claude's automatic summarization mechanism that activates when approaching the context window limit, allowing conversations to continue without manual intervention.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "When does server-side compaction trigger?",
    option_a: "After every 10 messages",
    option_b: "When explicitly requested by the client",
    option_c: "When approaching the context window limit",
    option_d: "At the start of every conversation",
    correct_answer: "C",
    explanation: "Server-side compaction triggers automatically when the conversation is approaching the context window limit, not at fixed intervals or on demand.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What content does server-side compaction prioritize for summarization?",
    option_a: "Most recent messages",
    option_b: "System prompts",
    option_c: "Older conversation history",
    option_d: "Tool use results",
    correct_answer: "C",
    explanation: "Server-side compaction prioritizes older conversation history for summarization, preserving more recent context which is typically more relevant to the current interaction.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your chatbot conversation has grown to 180K tokens. What should you do?",
    option_a: "Manually summarize and restart the conversation",
    option_b: "Delete the oldest messages before making the next request",
    option_c: "Let server-side compaction handle it automatically",
    option_d: "Switch to a model with a larger context window",
    correct_answer: "C",
    explanation: "At 180K tokens with a 200K window, you're approaching the limit but server-side compaction will handle this automatically. There's no need for manual intervention at this stage.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is a limitation of server-side compaction?",
    option_a: "It requires explicit API parameters",
    option_b: "Summarization may lose some nuanced details",
    option_c: "It only works with Enterprise accounts",
    option_d: "It increases response latency by 50%",
    correct_answer: "B",
    explanation: "While server-side compaction is automatic and helpful, summarization inherently may lose some nuanced details from the original conversation. This is a trade-off for maintaining conversation continuity.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does server-side compaction affect conversation quality?",
    option_a: "It always degrades quality significantly",
    option_b: "It maintains recent context while compressing older content",
    option_c: "It has no effect on quality",
    option_d: "It improves quality by removing redundant information",
    correct_answer: "B",
    explanation: "Server-side compaction is designed to maintain conversation quality by keeping recent context intact while compressing older content. This minimizes quality impact while managing context limits.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Can you disable server-side compaction?",
    option_a: "Yes, via an API parameter",
    option_b: "Yes, but only for Enterprise accounts",
    option_c: "No, it's automatic and cannot be disabled",
    option_d: "Yes, by using a larger context window",
    correct_answer: "C",
    explanation: "Server-side compaction is an automatic feature that cannot be disabled. It's part of Claude's built-in context management system to ensure conversations can continue smoothly.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your application needs to maintain exact conversation history for legal compliance. How should you handle server-side compaction?",
    option_a: "Disable compaction via API settings",
    option_b: "Store full conversation history client-side separately",
    option_c: "Use only models with 1M context windows",
    option_d: "Request Enterprise exemption from compaction",
    correct_answer: "B",
    explanation: "Since server-side compaction cannot be disabled, applications requiring exact conversation history must store it client-side separately. The compacted version in Claude is for operational purposes, not legal records.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is the relationship between prompt caching and server-side compaction?",
    option_a: "They are mutually exclusive features",
    option_b: "Cached content is never compacted",
    option_c: "They work independently for different purposes",
    option_d: "Caching prevents compaction from triggering",
    correct_answer: "C",
    explanation: "Prompt caching and server-side compaction work independently. Caching reduces costs for repeated content, while compaction manages context limits. They serve different purposes and don't interfere with each other.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How transparent is server-side compaction to API users?",
    option_a: "Completely transparent; you're notified of each compaction",
    option_b: "Mostly transparent; happens automatically without notification",
    option_c: "Not transparent; you must monitor token counts",
    option_d: "Transparent only for Enterprise users",
    correct_answer: "B",
    explanation: "Server-side compaction is mostly transparent to users, happening automatically in the background without explicit notifications. The conversation continues smoothly from the user's perspective.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "A customer reports that Claude seems to have 'forgotten' details from early in a long conversation. What's the most likely cause?",
    option_a: "A bug in the API",
    option_b: "Server-side compaction summarized early messages",
    option_c: "The model has a memory limit separate from context window",
    option_d: "Client-side message truncation",
    correct_answer: "B",
    explanation: "In long conversations, server-side compaction summarizes older messages when approaching context limits. This can make it seem like Claude 'forgot' specific details that were compressed in the summarization process.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the best practice when you need fine-grained control over what gets summarized?",
    option_a: "Configure compaction rules via API parameters",
    option_b: "Implement client-side message management",
    option_c: "Use Enterprise compaction controls",
    option_d: "Disable compaction and manage context manually",
    correct_answer: "B",
    explanation: "Since server-side compaction is automatic and non-configurable, applications needing fine-grained control should implement client-side message management, deciding what to keep, summarize, or remove before sending to the API.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does server-side compaction interact with system prompts?",
    option_a: "System prompts are compacted first",
    option_b: "System prompts are typically preserved",
    option_c: "System prompts must be resent after compaction",
    option_d: "System prompts are cached separately",
    correct_answer: "B",
    explanation: "Server-side compaction typically preserves system prompts as they define the assistant's behavior and role. The compaction focuses on conversation history rather than foundational instructions.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What happens to token counts after server-side compaction occurs?",
    option_a: "They reset to zero",
    option_b: "They decrease as content is summarized",
    option_c: "They remain unchanged",
    option_d: "They increase due to summarization overhead",
    correct_answer: "B",
    explanation: "After server-side compaction, token counts decrease because content has been summarized into a more compact form. This creates room for the conversation to continue within the context window.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "In what scenario would server-side compaction be insufficient?",
    option_a: "When you need to reference specific quotes from 100 messages ago",
    option_b: "When having a casual conversation",
    option_c: "When using multi-turn dialogue",
    option_d: "When the context window is 500K or larger",
    correct_answer: "A",
    explanation: "Server-side compaction would be insufficient when you need to reference specific quotes or exact details from much earlier in the conversation, as summarization loses verbatim content. In such cases, client-side storage or larger context windows are better.",
    difficulty: "hard"
  },

  // Automatic context management (10 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is automatic context management in Claude?",
    option_a: "Manual tracking of conversation tokens",
    option_b: "Built-in handling of context for code execution users",
    option_c: "Third-party context optimization service",
    option_d: "Client-side context compression",
    correct_answer: "B",
    explanation: "Automatic context management is a built-in feature for code execution users that handles context automatically, reducing the need for manual context tracking and management.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Who benefits most from automatic context management?",
    option_a: "All API users equally",
    option_b: "Code execution users",
    option_c: "Enterprise customers only",
    option_d: "Users with 1M context windows",
    correct_answer: "B",
    explanation: "Automatic context management is specifically designed for code execution users, providing automatic handling of context without manual intervention.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What does automatic context management handle?",
    option_a: "Only system messages",
    option_b: "Context tracking and optimization automatically",
    option_c: "Only tool use results",
    option_d: "Manual prompt engineering",
    correct_answer: "B",
    explanation: "Automatic context management handles context tracking and optimization automatically, removing the burden of manual context management from developers.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does automatic context management differ from server-side compaction?",
    option_a: "They are the same feature",
    option_b: "Automatic management is for code execution; compaction is universal",
    option_c: "Compaction is manual; automatic management is not",
    option_d: "Automatic management only works with caching",
    correct_answer: "B",
    explanation: "Automatic context management is specifically for code execution users and provides comprehensive context handling, while server-side compaction is a universal feature that summarizes content when approaching limits.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is a key benefit of automatic context management for developers?",
    option_a: "Lower API costs",
    option_b: "Faster response times",
    option_c: "Reduced complexity in application code",
    option_d: "Unlimited context windows",
    correct_answer: "C",
    explanation: "The key benefit of automatic context management is reduced complexity in application code, as developers don't need to implement their own context tracking and optimization logic.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Can you override automatic context management with manual controls?",
    option_a: "Yes, it's fully configurable",
    option_b: "No, it's always automatic for code execution users",
    option_c: "Yes, but only for Enterprise accounts",
    option_d: "No, but you can disable it entirely",
    correct_answer: "B",
    explanation: "Automatic context management is designed to be automatic for code execution users. The system handles it without configuration or override options, simplifying the developer experience.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your application uses Claude for code execution and you're concerned about context limits. What should you do?",
    option_a: "Implement custom context management",
    option_b: "Rely on automatic context management",
    option_c: "Manually track all token counts",
    option_d: "Upgrade to Enterprise immediately",
    correct_answer: "B",
    explanation: "For code execution users, relying on automatic context management is the recommended approach. It's designed to handle these concerns without custom implementation.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is NOT a feature of automatic context management?",
    option_a: "Automatic context optimization",
    option_b: "Built-in for code execution users",
    option_c: "Manual configuration of retention policies",
    option_d: "Simplified developer experience",
    correct_answer: "C",
    explanation: "Automatic context management does not offer manual configuration of retention policies. It's designed to work automatically without developer configuration.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does automatic context management affect application architecture?",
    option_a: "Requires significant architectural changes",
    option_b: "Simplifies architecture by removing context management code",
    option_c: "Has no effect on architecture",
    option_d: "Requires dedicated context management services",
    correct_answer: "B",
    explanation: "Automatic context management simplifies application architecture by removing the need for custom context management code, tracking systems, and optimization logic.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "When would you need to implement custom context management despite automatic context management being available?",
    option_a: "When using code execution features",
    option_b: "When you need non-code-execution use cases with specific context rules",
    option_c: "When using standard API calls",
    option_d: "Never; automatic management handles all cases",
    correct_answer: "B",
    explanation: "You'd need custom context management when your use case isn't code execution or has specific context requirements that automatic management doesn't address. Automatic management is specifically for code execution users.",
    difficulty: "hard"
  },

  // Prompt caching strategies (20 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is the primary purpose of prompt caching in Claude?",
    option_a: "To increase context window size",
    option_b: "To reduce costs for repeated content",
    option_c: "To improve response accuracy",
    option_d: "To enable faster model training",
    correct_answer: "B",
    explanation: "Prompt caching reduces costs by avoiding reprocessing of repeated content across requests. You pay a reduced rate for cached tokens compared to processing them fresh each time.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How do you enable prompt caching in the API?",
    option_a: "Set enable_caching: true parameter",
    option_b: "Use the cache_control field",
    option_c: "It's automatically enabled for all requests",
    option_d: "Requires Enterprise account activation",
    correct_answer: "B",
    explanation: "Prompt caching is enabled by using the cache_control field in your API request to mark content that should be cached. This gives you explicit control over what gets cached.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What type of content is ideal for prompt caching?",
    option_a: "Frequently changing user queries",
    option_b: "Stable content like system instructions and background info",
    option_c: "Short, single-use messages",
    option_d: "Real-time data feeds",
    correct_answer: "B",
    explanation: "Ideal content for caching is stable and reused across requests, such as system instructions, background information, large contexts, and tool definitions. Frequently changing content defeats the purpose of caching.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Where should cached content be placed in the prompt?",
    option_a: "At the end of the prompt",
    option_b: "In the middle of the prompt",
    option_c: "At the beginning of the prompt",
    option_d: "Placement doesn't matter",
    correct_answer: "C",
    explanation: "Cached content should be placed at the beginning of the prompt. This allows Claude to process and cache it efficiently before encountering new, variable content.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Does prompt caching work automatically for multi-turn conversations?",
    option_a: "No, you must explicitly enable it for each turn",
    option_b: "Yes, it automatically caches context across turns",
    option_c: "Only for Enterprise accounts",
    option_d: "Only for conversations under 50K tokens",
    correct_answer: "B",
    explanation: "Prompt caching works automatically for multi-turn conversations, caching the conversation history across turns without requiring explicit cache_control on every message.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "You have a 50K token system prompt that's identical across all requests. What's the best caching strategy?",
    option_a: "Don't cache; it's too large",
    option_b: "Cache it using cache_control and place at prompt beginning",
    option_c: "Split it into smaller chunks without caching",
    option_d: "Cache it only for Enterprise users",
    correct_answer: "B",
    explanation: "A large, stable system prompt is perfect for caching. Use cache_control to mark it for caching and place it at the beginning of the prompt for optimal efficiency and cost savings.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What happens if you change cached content slightly?",
    option_a: "The cache automatically updates incrementally",
    option_b: "The entire cache is invalidated and must be rebuilt",
    option_c: "Only the changed portion is reprocessed",
    option_d: "The change is ignored to maintain cache",
    correct_answer: "B",
    explanation: "If cached content changes, the entire cache is invalidated and must be rebuilt. This is why caching works best for stable content that rarely changes.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How long does cached content remain available?",
    option_a: "Forever, until explicitly cleared",
    option_b: "24 hours",
    option_c: "5 minutes (exact duration documented in API docs)",
    option_d: "Until server restart",
    correct_answer: "C",
    explanation: "Cached content has a specific time-to-live (TTL), which is documented in the API documentation. After this period, the cache expires and content must be reprocessed.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is a common mistake when implementing prompt caching?",
    option_a: "Caching stable, large content",
    option_b: "Placing cached content at the prompt beginning",
    option_c: "Caching frequently changing content",
    option_d: "Using cache_control field",
    correct_answer: "C",
    explanation: "A common mistake is caching frequently changing content. Since any change invalidates the entire cache, this provides no benefit and adds complexity. Cache only stable content.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your application sends 1000 requests/day with the same 100K token documentation. Estimated cost savings with caching?",
    option_a: "Minimal; caching doesn't affect costs significantly",
    option_b: "Substantial; you pay cache read rates instead of full processing",
    option_c: "None; cached tokens cost the same as regular tokens",
    option_d: "100%; cached tokens are free",
    correct_answer: "B",
    explanation: "With the same 100K token documentation across 1000 requests, caching provides substantial savings. After the first request, subsequent requests pay the reduced cache read rate instead of full processing costs.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Can you cache tool definitions?",
    option_a: "No, tool definitions cannot be cached",
    option_b: "Yes, tool definitions are ideal for caching",
    option_c: "Only function-based tools, not code-based",
    option_d: "Only for Enterprise accounts",
    correct_answer: "B",
    explanation: "Tool definitions are ideal for caching since they're typically stable and reused across many requests. Caching them reduces costs when the same tools are used repeatedly.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the relationship between prompt caching and context window size?",
    option_a: "Caching increases the effective context window",
    option_b: "Caching reduces the available context window",
    option_c: "Cached tokens still count toward the context window limit",
    option_d: "Caching replaces the context window mechanism",
    correct_answer: "C",
    explanation: "Cached tokens still count toward the context window limit. Caching is about cost efficiency, not increasing capacity. It doesn't change how much content you can include in a request.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your system prompt changes weekly. Is prompt caching beneficial?",
    option_a: "No, changes too frequently for cache benefits",
    option_b: "Yes, even weekly changes benefit from caching",
    option_c: "Only if the changes are minor",
    option_d: "Only with automatic cache invalidation",
    correct_answer: "B",
    explanation: "Even with weekly changes, prompt caching is beneficial. You get cost savings for all requests during that week. The cache is only rebuilt once when the prompt changes, then reused until the next change.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What content should NOT be cached?",
    option_a: "System instructions",
    option_b: "Tool definitions",
    option_c: "User-specific queries that change each request",
    option_d: "Large background documentation",
    correct_answer: "C",
    explanation: "User-specific queries that change with each request should not be cached. Caching works best for content that's reused across multiple requests, not unique per-request content.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How do you structure a prompt with both cached and non-cached content?",
    option_a: "Non-cached first, then cached",
    option_b: "Cached first, then non-cached",
    option_c: "Interleaved for best performance",
    option_d: "Separate API calls for each",
    correct_answer: "B",
    explanation: "Structure prompts with cached content first (at the beginning), followed by non-cached, variable content. This allows efficient cache utilization while accommodating request-specific information.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What happens when you use cache_control on content that's not actually reused?",
    option_a: "API returns an error",
    option_b: "You pay cache write costs with no benefits",
    option_c: "The content is automatically uncached",
    option_d: "Performance degrades significantly",
    correct_answer: "B",
    explanation: "If you cache content that's not reused, you pay the cache write cost without getting the benefit of cache reads. This increases costs rather than reducing them. Only cache content that will be reused.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "A chatbot has a 20K token system prompt and 50K token knowledge base, both static. What should be cached?",
    option_a: "Only the system prompt",
    option_b: "Only the knowledge base",
    option_c: "Both system prompt and knowledge base",
    option_d: "Neither; focus on user messages",
    correct_answer: "C",
    explanation: "Both the system prompt and knowledge base should be cached since they're static and reused across all conversations. Place both at the prompt beginning and mark with cache_control for maximum savings.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does prompt caching interact with streaming responses?",
    option_a: "Caching disables streaming",
    option_b: "Streaming disables caching",
    option_c: "They work independently without conflict",
    option_d: "Caching only works with complete responses",
    correct_answer: "C",
    explanation: "Prompt caching and streaming work independently. You can cache input content while still receiving streamed responses. They serve different purposes and don't interfere with each other.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What metrics should you monitor to optimize prompt caching?",
    option_a: "Only total token usage",
    option_b: "Cache hit rate and cost per request",
    option_c: "Only response latency",
    option_d: "Only cache size in bytes",
    correct_answer: "B",
    explanation: "Monitor cache hit rate (how often cached content is reused) and cost per request to optimize caching. These metrics show whether your caching strategy is effective and cost-efficient.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your cached content expires mid-conversation. What happens?",
    option_a: "The conversation immediately fails",
    option_b: "The content is reprocessed and recached transparently",
    option_c: "You must restart the conversation",
    option_d: "The API returns a cache expiration error",
    correct_answer: "B",
    explanation: "If cached content expires mid-conversation, it's transparently reprocessed and recached on the next request. The conversation continues normally, though that request will pay full processing costs to rebuild the cache.",
    difficulty: "hard"
  },

  // Cache placement and optimization (15 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Why should cached content be placed at the beginning of prompts?",
    option_a: "It's a required API constraint",
    option_b: "For efficient processing and cache utilization",
    option_c: "To improve response accuracy",
    option_d: "To reduce latency",
    correct_answer: "B",
    explanation: "Placing cached content at the beginning allows Claude to efficiently process and utilize the cache before encountering new content. This is an optimization best practice, not a hard requirement.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What happens if you place cached content at the end of the prompt?",
    option_a: "API returns an error",
    option_b: "Caching is automatically disabled",
    option_c: "It works but may be less efficient",
    option_d: "No difference from placing it at the beginning",
    correct_answer: "C",
    explanation: "Placing cached content at the end will still work and the content will be cached, but it may be less efficient than placing it at the beginning where it can be processed first.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How should you structure multiple cached sections in a prompt?",
    option_a: "Scatter them throughout the prompt",
    option_b: "Group all cached content together at the beginning",
    option_c: "Alternate cached and non-cached content",
    option_d: "Place the largest cached content last",
    correct_answer: "B",
    explanation: "Group all cached content together at the beginning of the prompt. This creates a clear cached prefix that's efficiently processed before the variable content in each request.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "You have system instructions (10K), tool definitions (30K), and knowledge base (100K) all cacheable. What's the optimal order?",
    option_a: "Order doesn't matter as long as they're at the beginning",
    option_b: "Largest to smallest: knowledge base, tools, system",
    option_c: "Smallest to largest: system, tools, knowledge base",
    option_d: "Tools, system, knowledge base",
    correct_answer: "A",
    explanation: "When all content is cacheable and at the beginning, the specific order among cached sections doesn't significantly impact caching efficiency. What matters is that they're all grouped at the start before non-cached content.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the minimum content size worth caching?",
    option_a: "Any size; even 100 tokens benefit from caching",
    option_b: "At least 1000 tokens for cost-effective caching",
    option_c: "At least 10K tokens minimum",
    option_d: "Only content larger than 50K tokens",
    correct_answer: "B",
    explanation: "While there's no hard minimum, caching becomes cost-effective typically around 1000+ tokens. Very small content may not justify the cache write overhead. The exact threshold depends on reuse frequency.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does cache placement affect latency?",
    option_a: "Beginning placement significantly reduces latency",
    option_b: "Placement has minimal impact on latency",
    option_c: "End placement reduces latency",
    option_d: "Cache placement doubles latency",
    correct_answer: "B",
    explanation: "Cache placement has minimal impact on latency. The main benefit of caching is cost reduction, not latency improvement. Proper placement optimizes processing efficiency but doesn't dramatically change response times.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Should you cache few-shot examples in your system prompt?",
    option_a: "No, examples change too frequently",
    option_b: "Yes, if the examples are stable across requests",
    option_c: "Only for Enterprise accounts",
    option_d: "Only if examples exceed 50K tokens",
    correct_answer: "B",
    explanation: "Cache few-shot examples if they're stable and reused across requests. Like other system prompt content, stable examples are ideal candidates for caching to reduce costs.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your prompt has: system instructions (stable), user context (per-user), and query (per-request). What should be cached?",
    option_a: "All three sections",
    option_b: "Only system instructions",
    option_c: "System instructions and user context",
    option_d: "Nothing; too much variation",
    correct_answer: "B",
    explanation: "Only cache the system instructions, as they're stable across all requests. User context varies per user and query varies per request, so caching them provides no benefit.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How can you optimize cache utilization in a multi-tenant application?",
    option_a: "Use separate caches for each tenant",
    option_b: "Cache only tenant-agnostic content",
    option_c: "Disable caching in multi-tenant scenarios",
    option_d: "Cache everything including tenant data",
    correct_answer: "B",
    explanation: "In multi-tenant applications, cache only tenant-agnostic content like system instructions and tool definitions. Tenant-specific content varies per tenant and won't benefit from caching.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's a sign that your cache placement needs optimization?",
    option_a: "High API costs despite using cache_control",
    option_b: "Slower response times",
    option_c: "More accurate responses",
    option_d: "Longer context windows",
    correct_answer: "A",
    explanation: "If you're using cache_control but still seeing high costs, your cache placement or content selection may need optimization. You might be caching content that's not reused or structured inefficiently.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Should you cache conversation history in a chatbot?",
    option_a: "Yes, always cache all conversation history",
    option_b: "No, conversation history is unique per conversation",
    option_c: "Yes, but only for multi-turn conversations with auto-caching",
    option_d: "Only for the most recent 5 messages",
    correct_answer: "C",
    explanation: "For multi-turn conversations, Claude automatically caches conversation history across turns. You don't need to explicitly cache it. However, the history is unique per conversation, so it's not shared across different users' conversations.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the best practice for caching versioned content like API documentation?",
    option_a: "Cache all versions together",
    option_b: "Don't cache versioned content",
    option_c: "Cache each version separately with version in cache key",
    option_d: "Only cache the latest version",
    correct_answer: "C",
    explanation: "For versioned content, cache each version separately. Include the version in your cache strategy (implementation-dependent) so different versions don't invalidate each other's caches. This allows efficient caching across versions.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How often should you review and optimize your caching strategy?",
    option_a: "After every API call",
    option_b: "Weekly or when usage patterns change",
    option_c: "Once during initial implementation, then never",
    option_d: "Hourly to catch all changes",
    correct_answer: "B",
    explanation: "Review caching strategy weekly or when usage patterns change significantly. This balances the need for optimization with practical development cycles. Monitor metrics to identify when optimization is needed.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your application has 5 different system prompts for different use cases. How should you approach caching?",
    option_a: "Cache all prompts in a single cache",
    option_b: "Cache each prompt separately for its use case",
    option_c: "Don't cache; too much variation",
    option_d: "Merge all prompts and cache the combined version",
    correct_answer: "B",
    explanation: "Cache each system prompt separately for its respective use case. Each use case benefits from caching its own prompt independently. Don't merge them as that would send unnecessary content for each request.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the impact of caching very large content (e.g., 150K tokens)?",
    option_a: "API rejects requests with content over 100K",
    option_b: "Higher cache write cost initially, but proportionally more savings on reuse",
    option_c: "Large content cannot be cached",
    option_d: "Cache efficiency decreases with size",
    correct_answer: "B",
    explanation: "Caching very large content has a higher initial cache write cost, but provides proportionally greater savings when reused multiple times. The cost-benefit improves with content size, assuming frequent reuse.",
    difficulty: "hard"
  },

  // Context editing strategies (15 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is context editing in Claude?",
    option_a: "Manual modification of conversation history",
    option_b: "Strategies for managing context size by selectively removing content",
    option_c: "Automatic grammar correction in context",
    option_d: "Version control for prompts",
    correct_answer: "B",
    explanation: "Context editing refers to strategies for managing context size by selectively removing or modifying content, helping keep conversations within context window limits.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What is the clear_tool_uses_20250919 strategy?",
    option_a: "A tool for clearing cache",
    option_b: "A context editing strategy that clears old tool results",
    option_c: "A method for deleting all tools",
    option_d: "A versioning system for tools",
    correct_answer: "B",
    explanation: "The clear_tool_uses_20250919 strategy is a context editing approach that automatically clears old tool results, helping manage context size in agentic workflows.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does clear_tool_uses_20250919 determine which tool results to clear?",
    option_a: "Randomly selects results to remove",
    option_b: "Clears tool results chronologically from oldest to newest",
    option_c: "Removes largest results first",
    option_d: "Clears all results at once",
    correct_answer: "B",
    explanation: "The clear_tool_uses_20250919 strategy clears tool results chronologically, removing the oldest tool results first. This preserves recent context while managing overall context size.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "When is context editing most valuable?",
    option_a: "In short, single-turn interactions",
    option_b: "In long-running agentic workflows with many tool calls",
    option_c: "Only when approaching 1M token limit",
    option_d: "When using streaming responses",
    correct_answer: "B",
    explanation: "Context editing is most valuable in long-running agentic workflows where many tool calls accumulate large amounts of tool results, potentially filling the context window.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What content does clear_tool_uses_20250919 NOT remove?",
    option_a: "Old tool results",
    option_b: "Recent tool results and other conversation content",
    option_c: "System messages",
    option_d: "User queries",
    correct_answer: "B",
    explanation: "The clear_tool_uses_20250919 strategy specifically removes old tool results while preserving recent tool results and other conversation content like messages, ensuring context continuity.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your AI agent makes 50 tool calls in a workflow, each returning 5K tokens. What strategy helps manage this?",
    option_a: "Increase context window to 1M tokens",
    option_b: "Use clear_tool_uses_20250919 to clear old tool results",
    option_c: "Disable tool use entirely",
    option_d: "Cache all tool results",
    correct_answer: "B",
    explanation: "With 50 tool calls producing 250K tokens of results, use clear_tool_uses_20250919 to clear old tool results. This prevents context overflow while maintaining recent results needed for the workflow.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Can you customize which tool results get cleared in context editing?",
    option_a: "Yes, you can specify individual results to keep",
    option_b: "No, the strategy follows its built-in logic",
    option_c: "Yes, but only for Enterprise accounts",
    option_d: "Yes, by setting priority flags on tools",
    correct_answer: "B",
    explanation: "The clear_tool_uses_20250919 strategy follows its built-in chronological logic and cannot be customized. It systematically clears oldest results first without user control over specific results.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the trade-off of using context editing strategies?",
    option_a: "Increased API costs",
    option_b: "Slower response times",
    option_c: "Potential loss of information from cleared content",
    option_d: "Reduced model accuracy",
    correct_answer: "C",
    explanation: "The main trade-off of context editing is potential loss of information from cleared content. While it helps manage context size, the model no longer has access to removed tool results.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does context editing differ from server-side compaction?",
    option_a: "They are the same feature",
    option_b: "Context editing is manual; compaction is automatic",
    option_c: "Context editing removes content; compaction summarizes it",
    option_d: "Compaction only works for tool results",
    correct_answer: "C",
    explanation: "Context editing strategies like clear_tool_uses_20250919 remove content entirely, while server-side compaction summarizes content. Both manage context size but use different approaches.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "When should you implement custom context editing instead of using clear_tool_uses_20250919?",
    option_a: "Never; always use built-in strategies",
    option_b: "When you need domain-specific logic for what to keep",
    option_c: "When using fewer than 10 tools",
    option_d: "When using Enterprise accounts",
    correct_answer: "B",
    explanation: "Implement custom context editing when you need domain-specific logic, such as keeping certain critical tool results while removing others, or using non-chronological prioritization. Use built-in strategies when chronological clearing suffices.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What happens if you don't use context editing in a long agentic workflow?",
    option_a: "The API automatically applies default editing",
    option_b: "You may hit context limits and need to restart",
    option_c: "Performance improves with more context",
    option_d: "Costs decrease due to better optimization",
    correct_answer: "B",
    explanation: "Without context editing in long workflows, tool results accumulate and may eventually hit context limits, forcing you to restart the workflow or manually manage context. Context editing prevents this.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Can context editing be combined with prompt caching?",
    option_a: "No, they are mutually exclusive",
    option_b: "Yes, they address different concerns and can work together",
    option_c: "Only for Enterprise accounts",
    option_d: "Yes, but only for tool definitions",
    correct_answer: "B",
    explanation: "Context editing and prompt caching address different concerns and can work together. Caching reduces costs for stable content, while editing manages dynamic tool results in workflows.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How should you design tools to work well with context editing?",
    option_a: "Make tools return maximum possible detail",
    option_b: "Design tools to return concise, essential information",
    option_c: "Avoid using tools in workflows with editing",
    option_d: "Make all tool results identical in size",
    correct_answer: "B",
    explanation: "Design tools to return concise, essential information. This minimizes context usage and reduces the need for aggressive context editing, while still providing necessary data.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the recommended approach for critical tool results that shouldn't be cleared?",
    option_a: "Use clear_tool_uses_20250919 and hope they're not cleared",
    option_b: "Store them client-side and reinject when needed",
    option_c: "Disable context editing entirely",
    option_d: "Mark them with a no-clear flag",
    correct_answer: "B",
    explanation: "For critical tool results, store them client-side and reinject when needed. Built-in strategies don't have exemption mechanisms, so client-side management gives you control over what to preserve.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How does context editing impact debugging agentic workflows?",
    option_a: "No impact; full history is always available",
    option_b: "Makes debugging harder since cleared results aren't visible",
    option_c: "Improves debugging by reducing noise",
    option_d: "Only affects production, not development",
    correct_answer: "B",
    explanation: "Context editing makes debugging harder because cleared tool results aren't visible in the conversation history. For development, consider logging full history client-side before editing occurs.",
    difficulty: "medium"
  },

  // Tool result management (10 questions)
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Why are tool results a common source of context bloat?",
    option_a: "Tools always return maximum-size responses",
    option_b: "Tool results can be very large and accumulate quickly in workflows",
    option_c: "Tool results are duplicated in context",
    option_d: "Tool results cannot be compressed",
    correct_answer: "B",
    explanation: "Tool results can be very large (e.g., API responses, file contents) and accumulate quickly in multi-step agentic workflows, making them a primary source of context bloat.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the best practice for tool design regarding context management?",
    option_a: "Return all available data for completeness",
    option_b: "Return only essential information needed for the task",
    option_c: "Always limit results to 100 characters",
    option_d: "Compress results using zip algorithms",
    correct_answer: "B",
    explanation: "Best practice is to design tools that return only essential information needed for the task. This minimizes context usage while providing necessary functionality.",
    difficulty: "easy"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How should you handle tools that potentially return very large results?",
    option_a: "Disable those tools entirely",
    option_b: "Implement pagination or filtering in the tool",
    option_c: "Use only with 1M context windows",
    option_d: "Cache all results automatically",
    correct_answer: "B",
    explanation: "For tools with potentially large results, implement pagination or filtering so the tool can return subsets of data rather than everything at once. This gives control over context usage.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your search tool returns 50K tokens of results, but Claude only uses the first few. What's the problem?",
    option_a: "Claude has a bug processing tool results",
    option_b: "The tool is returning too much unnecessary information",
    option_c: "You need a larger context window",
    option_d: "The tool results aren't formatted correctly",
    correct_answer: "B",
    explanation: "If Claude only uses a fraction of large tool results, the tool is returning too much unnecessary information. Refine the tool to return more targeted, relevant results to optimize context usage.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Should tool results be cached?",
    option_a: "Yes, always cache tool results",
    option_b: "No, tool results are too dynamic",
    option_c: "Only if the same tool with same params is called repeatedly",
    option_d: "Only for Enterprise accounts",
    correct_answer: "C",
    explanation: "Cache tool results only if the same tool with the same parameters is called repeatedly and returns the same data. Most tool results are dynamic and don't benefit from caching.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How can you monitor tool result impact on context usage?",
    option_a: "It's not possible to monitor",
    option_b: "Track token counts of tool results separately",
    option_c: "Only available in Enterprise dashboards",
    option_d: "Automatically monitored by clear_tool_uses_20250919",
    correct_answer: "B",
    explanation: "Monitor tool result impact by tracking token counts of tool results separately from other context. This helps identify which tools consume the most context and need optimization.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's a good heuristic for maximum tool result size?",
    option_a: "No limit; return everything",
    option_b: "Keep under 5-10K tokens unless essential",
    option_c: "Exactly 1000 tokens always",
    option_d: "50% of context window",
    correct_answer: "B",
    explanation: "A good heuristic is keeping tool results under 5-10K tokens unless larger results are essential. This prevents individual tools from consuming disproportionate context while allowing flexibility when needed.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "Your agent uses 10 different tools with varying result sizes. How should you approach tool result management?",
    option_a: "Limit all tools to the same size",
    option_b: "Optimize each tool individually based on its purpose",
    option_c: "Only optimize the largest tool",
    option_d: "Rely entirely on clear_tool_uses_20250919",
    correct_answer: "B",
    explanation: "Optimize each tool individually based on its purpose. Different tools have different needs; some naturally return more data. The goal is right-sized results for each tool's function.",
    difficulty: "medium"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "What's the relationship between tool result size and workflow complexity?",
    option_a: "No relationship",
    option_b: "Larger results enable more complex workflows",
    option_c: "Smaller, focused results allow longer workflows within context limits",
    option_d: "Complex workflows require disabling tools",
    correct_answer: "C",
    explanation: "Smaller, focused tool results allow longer, more complex workflows within context limits. Each tool call consumes less context, enabling more steps before hitting limits.",
    difficulty: "hard"
  },
  {
    week: 9,
    domain: "Context Management & Reliability",
    topic: "Context Management",
    question: "How should error messages in tool results be handled for context management?",
    option_a: "Return full stack traces always",
    option_b: "Return concise error messages with essential details",
    option_c: "Suppress all error messages",
    option_d: "Error messages don't affect context",
    correct_answer: "B",
    explanation: "Error messages should be concise with essential details. Full stack traces consume significant context unnecessarily. Provide enough information for Claude to understand and handle the error without excess verbosity.",
    difficulty: "medium"
  }
];
