export interface Question {
  week?: number;
  domain: string;
  topic: string;
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_answer: string;
  explanation: string;
  difficulty?: string;
}

export const topic7Questions: Question[] = [
  // Questions 1-15: XML tags
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Your LegalTech app extracts contract clauses but 30% have formatting inconsistencies causing downstream parsing failures. Restructure prompts using XML tags (`<context>`, `<task>`, `<instructions>`) to improve consistency by:",
    option_a: "Minimal improvement in consistency around 5-10% reduction in errors",
    option_b: "No measurable improvement without schema validation alongside XML tags",
    option_c: "Moderate improvement with 15-20% reduction in parsing failures",
    option_d: "Significant 20-40% improvement from clear structural prompt organization",
    correct_answer: "D",
    explanation: "XML tags like `<context>`, `<task>`, and `<instructions>` provide 20-40% more consistent outputs by clearly structuring prompts.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which XML tag is used to provide background information?",
    option_a: "`<background>`",
    option_b: "`<info>`",
    option_c: "`<context>`",
    option_d: "`<data>`",
    correct_answer: "C",
    explanation: "The `<context>` tag is the standard XML tag for providing background information in Claude prompts.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What is the recommended order for XML tags in a prompt?",
    option_a: "Random ordering since parsing handles any tag sequence equally well",
    option_b: "Alphabetical ordering for consistency and easier maintenance across prompts",
    option_c: "Task definition first followed by supporting context and instructions",
    option_d: "Context then task then instructions then output format then examples",
    correct_answer: "D",
    explanation: "The logical flow starts with context, then task definition, instructions, output format specification, and finally examples.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which tag defines what Claude should accomplish?",
    option_a: "`<goal>`",
    option_b: "`<task>`",
    option_c: "`<objective>`",
    option_d: "`<action>`",
    correct_answer: "B",
    explanation: "The `<task>` XML tag is used to clearly define what you want Claude to accomplish.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which tag contains step-by-step guidance?",
    option_a: "`<instructions>`",
    option_b: "`<steps>`",
    option_c: "`<procedure>`",
    option_d: "`<guide>`",
    correct_answer: "A",
    explanation: "The `<instructions>` tag is used for detailed, step-by-step guidance on how to complete the task.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "How many examples are recommended for multishot prompting?",
    option_a: "3-5 examples",
    option_b: "1-2 examples",
    option_c: "10+ examples",
    option_d: "Examples are not recommended",
    correct_answer: "A",
    explanation: "3-5 examples provide the optimal balance between pattern demonstration and token efficiency.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which tag specifies the desired output structure?",
    option_a: "`<structure>`",
    option_b: "`<output_format>`",
    option_c: "`<format>`",
    option_d: "`<style>`",
    correct_answer: "B",
    explanation: "The `<output_format>` XML tag is used to specify how Claude should structure its response.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Claude's Extended Thinking mode improves math problem accuracy from 75% to 95%, but your real-time tutoring app's response time increased from 2s to 8s. The primary trade-off is:",
    option_a: "Higher per token costs without corresponding latency changes for operations",
    option_b: "Reduced output quality requiring additional validation and correction steps",
    option_c: "Limited model availability restricted to Enterprise tier accounts only",
    option_d: "Additional latency from extended reasoning time before response generation",
    correct_answer: "D",
    explanation: "Extended Thinking adds latency because the model spends additional time on internal reasoning before generating output.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Claude's thinking process for complex math problems consumes 2,000 tokens per question, costing $0.80 each. To optimize costs while maintaining quality, limit internal reasoning by setting:",
    option_a: "max_tokens",
    option_b: "thinking_limit",
    option_c: "reasoning_budget",
    option_d: "budget_tokens",
    correct_answer: "D",
    explanation: "The `budget_tokens` parameter controls how many tokens the model can use for internal reasoning.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Where does Extended Thinking reasoning appear by default?",
    option_a: "Displayed inline within the visible text output responses automatically",
    option_b: "Stored in response metadata fields accessible via API parameters",
    option_c: "Returned in separate dedicated field alongside main content output",
    option_d: "Captured internally hidden by default unless explicitly requested via API",
    correct_answer: "D",
    explanation: "Extended Thinking reasoning is internal by default and not displayed unless specifically requested.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which tag is used for providing examples?",
    option_a: "`<examples>`",
    option_b: "`<samples>`",
    option_c: "`<demonstrations>`",
    option_d: "`<patterns>`",
    correct_answer: "A",
    explanation: "The `<examples>` tag is the standard XML tag for multishot prompting examples.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Can you nest XML tags in prompts?",
    option_a: "Yes, nesting is supported and useful for complex organization",
    option_b: "No, all tags must be at the same level",
    option_c: "Only with Extended Thinking",
    option_d: "Only on Opus models",
    correct_answer: "A",
    explanation: "XML tags can be nested in prompts to create hierarchical organization of complex information.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What effort level is appropriate for simple tasks?",
    option_a: "xhigh",
    option_b: "low or medium",
    option_c: "high",
    option_d: "adaptive only",
    correct_answer: "B",
    explanation: "Simple tasks should use 'low' or 'medium' effort levels to avoid unnecessary processing.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What is the correct thinking configuration for Opus 4.8?",
    option_a: "thinking: {enabled: true}",
    option_b: "thinking: {mode: \"adaptive\"}",
    option_c: "thinking: {level: \"adaptive\"}",
    option_d: "thinking: {type: \"adaptive\"}",
    correct_answer: "D",
    explanation: "The correct configuration is `thinking: {type: \"adaptive\"}` for Extended Thinking API.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "How do XML tags improve prompt parsing?",
    option_a: "They reduce total token count through efficient encoding compression",
    option_b: "They enable faster processing speeds with optimized parsing algorithms",
    option_c: "They clearly separate sections making them easier to identify and process",
    option_d: "They compress data using XML schema validation and reduction",
    correct_answer: "C",
    explanation: "XML tags provide clear boundaries between sections, making it easier for Claude to parse and understand each component.",
    difficulty: "medium"
  },
  // Questions 16-30: Extended Thinking API
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What happens when budget_tokens is increased?",
    option_a: "Model has more reasoning capacity potentially improving output quality significantly",
    option_b: "Response generation speed increases with larger allocated token budget",
    option_c: "Total processing cost decreases through more efficient reasoning allocation",
    option_d: "Output complexity becomes simpler with increased budget token availability",
    correct_answer: "A",
    explanation: "Higher budget_tokens allows more internal reasoning, which can improve response quality for complex tasks.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which model primarily supports Extended Thinking?",
    option_a: "Claude Opus 4.8",
    option_b: "All Claude models",
    option_c: "Only Sonnet models",
    option_d: "Claude Haiku 4.5",
    correct_answer: "A",
    explanation: "Extended Thinking is primarily available on Claude Opus 4.8, the most capable model.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What impact does Extended Thinking have on latency?",
    option_a: "No impact",
    option_b: "Reduces latency",
    option_c: "Slightly increases it",
    option_d: "Adds noticeable latency due to reasoning time",
    correct_answer: "D",
    explanation: "Extended Thinking adds noticeable latency because the model performs additional reasoning before responding.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "When should you use the `<task>` tag?",
    option_a: "To define the main objective",
    option_b: "To provide context",
    option_c: "To show examples",
    option_d: "To specify format",
    correct_answer: "A",
    explanation: "The `<task>` tag is used to clearly define the main objective or goal of the prompt.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What's the main difference between `<thinking>` tags and Extended Thinking API?",
    option_a: "They are the same feature with different naming conventions used",
    option_b: "Extended Thinking is cheaper with reduced per token processing costs",
    option_c: "Thinking tags are prompting technique while Extended Thinking is built in API feature",
    option_d: "Thinking tags work only on Opus models with advanced capabilities",
    correct_answer: "C",
    explanation: "`<thinking>` tags are a prompting technique where you instruct Claude to show reasoning. Extended Thinking is a built-in API feature with dedicated reasoning capacity.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which parameter controls maximum reasoning tokens?",
    option_a: "max_thinking",
    option_b: "reasoning_limit",
    option_c: "thinking_budget",
    option_d: "budget_tokens",
    correct_answer: "D",
    explanation: "The `budget_tokens` parameter controls the maximum tokens allocated for internal reasoning.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Can you combine `<thinking>` tags with Extended Thinking API?",
    option_a: "No, mutually exclusive",
    option_b: "Only on Sonnet",
    option_c: "Yes, for maximum reasoning transparency",
    option_d: "Only in specific cases",
    correct_answer: "B",
    explanation: "While technically possible, combining both may result in redundant reasoning output and is generally not recommended.",
    difficulty: "hard"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What's a key advantage of Extended Thinking API?",
    option_a: "Lower cost",
    option_b: "Available on all models",
    option_c: "Dedicated reasoning that doesn't clutter output",
    option_d: "Faster processing",
    correct_answer: "C",
    explanation: "Extended Thinking provides dedicated internal reasoning that improves quality without cluttering the visible output.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What is a key advantage of Extended Thinking over manual reasoning prompts?",
    option_a: "Processing is always faster with optimized reasoning token allocation",
    option_b: "Feature is free without additional token costs for thinking",
    option_c: "Available everywhere across all models tiers and deployment regions",
    option_d: "Provides dedicated reasoning capacity with cleaner more focused outputs",
    correct_answer: "A",
    explanation: "Extended Thinking provides dedicated reasoning capacity that improves quality while keeping outputs clean, unlike manual reasoning prompts that include reasoning in the visible output.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "How many examples work best for multishot prompting?",
    option_a: "1-2",
    option_b: "3-5",
    option_c: "10+",
    option_d: "As many as possible",
    correct_answer: "B",
    explanation: "3-5 examples provide optimal balance between pattern demonstration and context efficiency.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Where does reasoning appear when using `<thinking>` tags?",
    option_a: "In metadata",
    option_b: "In visible output text",
    option_c: "In a separate field",
    option_d: "Only in debug mode",
    correct_answer: "B",
    explanation: "When using `<thinking>` tags as a prompting technique, Claude includes reasoning directly in the visible output.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which is better for production APIs with clean outputs?",
    option_a: "Neither approach works well for production API clean outputs",
    option_b: "Extended Thinking API keeps reasoning internal for cleaner responses",
    option_c: "Always use thinking tags for maximum transparency and debugging",
    option_d: "Mix both randomly to balance performance and visibility trade offs",
    correct_answer: "B",
    explanation: "Extended Thinking API is better for production because reasoning stays internal, keeping outputs clean.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "How does Extended Thinking affect token usage?",
    option_a: "Uses fewer tokens through optimized reasoning compression algorithms",
    option_b: "Same token usage as regular requests without thinking enabled",
    option_c: "Uses budget tokens allocation plus standard output tokens combined",
    option_d: "More efficient than thinking tags with reduced overhead costs",
    correct_answer: "C",
    explanation: "Extended Thinking uses budget_tokens for reasoning plus output tokens, whereas `<thinking>` tags include reasoning in output tokens.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What tasks benefit most from Extended Thinking?",
    option_a: "Simple queries and straightforward information retrieval tasks",
    option_b: "Data formatting and structured output generation tasks",
    option_c: "Complex reasoning mathematics and multi step problem solving tasks",
    option_d: "Template filling and content generation from predefined structures",
    correct_answer: "C",
    explanation: "Extended Thinking excels at complex reasoning tasks like math problems, analysis, and multi-step problem solving.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What are the effort levels in Extended Thinking?",
    option_a: "Easy medium and hard effort levels for task complexity",
    option_b: "Four effort levels low medium high and extra high",
    option_c: "One through five numeric scale for reasoning intensity",
    option_d: "Minimal standard and maximum effort levels for processing",
    correct_answer: "B",
    explanation: "Extended Thinking supports four effort levels: low, medium, high, and xhigh.",
    difficulty: "medium"
  },
  // Questions 31-45: Thinking tags vs Extended Thinking
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Can you access internal thinking from Extended Thinking?",
    option_a: "Never accessible as thinking is permanently internal only",
    option_b: "Yes accessible by requesting it explicitly in API parameters",
    option_c: "Always included automatically in all response outputs",
    option_d: "Only on Opus models with advanced reasoning capabilities",
    correct_answer: "B",
    explanation: "Internal thinking can be accessed by specifically requesting it through API parameters.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which models support `<thinking>` tags?",
    option_a: "Only Opus four point eight with extended thinking capabilities",
    option_b: "All Claude models support thinking tags via prompting techniques",
    option_c: "Only Claude four point X series models support prompting",
    option_d: "Only Sonnet and Opus models with advanced reasoning features",
    correct_answer: "B",
    explanation: "`<thinking>` tags are a prompting technique that works with all Claude models.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What happens if a task is simpler than expected?",
    option_a: "All budget tokens are used anyway regardless of complexity",
    option_b: "Unused tokens are refunded back reducing actual usage costs",
    option_c: "Model may use fewer tokens with adaptive thinking enabled",
    option_d: "An error occurs requiring manual effort level adjustment",
    correct_answer: "B",
    explanation: "With adaptive thinking, the model can use fewer tokens than budgeted if the task is simpler.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which approach offers more control over reasoning format?",
    option_a: "Extended Thinking API provides granular control over reasoning format",
    option_b: "Neither approach offers meaningful control over reasoning format",
    option_c: "Both approaches are equal in format control capabilities",
    option_d: "Thinking tags in prompts allow custom format specification",
    correct_answer: "D",
    explanation: "`<thinking>` tags give more format control since you can specify the reasoning structure in your prompt.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Why combine both techniques?",
    option_a: "For maximum reasoning depth with transparency",
    option_b: "To reduce cost",
    option_c: "For speed optimization",
    option_d: "To reduce tokens",
    correct_answer: "A",
    explanation: "Combining both provides maximum reasoning depth (from API) with transparency (from prompted tags).",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What reasoning format control does Extended Thinking offer?",
    option_a: "Complete format control through comprehensive API configuration options",
    option_b: "Limited control through API parameters with predefined formats",
    option_c: "No format control available reasoning structure is fixed",
    option_d: "Same level of control as thinking tags prompting approach",
    correct_answer: "B",
    explanation: "Extended Thinking offers limited format control through API parameters, unlike the flexible control of `<thinking>` tags.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "How does Opus 4.8 handle effort levels?",
    option_a: "Strictly respects them, allocating appropriate resources",
    option_b: "They're only suggestions",
    option_c: "They only affect pricing",
    option_d: "They're ignored",
    correct_answer: "A",
    explanation: "Opus 4.8 strictly respects effort levels, allocating appropriate reasoning resources for each level.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What visibility advantage do `<thinking>` tags have?",
    option_a: "No visibility advantage over Extended Thinking API approach",
    option_b: "Lower cost per token for visible reasoning output",
    option_c: "Reasoning is immediately visible without extra configuration needed",
    option_d: "Faster processing with optimized visible reasoning display",
    correct_answer: "C",
    explanation: "`<thinking>` tags make reasoning immediately visible in the output without additional API configuration.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "For debugging AI behaviors, which is better?",
    option_a: "Neither helps",
    option_b: "Extended Thinking only",
    option_c: "`<thinking>` tags for visibility by default",
    option_d: "Both are equally unsuitable",
    correct_answer: "C",
    explanation: "`<thinking>` tags are better for debugging because reasoning is visible by default in the output.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What costs apply when using Extended Thinking?",
    option_a: "It's free",
    option_b: "Both thinking and output tokens",
    option_c: "Only output tokens",
    option_d: "Same as regular requests",
    correct_answer: "B",
    explanation: "Extended Thinking charges for both thinking tokens (budget_tokens) and output tokens.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Can `<thinking>` tags work without Extended Thinking API?",
    option_a: "No, they require it",
    option_b: "Yes, they're independent",
    option_c: "Only with special config",
    option_d: "Only on Opus",
    correct_answer: "C",
    explanation: "`<thinking>` tags are a standalone prompting technique that work independently of Extended Thinking API.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which technique excels at mathematical proofs?",
    option_a: "Extended Thinking API with dedicated reasoning",
    option_b: "Neither",
    option_c: "Regular prompting",
    option_d: "`<thinking>` tags only",
    correct_answer: "A",
    explanation: "Extended Thinking API is particularly well-suited for mathematical proofs due to dedicated reasoning capacity.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "How do `<thinking>` tags impact context window?",
    option_a: "Reasoning consumes output tokens, reducing space for other content",
    option_b: "No impact",
    option_c: "Increases window",
    option_d: "Reduces available context",
    correct_answer: "D",
    explanation: "Reasoning in `<thinking>` tags consumes output tokens, potentially leaving less room for other content.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What cost consideration exists with Extended Thinking?",
    option_a: "Both thinking and output tokens are charged",
    option_b: "Same as regular",
    option_c: "Only output tokens",
    option_d: "It's free",
    correct_answer: "A",
    explanation: "Extended Thinking charges for both thinking tokens (budget_tokens) and regular output tokens.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "How does Extended Thinking handle multi-step reasoning?",
    option_a: "Doesn't support it",
    option_b: "It can chain multiple reasoning steps using budget_tokens",
    option_c: "Limited to three steps",
    option_d: "Only single-step",
    correct_answer: "B",
    explanation: "Extended Thinking can internally chain multiple reasoning steps using the budget_tokens allocation.",
    difficulty: "medium"
  },
  // Questions 46-65: Structured Outputs (JSON mode and tool use)
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Best practice for `<thinking>` tags in user-facing apps?",
    option_a: "Always show all thinking",
    option_b: "Never use in production",
    option_c: "Parse and separate thinking from final output",
    option_d: "Combine randomly",
    correct_answer: "B",
    explanation: "For user-facing apps, parse and separate thinking from final output for better UX.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which models support Structured Outputs?",
    option_a: "Only Opus 4.8",
    option_b: "All Claude models",
    option_c: "Only Sonnet",
    option_d: "Opus 4.8, Mythos Preview, Opus 4.7/4.6, Sonnet 4.6/4.5, Haiku 4.5",
    correct_answer: "D",
    explanation: "Structured Outputs are supported on Opus 4.8, Mythos Preview, Opus 4.7/4.6, Sonnet 4.6/4.5, and Haiku 4.5.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Your data extraction tool needs guaranteed JSON schema compliance for parsing pipelines. Simply asking \"respond in JSON\" in prompts fails 15% of the time. Enable strict JSON mode by:",
    option_a: "Set `json: true`",
    option_b: "Set `output_config: {format: \"json\"}` and provide schema",
    option_c: "Use `json_mode` parameter",
    option_d: "Include \"Please respond in JSON\" in prompt",
    correct_answer: "B",
    explanation: "JSON mode is enabled by setting `output_config: {format: \"json\"}` and providing a JSON schema.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Where is the JSON response located?",
    option_a: "In `response.json`",
    option_b: "In `response.output`",
    option_c: "In `response.data`",
    option_d: "In `response.content[0].text` as JSON string",
    correct_answer: "A",
    explanation: "JSON mode returns the response in `response.content[0].text` as a JSON string conforming to the schema.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What enables strict schema validation for tools?",
    option_a: "`validate: true`",
    option_b: "`strict: true` in tool definition",
    option_c: "`schema_strict: true`",
    option_d: "`enforce_schema: true`",
    correct_answer: "C",
    explanation: "Setting `strict: true` in the tool definition enables strict schema validation.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What happens with strict tool use and mismatched parameters?",
    option_a: "Model corrects automatically",
    option_b: "Warning logged",
    option_c: "Parameters ignored",
    option_d: "Request fails with validation error",
    correct_answer: "B",
    explanation: "With strict tool use, mismatched parameters cause the request to fail with a validation error.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Can you use JSON mode and tool use together?",
    option_a: "No, mutually exclusive",
    option_b: "Only on Opus",
    option_c: "Yes, but must choose precedence",
    option_d: "Only in beta",
    correct_answer: "C",
    explanation: "You can use both together but must specify which takes precedence for output structure.",
    difficulty: "hard"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What's a key benefit of strict tool use?",
    option_a: "Faster processing",
    option_b: "Lower costs",
    option_c: "Increased context window",
    option_d: "Guaranteed type safety and schema compliance",
    correct_answer: "C",
    explanation: "Strict tool use guarantees type safety and schema compliance for tool parameters.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which JSON schema features are supported?",
    option_a: "All features",
    option_b: "Only basic types",
    option_c: "Basic types, objects, arrays, enums, required fields",
    option_d: "Only strings and numbers",
    correct_answer: "C",
    explanation: "Structured Outputs support basic types, objects, arrays, enums, and required field specifications.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Purpose of JSON schema in JSON mode?",
    option_a: "Improve performance",
    option_b: "Define exact structure for output",
    option_c: "Reduce token usage",
    option_d: "Enable caching",
    correct_answer: "B",
    explanation: "The JSON schema defines the exact structure that the model's output must follow.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "How does JSON mode differ from prompting for JSON?",
    option_a: "No difference",
    option_b: "JSON mode is faster",
    option_c: "JSON mode guarantees schema compliance; prompting is best-effort",
    option_d: "Prompting is more reliable",
    correct_answer: "C",
    explanation: "JSON mode guarantees schema-compliant output, while prompting for JSON is best-effort.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What if model can't match the schema?",
    option_a: "Returns closest match",
    option_b: "Returns error response",
    option_c: "Falls back to text",
    option_d: "Returns null",
    correct_answer: "B",
    explanation: "If the model can't satisfy the schema, it returns an error response.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Can you specify optional fields in schemas?",
    option_a: "No, all must be required",
    option_b: "Yes, by omitting from \"required\" array",
    option_c: "Only on Opus",
    option_d: "Only with extra config",
    correct_answer: "A",
    explanation: "Optional fields can be specified by omitting them from the \"required\" array.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Relationship between tool use and function calling?",
    option_a: "Unrelated features",
    option_b: "Tool use is newer term for function calling",
    option_c: "Function calling is more advanced",
    option_d: "Different models",
    correct_answer: "D",
    explanation: "Tool use is the current terminology for what was previously called function calling.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Schema complexity support in strict tool use?",
    option_a: "Unlimited",
    option_b: "Simple only",
    option_c: "Nested objects and arrays to reasonable depth",
    option_d: "Only flat structures",
    correct_answer: "B",
    explanation: "Strict tool use supports nested objects and arrays up to reasonable depth.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "How to specify enum values in schemas?",
    option_a: "Using `options` field",
    option_b: "Using `values` field",
    option_c: "Using `enum` field with array",
    option_d: "Using `choices` field",
    correct_answer: "C",
    explanation: "Enum values are specified using the `enum` field with an array of allowed values.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Common use case for JSON mode?",
    option_a: "Creative writing",
    option_b: "General conversation",
    option_c: "Extracting structured data with guaranteed format",
    option_d: "Image analysis",
    correct_answer: "C",
    explanation: "JSON mode is commonly used for extracting structured data with guaranteed formatting.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What if schema has circular reference?",
    option_a: "Works fine",
    option_b: "Model handles automatically",
    option_c: "May cause validation errors or rejection",
    option_d: "Only works on Opus",
    correct_answer: "C",
    explanation: "Circular references are not well-supported and may cause validation errors or rejection.",
    difficulty: "hard"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Are all JSON Schema drafts supported?",
    option_a: "Yes, all drafts fully",
    option_b: "Only latest draft",
    option_c: "Only commonly-used feature subset",
    option_d: "Only draft-04",
    correct_answer: "C",
    explanation: "Only a subset of commonly-used JSON Schema features are supported.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Can you use regex in JSON schemas?",
    option_a: "Full regex support",
    option_b: "No regex support",
    option_c: "Only basic patterns",
    option_d: "Only on Opus",
    correct_answer: "B",
    explanation: "Regular expressions and pattern matching are not currently supported.",
    difficulty: "medium"
  },
  // Questions 66-75: JSON schema compliance and limitations
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Recommended maximum nesting depth for schemas?",
    option_a: "2 levels",
    option_b: "5 levels",
    option_c: "No limit",
    option_d: "3-4 levels to avoid complexity",
    correct_answer: "B",
    explanation: "While no hard limit exists, 3-4 levels of nesting is recommended to avoid complexity issues.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Is `additionalProperties` supported in schemas?",
    option_a: "Yes, fully supported",
    option_b: "No, not supported",
    option_c: "Only on Opus",
    option_d: "Only with strict: false",
    correct_answer: "C",
    explanation: "The `additionalProperties` field is fully supported in JSON schemas.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What types can be in schema's `type` field?",
    option_a: "Only string and number",
    option_b: "string, number, boolean, null, object, array",
    option_c: "Any custom type",
    option_d: "Only primitives",
    correct_answer: "C",
    explanation: "The `type` field supports: string, number, boolean, null, object, and array.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Can you specify min/max for numbers?",
    option_a: "No numeric constraints",
    option_b: "Yes, using `minimum` and `maximum`",
    option_c: "Only for integers",
    option_d: "Only on Opus",
    correct_answer: "B",
    explanation: "Numeric constraints can be specified using `minimum` and `maximum` fields.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What happens with JSON mode and citations enabled?",
    option_a: "Citations in separate field",
    option_b: "Only citations work",
    option_c: "Only JSON works",
    option_d: "Returns 400 error as they conflict",
    correct_answer: "B",
    explanation: "Citations and JSON schema mode conflict, resulting in a 400 error.",
    difficulty: "hard"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Are `$ref` references supported?",
    option_a: "Yes, fully",
    option_b: "No, not supported",
    option_c: "Only local references",
    option_d: "Only on Opus",
    correct_answer: "B",
    explanation: "The `$ref` keyword is not currently supported. Schemas must be self-contained.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Can you specify string length constraints?",
    option_a: "No string constraints",
    option_b: "Yes, using `minLength` and `maxLength`",
    option_c: "Only max length",
    option_d: "Only on text models",
    correct_answer: "B",
    explanation: "String length can be constrained using `minLength` and `maxLength` fields.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Your caching strategy saves 40% on API costs by caching system prompts. At 2:00 PM, you make a cached request. At 2:45 PM, another request hits the cache. When does the cache expire?",
    option_a: "2:00 PM + 24 hours = next day 2:00 PM",
    option_b: "2:00 PM + 30 minutes = 2:30 PM (already expired)",
    option_c: "Never expires (indefinitely)",
    option_d: "2:45 PM + 1 hour = 3:45 PM (extends on each use)",
    correct_answer: "D",
    explanation: "Prompt caches persist for 1 hour from the last time they were accessed.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Caching saved $800/month. Today you updated the system prompt to fix a typo, and costs spiked back to $2,000/month. Your cache was invalidated by:",
    option_a: "Time expiration only",
    option_b: "Any change to cached content (even minor edits)",
    option_c: "Model updates only",
    option_d: "All of the above",
    correct_answer: "D",
    explanation: "Caches are invalidated by time expiration, content changes, or model updates.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Which models preserve thinking blocks in cache?",
    option_a: "All models",
    option_b: "Only Opus",
    option_c: "Opus 4.5+, Sonnet 4.6+",
    option_d: "No models",
    correct_answer: "B",
    explanation: "Thinking blocks are preserved in cache on Opus 4.5+ and Sonnet 4.6+ models.",
    difficulty: "medium"
  },
  // Questions 76-85: Prompt caching
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Minimum size to benefit from caching?",
    option_a: "100 tokens",
    option_b: "2048 tokens (cache breakpoint)",
    option_c: "500 tokens",
    option_d: "5000 tokens",
    correct_answer: "A",
    explanation: "The cache breakpoint is 2048 tokens - content should be at least this size to benefit.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Can you cache system prompts?",
    option_a: "No, only user messages",
    option_b: "Only on Opus",
    option_c: "Yes, system prompts can be cached",
    option_d: "Only in special mode",
    correct_answer: "A",
    explanation: "System prompts can be cached, which is useful for consistent system prompts across requests.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What if cached content is slightly modified?",
    option_a: "Partial update",
    option_b: "Cache remains valid",
    option_c: "Entire cache invalidated and rebuilt",
    option_d: "Only changed portion re-cached",
    correct_answer: "C",
    explanation: "Any modification, even minor, invalidates the entire cache requiring a full rebuild.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Cache impact on first vs subsequent requests?",
    option_a: "No difference",
    option_b: "First slower, subsequent faster",
    option_c: "First creates cache (normal speed), subsequent faster",
    option_d: "All equally fast",
    correct_answer: "D",
    explanation: "First request creates cache at normal speed; subsequent requests benefit from cache hits.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Best practice for maximizing cache hits?",
    option_a: "Randomize structure",
    option_b: "Keep static content first, variable last",
    option_c: "Mix content types",
    option_d: "Always change prompts",
    correct_answer: "C",
    explanation: "Place static content at the beginning (cached) and variable content at the end.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Are Extended Thinking blocks cached?",
    option_a: "Never",
    option_b: "Always on all models",
    option_c: "On Opus 4.5+ and Sonnet 4.6+",
    option_d: "Only in debug mode",
    correct_answer: "C",
    explanation: "Thinking blocks are preserved in cache on Opus 4.5+ and Sonnet 4.6+ models.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Can you cache tool definitions?",
    option_a: "No",
    option_b: "Only simple tools",
    option_c: "Yes, when they remain constant",
    option_d: "Only on Opus",
    correct_answer: "C",
    explanation: "Tool definitions can be cached when they remain constant across requests.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Primary purpose of multishot prompting?",
    option_a: "Reduce costs",
    option_b: "Demonstrate patterns through examples",
    option_c: "Increase speed",
    option_d: "Reduce tokens",
    correct_answer: "B",
    explanation: "Multishot prompting demonstrates patterns through examples for the model to replicate.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Can examples include `<thinking>` tags?",
    option_a: "No, output only",
    option_b: "Only on Opus",
    option_c: "Only with Extended Thinking",
    option_d: "Yes, helps model understand thought process",
    correct_answer: "D",
    explanation: "Including `<thinking>` tags in examples helps the model understand the reasoning process.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "What makes good multishot examples?",
    option_a: "As long as possible",
    option_b: "Generic and simple",
    option_c: "Representative with clear input-output mapping",
    option_d: "Complex and detailed",
    correct_answer: "D",
    explanation: "Good examples are representative of the task with clear input-output mapping.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Should examples be diverse or similar?",
    option_a: "All identical",
    option_b: "Completely random",
    option_c: "Diverse enough to cover different scenarios",
    option_d: "As similar as possible",
    correct_answer: "C",
    explanation: "Examples should be diverse enough to cover different scenarios within the task domain.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Risk of too many examples?",
    option_a: "No risk",
    option_b: "Better performance",
    option_c: "Consuming context without proportional benefit",
    option_d: "Faster responses",
    correct_answer: "C",
    explanation: "Too many examples consume context window space without proportional benefits.",
    difficulty: "medium"
  },
  // Questions 86-95: Multishot/few-shot prompting
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "When to use Extended Thinking vs standard prompting?",
    option_a: "Extended Thinking for complex reasoning; standard for simple tasks",
    option_b: "Never use Extended Thinking",
    option_c: "Always use Extended Thinking",
    option_d: "Only for math",
    correct_answer: "A",
    explanation: "Use Extended Thinking for complex reasoning tasks; standard prompting for simple tasks.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Best practice for combining techniques?",
    option_a: "Never combine",
    option_b: "Use all always",
    option_c: "Random combination",
    option_d: "Layer strategically: XML + multishot + caching",
    correct_answer: "D",
    explanation: "Layer techniques strategically: XML tags for structure, multishot for patterns, caching for reusable content.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Structure prompts for optimal caching?",
    option_a: "Randomize each time",
    option_b: "Mix content types",
    option_c: "Variable first",
    option_d: "Static first (cached), dynamic last",
    correct_answer: "D",
    explanation: "Place static content first (cached) and variable content last for optimal caching.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Benefit of JSON mode for data extraction?",
    option_a: "Faster only",
    option_b: "Lower costs",
    option_c: "Guaranteed structured format for reliable processing",
    option_d: "Better text quality",
    correct_answer: "C",
    explanation: "JSON mode guarantees structured output format for reliable downstream processing.",
    difficulty: "easy"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Most reliable combination for production structured outputs?",
    option_a: "Prompting only",
    option_b: "JSON mode + strict tool use + validation",
    option_c: "Extended Thinking only",
    option_d: "Caching only",
    correct_answer: "B",
    explanation: "JSON mode with schema, strict tool use, and validation provides most reliable structured outputs.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Optimal approach for repeated similar tasks?",
    option_a: "Smallest model always",
    option_b: "Cache instructions, use appropriate model",
    option_c: "Disable features",
    option_d: "Minimize length only",
    correct_answer: "B",
    explanation: "Cache static instructions/examples and use appropriately-sized model for cost-effectiveness.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "When to use strict tool use over JSON mode?",
    option_a: "Always use strict",
    option_b: "For absolute schema compliance guarantees",
    option_c: "Simple schemas only",
    option_d: "When caching enabled",
    correct_answer: "C",
    explanation: "Use strict tool use when you need absolute guarantees of schema compliance.",
    difficulty: "hard"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Handling errors in structured output generation?",
    option_a: "Retry same prompt",
    option_b: "Switch models",
    option_c: "Simplify schema or add context",
    option_d: "Disable strict mode",
    correct_answer: "B",
    explanation: "If generation fails, simplify the schema or provide more context/examples in the prompt.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Combining all features: Extended Thinking, strict JSON, multishot, caching?",
    option_a: "API error due to conflicts",
    option_b: "They work together harmoniously",
    option_c: "Only first works",
    option_d: "Performance degrades",
    correct_answer: "C",
    explanation: "All features work together: cached examples reduce cost, Extended Thinking provides reasoning, strict JSON ensures structure.",
    difficulty: "hard"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Verifying Extended Thinking is being used?",
    option_a: "Check response metadata for thinking tokens",
    option_b: "Compare latency",
    option_c: "Look for thinking block in response",
    option_d: "All of the above",
    correct_answer: "C",
    explanation: "Verify by checking thinking block, monitoring thinking tokens, and observing latency.",
    difficulty: "medium"
  },
  // Questions 96-100: Best practices and optimization
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Most common mistake with JSON schemas?",
    option_a: "Making them too simple",
    option_b: "Using required fields",
    option_c: "Including examples",
    option_d: "Making them overly complex",
    correct_answer: "A",
    explanation: "The most common mistake is creating overly complex schemas beyond what's needed.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "When to use effort levels in Opus 4.8?",
    option_a: "Always maximum",
    option_b: "Effort levels don't matter",
    option_c: "Only with Extended Thinking",
    option_d: "Match effort to task complexity",
    correct_answer: "D",
    explanation: "Match effort level to task complexity: low for simple, high/xhigh for complex reasoning.",
    difficulty: "hard"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Edge case with prompt caching?",
    option_a: "Cache shared across API keys",
    option_b: "Cache lasts indefinitely",
    option_c: "Slight modifications invalidate entire cache",
    option_d: "Cache shared between users",
    correct_answer: "C",
    explanation: "Even slight modifications invalidate the entire cache - caching is exact-match only.",
    difficulty: "hard"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "When to combine multishot with Extended Thinking?",
    option_a: "Never combine",
    option_b: "For complex tasks where examples show reasoning patterns",
    option_c: "Only simple tasks",
    option_d: "Only with caching disabled",
    correct_answer: "B",
    explanation: "Combine for complex tasks where examples can demonstrate both reasoning patterns and output structure.",
    difficulty: "medium"
  },
  {
    week: 7,
    domain: "Prompt Engineering & Structured Output",
    topic: "Prompt Engineering & Structured Output",
    question: "Best practice for handling null in JSON schemas?",
    option_a: "Avoid nulls entirely",
    option_b: "Use type arrays like [\"string\", \"null\"]",
    option_c: "All required",
    option_d: "Use defaults instead",
    correct_answer: "B",
    explanation: "Use type arrays like `[\"string\", \"null\"]` to explicitly allow nullable fields.",
    difficulty: "hard"
  }
];
