export interface Question {
  week?: number;
  domain: string;
  topic: string;
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_answer: string;
  explanation: string;
  difficulty?: string;
}

export const topic10Questions: Question[] = [
  // Citations feature basics (15 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your medical diagnosis app analyzes 200-page patient records. HIPAA auditors demand proof that every recommendation cites specific pages. You enable Citations API to provide:",
    option_a: "Faster response generation times",
    option_b: "Automatic source attribution with page-level references to patient records",
    option_c: "Reduced token costs for large documents",
    option_d: "Increased 500K context window capacity",
    correct_answer: "B",
    explanation: "Citations provides automatic source attribution with specific page references, exactly what HIPAA auditors need to verify recommendations trace back to patient record pages.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your pharmaceutical research tool synthesizes drug interactions from 50 clinical studies. FDA audit requires proving every claim comes from supplied studies, not general AI knowledge. Document grounding ensures:",
    option_a: "Studies are stored on secure servers",
    option_b: "Claude's answers come only from the 50 supplied studies",
    option_c: "Study PDFs are compressed for storage",
    option_d: "Studies are translated to multiple languages",
    correct_answer: "B",
    explanation: "Document grounding forces Claude to base answers exclusively on provided documents (the 50 studies), meeting FDA's requirement for verifiable sources.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Contract analysis tool processes 500-page merger agreements. Legal team needs to verify every clause interpretation has source attribution. Citations provides:",
    option_a: "Only document titles without specifics",
    option_b: "Traceable references with specific page numbers in the merger agreement",
    option_c: "General topic areas like 'contract law'",
    option_d: "External URL links to legal databases",
    correct_answer: "B",
    explanation: "Citations provides precise references with page numbers, allowing legal teams to verify every interpretation against specific merger agreement pages.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your custom implementation of citation tracking has 70% recall accuracy. You switch to Claude's Citations feature and benchmark shows it achieves:",
    option_a: "75% recall (5% improvement)",
    option_b: "80% recall (10% improvement)",
    option_c: "85% recall (15% improvement)",
    option_d: "95% recall (25% improvement)",
    correct_answer: "C",
    explanation: "Citations provides approximately 15% improved recall accuracy (70% → 85%) compared to custom implementations, demonstrating the built-in feature's effectiveness.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your JSON extraction pipeline needs source provenance. You enable both Citations and strict JSON schema mode. API returns:",
    option_a: "Citations automatically formatted as JSON",
    option_b: "400 Bad Request error - features conflict",
    option_c: "Citations silently disabled, JSON works",
    option_d: "JSON schema ignored, Citations works",
    correct_answer: "B",
    explanation: "Citations and strict JSON schema mode are incompatible - the API returns 400 error when both are enabled. You must choose one approach.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Financial analytics platform requires both structured JSON output for downstream systems AND source attribution for compliance. Your solution:",
    option_a: "Enable Citations and ignore the JSON schema conflict",
    option_b: "Disable strict JSON schema, implement custom citation logic, request JSON in prompt",
    option_c: "Use Citations and force JSON in system prompt",
    option_d: "Make two API calls: first with Citations, second with JSON schema",
    correct_answer: "B",
    explanation: "Since Citations conflicts with strict JSON schema, implement custom citation logic or use non-strict JSON (request in prompt) to get both structured output and source tracking.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Healthcare compliance team must audit AI-generated treatment recommendations against approved medical literature. Citations' primary benefit for SOC2 certification is:",
    option_a: "Reduced API costs by 30%",
    option_b: "Verifiable, auditable responses with traceable sources",
    option_c: "10x faster response generation times",
    option_d: "Unlimited context window for literature",
    correct_answer: "B",
    explanation: "For SOC2 and healthcare compliance, the primary benefit is verifiable, auditable responses where every recommendation traces to approved medical literature.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your insurance claims processor needs to cite policy documents stored in AWS S3. To use Citations, you must:",
    option_a: "Provide S3 URLs directly to Citations API",
    option_b: "Download documents from S3 and include content in request",
    option_c: "Enable Enterprise plan for external document access",
    option_d: "Configure Citations with S3 IAM credentials",
    correct_answer: "B",
    explanation: "Citations requires document content in the request - it doesn't fetch external documents. Download from S3 first, then include in the API call.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your startup processes 10M documents/month with Citations. CFO asks about token cost impact. Citations adds:",
    option_a: "50% overhead - significant cost increase",
    option_b: "20% overhead for citation metadata",
    option_c: "Minimal impact - documents tokenized normally, slight metadata overhead",
    option_d: "100% overhead - doubles token costs",
    correct_answer: "C",
    explanation: "Citations has minimal token cost impact. Documents are tokenized normally as input; citation metadata adds minimal overhead to output tokens.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Investment research platform analyzes company filings. Analyst wants to cite both factual data (revenue numbers) AND qualitative analysis (management tone). Citations can attribute sources for:",
    option_a: "Only numerical facts and direct quotes",
    option_b: "Any content in response - facts, analysis, summaries, paraphrases",
    option_c: "Only direct quotes from documents",
    option_d: "Only numerical data and tables",
    correct_answer: "B",
    explanation: "Citations works for any content type - facts, analysis, summaries, and paraphrases - as long as it's based on provided documents.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your API returns citation data to frontend. Backend engineer asks how citations are structured. They appear as:",
    option_a: "Inline markdown links like [1] embedded in text",
    option_b: "Structured JSON metadata with source IDs, page/character ranges",
    option_c: "Footnotes appended to the end of response text",
    option_d: "HTML <cite> annotations",
    correct_answer: "B",
    explanation: "Citations return as structured JSON metadata including source IDs, document references, and location information (pages/characters), separate from the text content.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Real-time trading algorithm ingests live market data feeds. You want to use Citations for trade decision provenance. This approach:",
    option_a: "Works perfectly - Citations handle any input",
    option_b: "Won't work well - Citations require static documents, not streaming data",
    option_c: "Works only with Enterprise real-time citation mode",
    option_d: "Works with special streaming citations API",
    correct_answer: "B",
    explanation: "Citations are designed for static documents with stable references. Real-time streams that constantly change aren't suitable since source references become invalid.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Document processing pipeline caches 5GB of regulatory documents using prompt caching. You add Citations to track compliance. These features:",
    option_a: "Are mutually exclusive - can't use both",
    option_b: "Work together - cache documents AND cite them, combining cost savings with provenance",
    option_c: "Caching disables Citations automatically",
    option_d: "Citations automatically enable caching",
    correct_answer: "B",
    explanation: "Citations and prompt caching work perfectly together - cache your documents for cost savings while still getting traceable citations to those cached documents.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your data extraction pipeline requires strict JSON schema for database insertion. Product manager wants to add Citations for audit trail. You explain:",
    option_a: "Easy - enable both features together",
    option_b: "Impossible - Citations conflict with strict JSON schema (returns 400 error)",
    option_c: "Possible only for documents under 50K tokens",
    option_d: "Available only on Enterprise plan",
    correct_answer: "B",
    explanation: "Citations and strict JSON schema are incompatible (400 error). For JSON + citations, use non-strict JSON mode or custom citation implementation.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Academic research assistant processes journal articles. Professor suspects AI is hallucinating references. Citations help prevent hallucination by:",
    option_a: "Eliminating all hallucinations completely",
    option_b: "Grounding responses in documents with traceable references - unsupported claims visible",
    option_c: "Having no effect on hallucination rates",
    option_d: "Only helping with numerical data accuracy",
    correct_answer: "B",
    explanation: "Citations grounds responses in provided documents with traceable references. Claims without citations are visible, helping identify potential hallucinations.",
    difficulty: "medium"
  },

  // Document grounding (15 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your legal tech startup analyzes case law for lawyer clients. Bar association requires answers based ONLY on provided case documents, not AI's general legal knowledge. Document grounding ensures:",
    option_a: "Case documents are stored permanently in databases",
    option_b: "Claude's answers come exclusively from supplied case law documents",
    option_c: "Documents are compressed for efficient storage",
    option_d: "Case law is automatically translated to client's language",
    correct_answer: "B",
    explanation: "Document grounding forces Claude to base answers exclusively on supplied case law, meeting bar association requirements for verifiable legal sources.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Tax preparation software analyzes client's 15 documents: W2s, 1099s, receipts, deductions. IRS audit requires tracing every tax calculation. You can provide:",
    option_a: "Maximum 1 document per request",
    option_b: "Maximum 5 documents per request",
    option_c: "All 15 documents limited only by 200K token context window",
    option_d: "Unlimited documents with automatic pagination",
    correct_answer: "C",
    explanation: "No artificial document count limit - provide as many documents as fit in context window. All 15 tax documents can be included in one request.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your previous approach: prompt engineering 'Please cite sources' achieved 70% citation accuracy. Document grounding with Citations provides:",
    option_a: "Same 70% accuracy, no improvement",
    option_b: "85% accuracy - 15% better recall with structured, verifiable references automatically",
    option_c: "Only marginal 2-3% improvement",
    option_d: "100% accuracy guaranteed",
    correct_answer: "B",
    explanation: "Document grounding + Citations provides 15% better recall (70% → 85%) with structured, machine-readable references vs. manual citation prompts.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Patent analysis tool processes applications (PDFs), prior art (text), and examiner notes (JSON). All three formats in one request:",
    option_a: "Impossible - all documents must be same format",
    option_b: "Works - mix PDFs, text, and custom content with appropriate citation formats for each",
    option_c: "Only PDF + text allowed, no JSON",
    option_d: "Requires Enterprise multi-format license",
    correct_answer: "B",
    explanation: "Document grounding supports mixed formats in one request - PDFs (page citations), text (character indices), custom content (block indices).",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "SEC filing analyzer for hedge fund must answer questions using ONLY filed 10-K reports, never general financial knowledge. Best implementation:",
    option_a: "Fine-tune Claude exclusively on 10-K reports",
    option_b: "Use document grounding with Citations on supplied 10-Ks",
    option_c: "System prompt: 'Only use provided documents'",
    option_d: "Custom post-processing fact-checker",
    correct_answer: "B",
    explanation: "Document grounding with Citations is purpose-built for this: ensures answers come only from supplied 10-Ks with traceable page references.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Customer asks product specifications not covered in your 20 provided product manuals. With document grounding, Claude:",
    option_a: "Fabricates answer from general AI knowledge",
    option_b: "Explicitly states information not found in provided manuals",
    option_c: "Returns API error",
    option_d: "Automatically searches external documentation sources",
    correct_answer: "B",
    explanation: "Document grounding causes Claude to explicitly state when information isn't available in provided sources rather than using general knowledge.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your team worries document grounding will reduce response quality by 'restricting Claude's knowledge'. In practice, grounding:",
    option_a: "Always reduces quality by limiting knowledge",
    option_b: "Improves reliability and verifiability - appropriate trade-off for compliance use cases",
    option_c: "Has zero effect on response quality",
    option_d: "Only affects response speed, not quality",
    correct_answer: "B",
    explanation: "Grounding trades breadth (general knowledge) for reliability and verifiability (provable sources) - correct choice for legal, medical, financial compliance.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Insurance claims system: Ground policy document interpretation in policy PDFs, but allow general knowledge for claim processing workflows. You configure:",
    option_a: "Not possible - grounding is all-or-nothing",
    option_b: "Full grounding on all content",
    option_c: "Prompt instructions: 'Use policy docs for coverage questions, general knowledge for processing steps'",
    option_d: "Enterprise-only partial grounding mode",
    correct_answer: "C",
    explanation: "Prompt engineering allows partial grounding - specify which questions need document backing vs. general knowledge, though this reduces strict verification.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your data science team asks 'what's optimal document size for grounding?'. Best answer:",
    option_a: "Keep all documents under 1K tokens",
    option_b: "Optimal size is 10K tokens per document",
    option_c: "No specific limit - depends on use case and context window constraints",
    option_d: "Exactly 50K tokens for maximum citation accuracy",
    correct_answer: "C",
    explanation: "No one-size-fits-all limit. Document size should be determined by use case needs and total context window capacity (200K tokens).",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Medical diagnosis system: 3 research papers disagree on treatment protocol. Ground on all 3. Claude should:",
    option_a: "Automatically resolve contradiction using AI judgment",
    option_b: "Identify contradictory sources and cite which papers disagree",
    option_c: "Use only first document, ignore others",
    option_d: "Return API error on contradictory sources",
    correct_answer: "B",
    explanation: "Claude can identify and cite contradictory sources, showing doctors that papers disagree rather than hiding the contradiction - critical for medical decisions.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Customer support chatbot must align responses with official company policy manual. Document grounding ensures:",
    option_a: "3x faster response times",
    option_b: "Answers match official policies, preventing incorrect info from AI's general knowledge",
    option_c: "50% reduction in API costs",
    option_d: "Unlimited conversation length",
    correct_answer: "B",
    explanation: "Grounding on policy manual ensures support answers align with official policies, preventing incorrect information from Claude's general training.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Company policy manual updates weekly. Your app runs Monday-Friday. To keep grounding current, you:",
    option_a: "Impossible - Citations only work with static documents",
    option_b: "Fetch updated manual from CMS and include in each request",
    option_c: "Citations automatically track document versions",
    option_d: "Enable Enterprise document versioning mode",
    correct_answer: "B",
    explanation: "No automatic version tracking. Fetch the current version from your CMS and include it in requests to ground on latest policy.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your application grounds on technical documentation. Engineer asks if Claude will still understand industry terminology and context. Document grounding:",
    option_a: "Completely replaces all general knowledge",
    option_b: "Prioritizes documents for facts, still uses general knowledge for language understanding",
    option_c: "Has no effect on general knowledge usage",
    option_d: "Merges documents with general knowledge equally",
    correct_answer: "B",
    explanation: "Grounding prioritizes documents for factual claims but Claude still uses general knowledge for language understanding, reasoning, and technical terminology.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "QA team prepares documents for grounding. Best practice before including in requests:",
    option_a: "Always summarize documents first to reduce tokens",
    option_b: "Provide documents as-is with clear structure (headings, sections, formatting)",
    option_c: "Convert everything to plain text, remove formatting",
    option_d: "Split all documents into exactly 1K token chunks",
    correct_answer: "B",
    explanation: "Provide documents with original structure intact (headings, sections, formatting) - helps Citations generate accurate page/section references.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your code review assistant needs to cite specific functions in a GitHub repository. You can ground responses on:",
    option_a: "Impossible - only text documents supported",
    option_b: "Yes - include code files as documents, Claude cites specific files/functions",
    option_c: "Requires special code citation mode",
    option_d: "Only Python code supported",
    correct_answer: "B",
    explanation: "Code repositories work as documents for grounding - Claude can cite specific files, functions, or line ranges when answering code questions.",
    difficulty: "medium"
  },

  // Citation formats (PDF, text, custom) (20 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your legal document analyzer processes 300-page merger agreement PDF. Claude cites relevant sections. PDF citations use:",
    option_a: "0-indexed character ranges",
    option_b: "1-indexed page numbers (e.g., 'pages 45-47')",
    option_c: "Paragraph numbers",
    option_d: "Line numbers",
    correct_answer: "B",
    explanation: "PDF citations use 1-indexed page numbers matching what readers see (first page = 1), making references intuitive for legal review.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Plain text document processing: You provide 50KB text string, Claude cites specific passages. Text citations format:",
    option_a: "1-indexed page numbers",
    option_b: "Word offsets",
    option_c: "0-indexed character ranges (e.g., 'chars 5000-5500')",
    option_d: "Line numbers",
    correct_answer: "C",
    explanation: "Plain text citations use 0-indexed character ranges (programming convention), allowing precise location within the string.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your API receives JSON array of 200 product records. Claude analyzes and cites specific products. Custom content citations use:",
    option_a: "Page numbers",
    option_b: "Character indices",
    option_c: "0-indexed content block ranges (e.g., 'blocks 45-50')",
    option_d: "Custom IDs from your metadata",
    correct_answer: "C",
    explanation: "Custom content (like JSON arrays) uses 0-indexed block indices, referencing which elements/objects were cited.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Frontend developer asks: 'Why are PDF pages 1-indexed but text characters 0-indexed?' You explain:",
    option_a: "It's a bug scheduled for fix in next API version",
    option_b: "Matches user expectations (PDF page 1) and programming conventions (string[0])",
    option_c: "Backwards compatibility with legacy systems",
    option_d: "Arbitrary design decision",
    correct_answer: "B",
    explanation: "Intentional design: PDF pages match reader expectations (first page = 1), character indices match programming conventions (strings start at 0).",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Patent examiner reviews 50-page prior art PDF. Claude cites 'pages 10-12'. Your UI should navigate to:",
    option_a: "Character indices 10-12 in extracted text",
    option_b: "The actual pages numbered 10, 11, 12 visible in PDF viewer",
    option_c: "Content blocks 10-12 in structured data",
    option_d: "0-indexed pages 9-11",
    correct_answer: "B",
    explanation: "PDF page citations are 1-indexed and match physical pages - 'pages 10-12' means the 10th, 11th, and 12th pages as displayed in PDF viewer.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Text analysis: 100KB document, Claude cites 'characters 50000-51000'. To highlight in UI, you:",
    option_a: "Count 50,000 words from start",
    option_b: "Extract substring from index 50000 to 51000 (0-indexed)",
    option_c: "Navigate to pages 50000-51000",
    option_d: "Show lines 50000-51000",
    correct_answer: "B",
    explanation: "Character indices are 0-indexed positions in string. Extract text[50000:51000] to get cited content.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Data pipeline sends structured product catalog to Claude (JSON objects with descriptions, specs, prices). Custom content in Citations refers to:",
    option_a: "User-defined document file formats",
    option_b: "Structured data with defined blocks (JSON objects, XML elements) cited by block index",
    option_c: "Encrypted proprietary formats",
    option_d: "Compressed archive formats",
    correct_answer: "B",
    explanation: "Custom content = structured data (JSON, XML, etc.) where citations reference logical blocks (objects/elements) by 0-indexed position.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Multi-source research: You provide 3 PDFs (research papers), 2 text files (news articles), 1 JSON (dataset). In one request, Citations:",
    option_a: "Impossible - only one format per request",
    option_b: "Works - uses page numbers for PDFs, character indices for text, block indices for JSON",
    option_c: "Only PDF + text allowed together",
    option_d: "Requires Enterprise multi-format citation license",
    correct_answer: "B",
    explanation: "Mix document types freely - Citations automatically uses appropriate format: pages (PDF), characters (text), blocks (JSON).",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Legal brief PDF has Roman numerals for preface (i, ii, iii) then Arabic numerals for body (1, 2, 3). Claude cites content from preface as:",
    option_a: "Uses printed page numbers (i, ii, iii)",
    option_b: "Sequential 1-indexed numbers (preface page 'i' cited as page 1)",
    option_c: "0-indexed positions (preface page 'i' cited as page 0)",
    option_d: "Citations fail - requires consistent numbering",
    correct_answer: "B",
    explanation: "Citations use sequential physical position (1, 2, 3...) regardless of printed page numbers. First page is always 1.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "QA engineer asks 'How precise are character-based citations for text?' They provide:",
    option_a: "Exact character ranges where cited content appears",
    option_b: "Approximate paragraph locations ±50 characters",
    option_c: "Whole document reference only",
    option_d: "Line number approximations",
    correct_answer: "A",
    explanation: "Character citations are exact - specify precise character start/end positions of cited content in the string.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "E-commerce product catalog: 1000 JSON product objects. Claude cites 'blocks 100-105' for price comparison analysis. This references:",
    option_a: "Characters 100-105 in JSON string",
    option_b: "Pages 100-105 in PDF export",
    option_c: "The 101st through 106th product objects (0-indexed blocks 100-105)",
    option_d: "Lines 100-105 in JSON file",
    correct_answer: "C",
    explanation: "Block indices are 0-indexed. Blocks 100-105 = array indices 100-105, which are the 101st-106th elements.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Document prep team asks how to optimize PDFs for citation accuracy. Best practice:",
    option_a: "Convert all PDFs to plain text first",
    option_b: "Ensure PDFs have extractable text (OCR if scanned) and proper structure",
    option_c: "Split PDFs into single-page files",
    option_d: "Remove all images and tables from PDFs",
    correct_answer: "B",
    explanation: "Ensure PDFs have extractable text (OCR scanned documents) and maintain structure. Poor quality/scanned PDFs without OCR reduce citation accuracy.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Technical specification PDF: Feature description spans pages 15-17. Claude cites this feature with:",
    option_a: "Single page only (citations can't span pages)",
    option_b: "Page range 'pages 15-17' showing content crosses boundaries",
    option_c: "Multiple separate citations (page 15, page 16, page 17)",
    option_d: "Only allowed on Enterprise multi-page citations",
    correct_answer: "B",
    explanation: "Citations can span page ranges when content crosses boundaries, shown as 'pages 15-17'.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "UX designer asks: 'Character indices are precise but users can't navigate them in our UI.' Main limitation is:",
    option_a: "Character indices aren't precise enough",
    option_b: "Won't work for multi-line content",
    option_c: "Difficult for humans to use without tooling (need text editor with position indicators)",
    option_d: "Only work for English language text",
    correct_answer: "C",
    explanation: "Character indices are very precise but not human-friendly. Build UI tooling to convert character positions to visible highlights/scrolling.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Financial report PDF with complex multi-column layout and tables. Citations reference:",
    option_a: "Fail completely for complex layouts",
    option_b: "Text in extraction order (may not match visual reading order)",
    option_c: "Only content from tables (skipping body text)",
    option_d: "Require manual annotation for complex layouts",
    correct_answer: "B",
    explanation: "Citations reference text in extraction order. Complex layouts may have extraction order different from visual order - test with your PDFs.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your app presents citations to compliance auditors. UX best practice:",
    option_a: "Show raw JSON citation data only",
    option_b: "Convert to user-friendly format: clickable page links, highlighted text ranges, source previews",
    option_c: "Hide citations - only log for backend records",
    option_d: "Only show citations for direct quotes, hide others",
    correct_answer: "B",
    explanation: "Convert raw citations to auditor-friendly UI: clickable page numbers, highlighted text, expandable source context - make verification effortless.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Developer wants to customize citation format (e.g., use section numbers instead of pages). Citation formats are:",
    option_a: "Fully customizable via API parameters",
    option_b: "Fixed by document type (pages/chars/blocks) - transform client-side for display",
    option_c: "Customizable only on Enterprise plan",
    option_d: "Customizable through citation templates",
    correct_answer: "B",
    explanation: "Citation formats are fixed by document type. For custom display (section numbers), transform the page/char/block references client-side.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Marketing materials PDF with embedded images. Citations handle:",
    option_a: "Images automatically described and cited with AI vision",
    option_b: "Only text is cited - images skipped in citation tracking",
    option_c: "Images extracted and cited separately",
    option_d: "API returns error if images present",
    correct_answer: "B",
    explanation: "Citations focus on text content. Images in documents are processed by Claude's vision but not separately cited - only text gets citation references.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Architect asks: 'Which citation format is most granular for precise source tracking?' Most granular is:",
    option_a: "Page numbers (PDF) - down to specific pages",
    option_b: "Character indices (text) - exact character positions",
    option_c: "Content blocks (JSON) - logical units",
    option_d: "All equally granular",
    correct_answer: "B",
    explanation: "Character-based text citations are most granular (exact positions). Page citations less granular (entire pages). Block granularity depends on block size.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Bank loan processing: Applicant submits documents as images (scanned forms). To enable Citations, you must:",
    option_a: "Send image files directly - Citations handles automatically",
    option_b: "OCR images to extract text, then include extracted text with Citations",
    option_c: "Enable Enterprise vision citations mode",
    option_d: "Convert images to PDF format first",
    correct_answer: "B",
    explanation: "Citations requires text content. OCR scanned images first to extract text, then provide that text for citation-enabled processing.",
    difficulty: "medium"
  },

  // Document metadata and context field (15 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Financial analyst provides 20 quarterly reports to Claude. For FINRA compliance audit, document metadata serves to:",
    option_a: "Reduce total document file sizes",
    option_b: "Help identify which specific report (Q1-2024, Q2-2024) is cited in analysis",
    option_c: "Improve processing speed by 30%",
    option_d: "Encrypt sensitive financial data",
    correct_answer: "B",
    explanation: "Metadata (especially titles like 'Q1-2024 Report') helps auditors identify which specific document is cited when multiple documents are provided.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your API documentation analyzer includes official docs + internal implementation notes. The 'context' field is for:",
    option_a: "Primary content that will be cited as authoritative source",
    option_b: "Additional background info Claude uses but won't cite as official source",
    option_c: "System instructions and prompts",
    option_d: "Error handling configuration",
    correct_answer: "B",
    explanation: "Context field provides supporting information Claude can use to understand but won't cite as authoritative source - perfect for internal notes.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Compliance review: 10 contracts from different vendors, all titled 'Contract.pdf' in your system. For citation clarity, document titles should be:",
    option_a: "Doesn't matter - titles are optional",
    option_b: "Descriptive and unique (e.g., 'Vendor-Acme-2024-Services-Contract.pdf') to identify sources",
    option_c: "Only important for PDF files",
    option_d: "Required only on Enterprise plan",
    correct_answer: "B",
    explanation: "Descriptive, unique titles (like 'Vendor-Acme-2024-Contract') make citations clear and actionable, especially critical with multiple similar documents.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Technical support chatbot: Official product manual (should be cited) + internal troubleshooting tips (shouldn't be cited as official). Structure as:",
    option_a: "Everything in main content field",
    option_b: "Product manual in main content (citable), troubleshooting tips in context field (not cited)",
    option_c: "Everything in context field",
    option_d: "Make two separate API calls",
    correct_answer: "B",
    explanation: "Official manual goes in main content (citable source), internal tips in context field (helps Claude understand but won't be cited as official).",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Developer asks: 'Can Claude use information from the context field in responses?' Answer:",
    option_a: "No - context field is completely ignored",
    option_b: "Yes - Claude uses it for understanding but it won't appear in citations",
    option_c: "Only on Enterprise plan",
    option_d: "Only if explicitly referenced in prompt",
    correct_answer: "B",
    explanation: "Claude uses context field information to inform responses and understanding, but this content won't be cited as authoritative source.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Engineering team asks which metadata fields are most critical for Citations. Priority metadata:",
    option_a: "File size and creation timestamp",
    option_b: "Title and document type (PDF/text/custom) for source identification",
    option_c: "Author name and version number",
    option_d: "All metadata equally important",
    correct_answer: "B",
    explanation: "Title and document type are most critical - help identify which source is cited. Other metadata useful but less critical for citation functionality.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Software documentation updates monthly (v1.0, v1.1, v1.2). Citations reference specific versions. Best practice for metadata:",
    option_a: "No action - Claude tracks versions automatically",
    option_b: "Include version in title/metadata (e.g., 'API-Docs-v1.2-Jan-2024') for audit trail",
    option_c: "Only needed on Enterprise plan",
    option_d: "Only necessary for PDF documents",
    correct_answer: "B",
    explanation: "Include version information in titles/metadata so citations clearly reference which version was used - critical when docs change over time.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "CFO analyzes API costs: 100K tokens in main content, 20K tokens in context field per request. Token billing for context field:",
    option_a: "Context field tokens are free (not billed)",
    option_b: "Context field tokens billed identically to content tokens (120K total billed)",
    option_c: "Context field tokens billed at 2x rate (140K effective)",
    option_d: "Context field gets 50% discount (110K effective)",
    correct_answer: "B",
    explanation: "Context field tokens are billed identically to main content tokens. The distinction is citation behavior, not cost.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Batch processing: 10 documents provided without titles. Citations in output show:",
    option_a: "Claude generates descriptive titles automatically",
    option_b: "Generic identifiers like 'Document 1', 'Document 2' - harder to interpret",
    option_c: "Citations fail entirely without titles",
    option_d: "File paths used as default titles",
    correct_answer: "B",
    explanation: "Without titles, citations use generic identifiers (Document 1, 2, 3) making them less actionable. Always provide descriptive titles.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Research pipeline processes 50 academic papers. Best practice for metadata structure:",
    option_a: "Identical metadata for all papers to simplify processing",
    option_b: "Unique, descriptive metadata per paper (author, journal, year) to distinguish sources",
    option_c: "Omit metadata to save 5K tokens",
    option_d: "Only provide metadata for longest paper",
    correct_answer: "B",
    explanation: "Unique metadata per document (e.g., 'Smith-2023-Nature-Cancer-Research') makes citations clear and actionable when working with many papers.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Data analyst asks if context field can contain JSON structured data. Context field supports:",
    option_a: "Only plain text format",
    option_b: "Any format main content supports - including JSON, XML, etc.",
    option_c: "Only on Enterprise plan",
    option_d: "Only if under 1K tokens",
    correct_answer: "B",
    explanation: "Context field accepts any format main content supports (text, JSON, XML, etc.). Only difference: content won't be cited as authoritative source.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Debug session: Citations pointing to wrong document. Document metadata helps debugging by:",
    option_a: "Metadata doesn't help with debugging",
    option_b: "Descriptive titles make it easy to identify which document has citation issues",
    option_c: "Automatically fixes citation errors",
    option_d: "Only helps in development mode",
    correct_answer: "B",
    explanation: "Good metadata (descriptive titles) makes debugging much easier - quickly identify which specific document has citation problems.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "System design: Planning context field capacity. Maximum recommended size:",
    option_a: "Hard limit of 1K tokens",
    option_b: "Limited only by total 200K context window (minus main content)",
    option_c: "Hard limit of 10K tokens",
    option_d: "Context field discouraged - use sparingly",
    correct_answer: "B",
    explanation: "Context field limited only by total context window capacity. Use judiciously since it consumes tokens but isn't citable.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Prompt engineer wants to put system instructions like 'be concise' in context field. Correct approach:",
    option_a: "Yes - always use context field for instructions",
    option_b: "No - use dedicated 'system' parameter for instructions, not context field",
    option_c: "Only for instructions under 100 tokens",
    option_d: "Only when Citations enabled",
    correct_answer: "B",
    explanation: "System instructions belong in the system parameter, not context field. Context field is for document-related background information.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Enterprise compliance: Context field contains preliminary analysis notes (confidential). These notes will:",
    option_a: "Appear in citations if Claude uses them",
    option_b: "Never appear in citations - only influence Claude's understanding",
    option_c: "Appear in citations only on Enterprise plan",
    option_d: "Require explicit tagging to exclude from citations",
    correct_answer: "B",
    explanation: "Context field content never appears in citations regardless of how Claude uses it - perfect for confidential notes that inform understanding.",
    difficulty: "medium"
  },

  // Source provenance tracking (15 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Pharmaceutical research: FDA audit asks 'prove this drug interaction claim came from clinical trials, not AI knowledge'. Source provenance means:",
    option_a: "Server location where documents are stored",
    option_b: "Origin and history of information - tracing claims back to specific trial documents",
    option_c: "File format of clinical trial documents",
    option_d: "API cost of processing trial data",
    correct_answer: "B",
    explanation: "Provenance = origin trail. For FDA, proving the drug claim traces to specific clinical trial documents, not AI general knowledge.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Bank implements AI loan decisioning. OCC regulators require proving every decision traces to approved policy documents. Provenance tracking critical for:",
    option_a: "Reducing API costs per loan application",
    option_b: "Compliance auditing, regulatory verification, proving decisions from approved sources",
    option_c: "Improving loan decision speed",
    option_d: "Increasing context window for larger applications",
    correct_answer: "B",
    explanation: "For banking regulators, provenance proves every decision traces to approved policy documents - essential for compliance and auditing.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Healthcare system must prove treatment recommendations come from approved medical literature for malpractice defense. Citations support provenance by:",
    option_a: "Permanently storing medical literature documents",
    option_b: "Providing traceable references to specific pages/sections in medical literature",
    option_c: "Encrypting source attribution information",
    option_d: "Generating unique document IDs for tracking",
    correct_answer: "B",
    explanation: "Citations create provenance trail with traceable references to specific medical literature pages - defendable in malpractice cases.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "SOC2 audit: Auditor asks 'show me complete provenance for AI decisions made in Q4 2024'. Your logging should capture:",
    option_a: "Only final AI responses",
    option_b: "Full request (documents + prompts), response, citations, document metadata, timestamps",
    option_c: "Only error logs",
    option_d: "Only document titles used",
    correct_answer: "B",
    explanation: "Complete provenance = full audit trail: requests, documents provided, responses, citation data, metadata. Log everything for compliance.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Medical diagnosis app: Malpractice lawsuit claims AI hallucinated treatment recommendation. Citations help defense prove:",
    option_a: "Citations automatically validate medical accuracy",
    option_b: "Recommendation traced to specific page in peer-reviewed medical literature",
    option_c: "Citations replace need for doctor review",
    option_d: "Patient data was encrypted properly",
    correct_answer: "B",
    explanation: "Citations provide defense evidence: recommendation traces to specific literature page, proving it came from approved medical source, not hallucination.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Multi-turn conversation (20 API calls) builds analysis over time. To maintain provenance across conversation:",
    option_a: "Provenance automatically tracked across calls by Claude",
    option_b: "Store citation logs client-side, maintain association of information with sources across turns",
    option_c: "Provenance resets each call - can't track across conversation",
    option_d: "Only Enterprise accounts support multi-turn provenance",
    correct_answer: "B",
    explanation: "Track provenance across conversation client-side - store which information came from which sources in each turn, building complete audit trail.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Complex agentic workflow: 50-turn conversation with tool use. Context editing removes old tool results after turn 30. Provenance challenge:",
    option_a: "Citations become inaccurate automatically over time",
    option_b: "Removed tool results mean lost provenance - store full history client-side if needed",
    option_c: "Provenance impossible to track in workflows",
    option_d: "Citations disabled automatically after 10 turns",
    correct_answer: "B",
    explanation: "Context editing removes old content from Claude's view but loses provenance trail. Store complete citation history client-side for full audit trail.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Policy manual updates quarterly (v1.0 → v1.1 → v1.2). Provenance for decisions made in Q1 must reference Q1 version. Best practice:",
    option_a: "Citations automatically track document versions",
    option_b: "Include version in document metadata (e.g., 'Policy-Manual-v1.0-Q1-2024') in logs",
    option_c: "Provenance doesn't apply to updated documents",
    option_d: "Previous citations remain valid automatically",
    correct_answer: "B",
    explanation: "Include version in metadata so provenance records show which version was used for each decision - critical for audit trail.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Law firm: Case depends on proving legal advice came from specific precedent cases. Traceable provenance provides:",
    option_a: "Lower API costs for legal research",
    option_b: "Ability to verify advice meets evidentiary standards by citing specific cases and pages",
    option_c: "Faster legal research processing",
    option_d: "Automatic legal compliance certification",
    correct_answer: "B",
    explanation: "Legal provenance allows verification advice meets evidentiary standards - every claim traced to specific authoritative legal sources (cases, pages).",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Customer-facing app: Transparency requirement shows users where AI got information. Display provenance by:",
    option_a: "Don't show - keep internal only",
    option_b: "Show citation data with clickable links to source documents/pages",
    option_c: "Only show to admin users",
    option_d: "Provenance is automatic and invisible",
    correct_answer: "B",
    explanation: "Display provenance to users with clickable citations linking to source documents/pages - builds trust and transparency.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Investment research synthesizes 10 analyst reports with conflicting price targets. Provenance best practice:",
    option_a: "Only cite the primary (first) source",
    option_b: "Cite all relevant sources for each claim, showing which reports support which targets",
    option_c: "Avoid multi-source responses to simplify provenance",
    option_d: "Combine sources into single citation",
    correct_answer: "B",
    explanation: "Cite all relevant sources showing which reports support which claims - complete provenance reveals conflicts and allows independent verification.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "QA review: AI makes factual claim but citations show no source attribution. This indicates:",
    option_a: "Citations feature is broken",
    option_b: "Potential hallucination - claim lacks document source despite grounding being enabled",
    option_c: "Normal behavior - some claims don't need citations",
    option_d: "Only problematic for numerical claims",
    correct_answer: "B",
    explanation: "With document grounding enabled, unsourced claims may indicate hallucination - responses should trace to documents. Flag for review.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Enterprise security team: Provenance logs contain sensitive data. Recommended approach:",
    option_a: "Combine provenance with general application logs",
    option_b: "Maintain separate provenance logs with specialized access controls for auditing",
    option_c: "Only Enterprise accounts need provenance logs",
    option_d: "Provenance logging unnecessary",
    correct_answer: "B",
    explanation: "Separate provenance logs with specialized access controls allow focused auditing without exposing sensitive data in general logs.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Healthcare org (HIPAA): Provenance records for patient diagnosis must be retained for malpractice statute of limitations. Retention period:",
    option_a: "24 hours minimum",
    option_b: "Based on HIPAA requirements and state medical malpractice laws (typically 7-10 years)",
    option_c: "1 week minimum",
    option_d: "Indefinite retention required",
    correct_answer: "B",
    explanation: "Retention based on regulations: HIPAA + state medical malpractice statutes typically require 7-10 years. Consult legal team for your jurisdiction.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your team spent 2 months building custom citation system (70% recall). Claude's Citations provides 85% recall out-of-box. Key difference:",
    option_a: "Custom implementations always outperform",
    option_b: "Citations provides 15% better recall with zero implementation effort",
    option_c: "Citations only works for PDF documents",
    option_d: "No measurable difference in practice",
    correct_answer: "B",
    explanation: "Citations provides significantly better recall (15% improvement) with zero custom implementation - built-in feature beats custom systems.",
    difficulty: "medium"
  },

  // Citations vs structured outputs (10 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Financial data extraction: Enable both Citations (for audit trail) and strict JSON schema (for database insertion). Result:",
    option_a: "Works perfectly - both features enabled together",
    option_b: "API returns 400 Bad Request - features conflict, cannot use simultaneously",
    option_c: "Works only on Enterprise plan",
    option_d: "Works with special dual-mode configuration",
    correct_answer: "B",
    explanation: "Citations and strict JSON schema mode are incompatible - API returns 400 error. Must choose one approach or find workaround.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Technical reason Citations conflicts with strict JSON schema:",
    option_a: "Temporary API bug being fixed",
    option_b: "Citation metadata doesn't fit strict schema constraints - schemas require exact structure",
    option_c: "JSON mode disables all advanced features",
    option_d: "Incompatible token encoding formats",
    correct_answer: "B",
    explanation: "Citations adds variable metadata structure that can't conform to strict predefined JSON schemas requiring exact formats.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "E-commerce product data pipeline needs structured JSON for inventory system AND source citations for product claims (legal compliance). Solution:",
    option_a: "Enable Citations, accept approximate JSON format",
    option_b: "Use non-strict JSON mode (request JSON in prompt) with custom citation implementation",
    option_c: "Alternate between modes: Citations request, then JSON request",
    option_d: "Enterprise dual-mode API supports both",
    correct_answer: "B",
    explanation: "Best approach: non-strict JSON (prompt-based) with custom citation tracking, or make two calls (Citations first, JSON second based on cited content).",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Can you request JSON output format with Citations enabled (non-strict mode)?",
    option_a: "Absolutely incompatible",
    option_b: "Yes - request JSON in prompt (non-strict), get JSON content + citation metadata separately",
    option_c: "Only for simple JSON structures",
    option_d: "Only on Enterprise plan",
    correct_answer: "B",
    explanation: "Non-strict JSON (prompt-based) works with Citations - you get JSON content plus separate citation metadata in response.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Trade-off decision: Strict JSON schema guarantees exact format for parser vs Citations provides source verification. Decision criteria:",
    option_a: "Always choose JSON - format more important",
    option_b: "Strict JSON for parser reliability; Citations for compliance/audit requirements - choose based on priority",
    option_c: "Only cost differences matter",
    option_d: "Only performance differences matter",
    correct_answer: "B",
    explanation: "Choose based on priority: strict JSON when parsing reliability is critical, Citations when compliance/audit/verification is critical.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Medical device software (FDA regulated): Source verification for safety recommendations is critical, JSON parsing is secondary. Prioritize:",
    option_a: "Strict JSON schema for reliable parsing",
    option_b: "Citations for FDA audit trail and patient safety verification",
    option_c: "Fastest response time",
    option_d: "Lowest token cost",
    correct_answer: "B",
    explanation: "FDA medical device regulations prioritize safety/verification over parsing convenience - Citations for audit trail is correct choice.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Using non-strict JSON mode with Citations, citation metadata appears:",
    option_a: "Embedded within the JSON structure itself",
    option_b: "As separate metadata structure alongside JSON content in API response",
    option_c: "Incompatible - can't have both",
    option_d: "As JSON comments",
    correct_answer: "B",
    explanation: "Non-strict JSON + Citations: JSON content and citation metadata are separate structures in API response - parse both independently.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Backend engineer asks if citation metadata structure is consistent for validation. Citation metadata:",
    option_a: "Completely unstructured - no validation possible",
    option_b: "Has consistent, documented schema for validation - just separate from content schema",
    option_c: "Only Enterprise accounts get structured citations",
    option_d: "Only PDF citations have structure",
    correct_answer: "B",
    explanation: "Citation metadata has well-defined, consistent schema you can validate - it's just separate from strict content JSON schema mode.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Workaround for application requiring both strict JSON formatting AND citations:",
    option_a: "Impossible - no workaround exists",
    option_b: "Two API calls: first with Citations (get cited content), second with JSON schema (format cited content)",
    option_c: "Enterprise-only dual mode feature",
    option_d: "Use XML instead of JSON",
    correct_answer: "B",
    explanation: "Workaround: Make two calls - Citations call for sourced content, then JSON schema call to format that content strictly. Adds cost but achieves both goals.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Error handling: Citations mode vs strict JSON mode have different failure patterns. Citations mode should handle:",
    option_a: "Identical error handling for both modes",
    option_b: "Citation-specific errors: missing citations, invalid source references, grounding failures",
    option_c: "JSON validation errors only",
    option_d: "No difference in error handling",
    correct_answer: "B",
    explanation: "Citations mode: handle citation-specific errors (missing citations, invalid references). JSON mode: handle schema validation errors. Different error patterns.",
    difficulty: "medium"
  },

  // Best practices and accuracy (10 questions)
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Your custom prompt 'Please cite page numbers for claims' achieves 70% citation accuracy. Switching to Citations API provides:",
    option_a: "Same 70% - no improvement",
    option_b: "85% accuracy (15% better recall) plus structured, machine-readable citations",
    option_c: "Marginal 2% improvement",
    option_d: "100% accuracy guaranteed",
    correct_answer: "B",
    explanation: "Citations provides 15% better recall (70% → 85%) plus structured format that's easier to parse and validate vs. text-based citations.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Document prep: Mix of well-formatted PDFs and poorly scanned images without OCR. For optimal citation accuracy:",
    option_a: "Merge all into single document",
    option_b: "OCR scanned images, ensure all docs have extractable text and clear structure",
    option_c: "Convert everything to plain text, removing formatting",
    option_d: "Split into exactly 1K token chunks",
    correct_answer: "B",
    explanation: "OCR scanned documents so all have extractable text. Maintain clear structure (headings, sections) - helps Citations generate accurate references.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Processing 50 vendor contracts simultaneously. Best practice for document metadata:",
    option_a: "Identical metadata simplifies processing",
    option_b: "Unique, descriptive metadata per contract (vendor name, date, type) for clear citations",
    option_c: "Omit metadata to save 10K tokens",
    option_d: "Only metadata for longest contract",
    correct_answer: "B",
    explanation: "Unique metadata (e.g., 'Acme-Corp-Services-2024-Q1') makes citations actionable when reviewing 50 contracts - know exactly which contract cited.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "QA process: Validate citation accuracy before production deployment. Implementation:",
    option_a: "Trust Citations completely - no validation needed",
    option_b: "Spot-check sample: manually verify citations point to correct content in source docs",
    option_c: "Citations never need validation",
    option_d: "Only validate on Enterprise accounts",
    correct_answer: "B",
    explanation: "Implement spot-checking: sample requests, manually verify citations match source content. Build confidence in accuracy before full deployment.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Production issue: 20% of citations seem inaccurate or missing. First debugging step:",
    option_a: "Assume model error, file bug report",
    option_b: "Check document quality: scanned PDFs without OCR, corrupt files, poor formatting",
    option_c: "Immediately switch to custom implementation",
    option_d: "Disable Citations feature",
    correct_answer: "B",
    explanation: "First check document quality - scanned PDFs without OCR, poor formatting, complex layouts are common causes. Fix input quality before assuming model issues.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Prompt engineering with Citations enabled. Best practice:",
    option_a: "Explicitly request 'please provide citations' in every prompt",
    option_b: "Citations work automatically - prompt for actual task, citations added automatically",
    option_c: "Avoid mentioning sources in prompts",
    option_d: "Use special citation prompt syntax",
    correct_answer: "B",
    explanation: "With Citations enabled, feature works automatically. Prompt for your task (e.g., 'summarize this contract'), citations added automatically.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Document quality impact on citations: High-quality PDFs (extractable text, clear formatting) vs low-quality scans:",
    option_a: "No relationship between quality and citation accuracy",
    option_b: "High-quality documents enable significantly more accurate citations",
    option_c: "Low-quality documents work better",
    option_d: "Quality only affects processing speed",
    correct_answer: "B",
    explanation: "High-quality documents (extractable text, clear structure) enable precise citations. Poor quality (scanned without OCR, bad formatting) reduces accuracy.",
    difficulty: "easy"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Legacy document archive: 1990s scanned PDFs without OCR. To enable Citations:",
    option_a: "Use as-is - Citations will work",
    option_b: "Pre-process: OCR to extract text, improve formatting before sending to API",
    option_c: "Only process PDFs created after 2010",
    option_d: "Scanned documents don't work with Citations",
    correct_answer: "B",
    explanation: "Pre-process legacy documents: OCR to extract text, clean up formatting. This investment in quality enables accurate citations.",
    difficulty: "medium"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "Production monitoring: Measure citation accuracy over 10,000 requests. Methodology:",
    option_a: "Impossible to measure at scale",
    option_b: "Random sample (e.g., 100 requests), manually verify citations match source locations, track accuracy %",
    option_c: "Only Enterprise dashboard provides metrics",
    option_d: "Accuracy automatically 100% - no measurement needed",
    correct_answer: "B",
    explanation: "Sample-based validation: randomly select requests, manually verify citations. Track accuracy over time to identify issues or improvement opportunities.",
    difficulty: "hard"
  },
  {
    week: 10,
    domain: "Context Management & Reliability",
    topic: "Advanced Context & Provenance",
    question: "User experience: Present citations to non-technical end users (lawyers, doctors, analysts). Best practice:",
    option_a: "Hide citations - too technical for end users",
    option_b: "User-friendly UI: clickable page numbers, highlighted text, source previews - make verification effortless",
    option_c: "Show raw JSON citation metadata",
    option_d: "Only show citations if user explicitly requests",
    correct_answer: "B",
    explanation: "Build user-friendly citation UI: clickable page links, text highlighting, source previews. Make verification intuitive even for non-technical professionals.",
    difficulty: "easy"
  }
];
