export interface Question {
  week?: number;
  domain: string;
  topic: string;
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_answer: string;
  explanation: string;
  difficulty?: string;
}

export const topic11Questions: Question[] = [
  // Error types and retry logic (20 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your payment processing API gets random 503 Service Unavailable errors from Claude during checkout peaks. To maximize transaction success without wasting money on permanent failures, retry only:",
    option_a: "All HTTP errors including 4xx client and 5xx server",
    option_b: "429 (rate limit) and 5xx (server errors)",
    option_c: "Only 5xx server errors with exponential backoff between attempts",
    option_d: "429 rate limits plus 502/503/504 gateway errors specifically",
    correct_answer: "B",
    explanation: "Retry 429 (rate limit) and 5xx (server errors) as these are typically transient. Do not retry 4xx errors (except 429) as they indicate client-side problems that won't be resolved by retrying.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your document parser sends malformed JSON to Claude API and receives 400 Bad Request. Your retry logic retries 3 times, burning tokens and failing each time. You should:",
    option_a: "Yes, retry with exponential backoff as temporary network issues",
    option_b: "No, 400 indicates client-side problem (invalid JSON) - fix the request",
    option_c: "Yes, but only retry once with request validation enabled",
    option_d: "Retry with circuit breaker pattern to prevent cascading failures",
    correct_answer: "B",
    explanation: "Never retry 400 errors as they indicate client-side problems (invalid request format, parameters, etc.) that won't be resolved by retrying. Fix the request instead.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your chatbot hits 1,000 requests/minute during product launch. Claude API returns 429 status code, meaning:",
    option_a: "Temporary server overload requiring immediate retry with backoff",
    option_b: "Rate limit exceeded - wait and retry",
    option_c: "Authentication failure from expired API key credentials needing refresh",
    option_d: "Request timeout from network latency exceeding threshold limits",
    correct_answer: "B",
    explanation: "429 status code indicates rate limit exceeded. This is a retryable error - wait and retry with exponential backoff, respecting retry-after headers.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API call returns a 503 Service Unavailable. What should you do?",
    option_a: "Fail immediately and notify monitoring systems for investigation",
    option_b: "Retry with exponential backoff",
    option_c: "Switch to alternative model tier like Haiku for degraded",
    option_d: "Queue request for later processing when service recovers",
    correct_answer: "B",
    explanation: "503 is a server-side error indicating temporary unavailability. Retry with exponential backoff as the service will likely recover.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Black Friday traffic causes 429 rate limit errors. Response header shows 'retry-after: 30'. Your exponential backoff would retry after 1 second. Best strategy:",
    option_a: "Retry using exponential backoff ignoring retry-after for faster recovery",
    option_b: "Respect retry-after header (wait 30s) and use exponential backoff for subsequent retries",
    option_c: "Use whichever is shorter between retry-after and calculated backoff",
    option_d: "Apply jitter to retry-after value for distributed load patterns",
    correct_answer: "B",
    explanation: "For 429 errors, respect the retry-after header if provided, and use exponential backoff. This prevents overwhelming the system while ensuring requests eventually succeed.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "You receive a 401 Unauthorized error. What's the appropriate action?",
    option_a: "Retry with API key rotation to alternate credentials automatically",
    option_b: "Fix authentication (API key) - do not retry",
    option_c: "Retry once with cached authentication token before failing permanently",
    option_d: "Switch to backup regional endpoint with same credentials temporarily",
    correct_answer: "B",
    explanation: "401 indicates an authentication problem (invalid or missing API key). Don't retry - fix the authentication issue. Retrying won't help and wastes resources.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production SaaS uses Anthropic Python SDK with default configuration. During a 503 outage, requests succeed after automatic retries. This works because SDKs use:",
    option_a: "Linear backoff with 2-second intervals between retry attempts",
    option_b: "Exponential backoff with jitter for retryable errors",
    option_c: "Constant backoff delays with decorrelated jitter for distribution",
    option_d: "Adaptive backoff based on server response latency metrics",
    correct_answer: "B",
    explanation: "Anthropic Python and Node.js SDKs automatically implement exponential backoff with jitter for retryable errors (429, 5xx), which is the recommended approach.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API call returns a 400 error saying the request exceeds token limits. What should you do?",
    option_a: "Retry with prompt caching enabled to reduce token consumption",
    option_b: "Modify or split the request - do not retry",
    option_c: "Wait for context window expansion then retry unchanged request",
    option_d: "Retry with compression enabled to fit within token limits",
    correct_answer: "B",
    explanation: "Token limit errors (400) are client-side errors requiring request modification (reduce content, split into multiple requests). Retrying without changes won't help.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production app uses the official Anthropic Python SDK. During a 502 outage, which SDK provides built-in retry logic with exponential backoff?",
    option_a: "Only third-party community-maintained wrapper libraries for Python and Node",
    option_b: "Anthropic Python and Node.js SDKs",
    option_c: "All language SDKs including Java, Go, and Rust officially",
    option_d: "Only Enterprise tier SDKs with premium support subscriptions",
    correct_answer: "B",
    explanation: "Both Anthropic Python and Node.js SDKs provide built-in retry logic with exponential backoff for retryable errors, eliminating the need for custom retry implementation.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your monitoring dashboard shows: 4xx errors (401, 400) = 50/hour, 5xx errors (503, 502) = 5/hour. The difference indicates:",
    option_a: "Both 4xx and 5xx errors equally retryable with backoff",
    option_b: "Retryable errors (5xx) are transient; non-retryable (4xx) need fixes",
    option_c: "Only 500 Internal Server errors retryable not 502/503/504",
    option_d: "All 4xx errors except 401 are retryable with authentication",
    correct_answer: "B",
    explanation: "Retryable errors (429, 5xx) are transient and may succeed on retry. Non-retryable errors (most 4xx) indicate client-side problems requiring fixes, not retries.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your application receives intermittent 502 Bad Gateway errors. What's the best strategy?",
    option_a: "Fail immediately for all 502 errors",
    option_b: "Implement retry with exponential backoff",
    option_c: "Log and ignore these errors",
    option_d: "Switch APIs permanently",
    correct_answer: "B",
    explanation: "502 is a transient server-side error. Implement retry with exponential backoff - these errors typically resolve quickly and requests succeed on retry.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your error logs show: 95% of 429 errors succeed on retry, but 100% of 400 errors fail even after 3 retries. The documented exception to the 4xx no-retry rule is:",
    option_a: "All 4xx errors should be retried",
    option_b: "429 (rate limit) is retryable despite being 4xx",
    option_c: "There are no exceptions",
    option_d: "Only 404 errors are exceptions",
    correct_answer: "B",
    explanation: "429 is the main documented exception to the 4xx no-retry rule. It's a client-side status code but indicates a transient condition (rate limiting) that resolves over time.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API call times out after 60 seconds. Network logs show request sent but no response received. You should:",
    option_a: "Never retry timeouts",
    option_b: "Retry with backoff, but be cautious of idempotency",
    option_c: "Only retry for GET requests",
    option_d: "Increase timeout and retry immediately",
    correct_answer: "B",
    explanation: "Retry timeouts with exponential backoff, but be cautious about idempotency - ensure retrying doesn't cause duplicate processing. Consider whether the original request might have succeeded.",
    difficulty: "hard"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your retry logic retries all errors (4xx, 5xx) indiscriminately. Monthly costs increased 30% from retrying 400, 401, 404 errors that never succeed. The error handling pattern to avoid is:",
    option_a: "Exponential backoff",
    option_b: "Retrying all errors without discrimination",
    option_c: "Using SDK defaults",
    option_d: "Logging errors",
    correct_answer: "B",
    explanation: "Avoid retrying all errors indiscriminately. This wastes resources on non-retryable errors (4xx) and can create cascading failures. Only retry appropriate errors (429, 5xx).",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API key has been rotated but the application still uses the old one. What error do you expect?",
    option_a: "429 Rate Limit",
    option_b: "401 Unauthorized",
    option_c: "500 Internal Server Error",
    option_d: "400 Bad Request",
    correct_answer: "B",
    explanation: "An invalid or expired API key results in 401 Unauthorized. This is a non-retryable error - update the API key configuration.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production system retries 429 errors with: 1st retry after 1s, 2nd after 2s, 3rd after 4s. After 3 retries, 503 errors still fail. Best practice is to implement:",
    option_a: "Unlimited retries",
    option_b: "3-5 retries with exponential backoff",
    option_c: "Always exactly 3 retries",
    option_d: "Never retry",
    correct_answer: "B",
    explanation: "Typically implement 3-5 retries with exponential backoff. This balances giving transient errors time to resolve while avoiding excessive waiting for persistent failures.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your error tracking shows: Attempt 1 failed (503), Attempt 2 failed (503), Attempt 3 succeeded. To debug these retry patterns, you should:",
    option_a: "Don't log retries",
    option_b: "Log each attempt with context (attempt number, error, backoff duration) for debugging",
    option_c: "Only log final failure",
    option_d: "Only log successful retries",
    correct_answer: "B",
    explanation: "Log each retry attempt with context (attempt number, error, backoff duration) for debugging. This helps identify patterns and optimize retry strategies.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API consistently fails after 5 retry attempts with 503 errors for 10 minutes straight. After maximum retries, you should:",
    option_a: "Retry indefinitely",
    option_b: "Return error, log for investigation, consider fallback strategies (circuit breaker)",
    option_c: "Silently drop the request",
    option_d: "Immediately switch APIs",
    correct_answer: "B",
    explanation: "After maximum retries fail, return an error to the caller, log comprehensively for investigation, and consider fallback strategies (cached responses, degraded service, circuit breaker).",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production system uses Anthropic SDK with default 3 retries. For a critical financial app, you need 5 retries. Can you customize this?",
    option_a: "No, SDK behavior is fixed",
    option_b: "Yes, SDKs allow customizing retry strategies",
    option_c: "Only for Enterprise accounts",
    option_d: "Only by forking the SDK",
    correct_answer: "B",
    explanation: "Anthropic SDKs allow customizing retry strategies (max attempts, backoff parameters), but start with SDK defaults and only customize if you have specific requirements.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your Black Friday monitoring shows: 10,000 requests hit 429 simultaneously → all retry after 1 second → 10,000 requests hit 429 again. This retry storm demonstrates the main risk of aggressive retry strategies:",
    option_a: "Lower accuracy",
    option_b: "Thundering herd and cascading failures",
    option_c: "Higher costs",
    option_d: "Slower initial response",
    correct_answer: "B",
    explanation: "Aggressive retries (immediate, no backoff, too many clients) can cause thundering herd problems and cascading failures, overwhelming systems during recovery and prolonging outages.",
    difficulty: "hard"
  },

  // Exponential backoff and jitter (15 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Black Friday traffic causes retry storms - each failed request retries immediately, overwhelming the API. Your $5,000 Claude bill shows 80% retry costs. Implement exponential backoff starting at 1s, doubling each attempt, to:",
    option_a: "Maintain constant 1-second intervals between all retry attempts uniformly",
    option_b: "Double wait time with each retry (1s, 2s, 4s, 8s)",
    option_c: "Increase linearly with each attempt using arithmetic progression intervals",
    option_d: "Use adaptive delays based on real-time server load metrics",
    correct_answer: "B",
    explanation: "Exponential backoff doubles the wait time with each retry attempt (e.g., 1s, 2s, 4s, 8s), allowing more time for transient issues to resolve while preventing system overload.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your retry logic starts with a base delay for exponential backoff. Industry best practice recommends starting at:",
    option_a: "500 milliseconds for fast recovery with minimal user impact",
    option_b: "1 second",
    option_c: "2 seconds to balance responsiveness with system recovery time",
    option_d: "3 seconds to allow adequate server recovery before retrying",
    correct_answer: "B",
    explanation: "The recommended base delay is 1 second. This provides a reasonable starting point that doubles to 2s, 4s, 8s, etc., balancing responsiveness with giving errors time to resolve.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your 10,000 concurrent users all hit 503 errors at exactly 2:00 PM. All retry at exactly 2:00:01 PM (1s backoff). All hit 503 again. This thundering herd is prevented by adding jitter, which is:",
    option_a: "Network latency variations from distributed geographic server locations",
    option_b: "Random variation added to backoff delays",
    option_c: "Clock skew compensation for distributed timestamp synchronization issues",
    option_d: "Maximum retry attempt ceiling to prevent infinite backoff growth",
    correct_answer: "B",
    explanation: "Jitter is random variation added to backoff delays to prevent many clients from retrying simultaneously (thundering herd), distributing retry load over time.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production monitoring shows: Without jitter, 5,000 requests retry simultaneously causing cascading failures. With jitter, retries spread over 4 seconds, all succeed. Jitter is important because:",
    option_a: "Makes retry timing predictable for monitoring and alerting systems",
    option_b: "It prevents thundering herd by distributing retries",
    option_c: "Reduces overall wait time by optimizing retry timing dynamically",
    option_d: "Required by API specification to prevent client-side rate limiting",
    correct_answer: "B",
    explanation: "Jitter prevents thundering herd problems where many clients retry simultaneously, overwhelming the recovering service. It distributes retry attempts over time.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your backoff algorithm calculates 4 second delay. Full jitter implementation randomly selects the actual delay as:",
    option_a: "Fixed 4-second delay with ±100ms tolerance for precision",
    option_b: "Random value between 0 and 4 seconds",
    option_c: "Decorrelated jitter between 2 and 6 seconds centered",
    option_d: "Equal jitter applying ±25% variance producing 3 to 5",
    correct_answer: "B",
    explanation: "Full jitter selects a random value between 0 and the calculated exponential backoff time (e.g., for 4s backoff, randomly choose between 0-4s), providing maximum distribution of retries.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your retry logic implements exponential backoff with 1s base delay. Over 4 retries, the delays are approximately:",
    option_a: "1s, 1.5s, 2.25s, 3.375s using multiplicative factor of 1.5",
    option_b: "1s, 2s, 4s, 8s",
    option_c: "1s, 3s, 9s, 27s using triple multiplication progression",
    option_d: "1s, 2s, 3s, 4s using linear arithmetic sequence addition",
    correct_answer: "B",
    explanation: "With 1s base and exponential backoff, delays double each time: 1s, 2s, 4s, 8s. This is before jitter is applied.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your document processing pipeline retries failed requests with 1s base backoff. Over 3 retries, the total maximum wait time (sum of delays) is:",
    option_a: "3 seconds",
    option_b: "7 seconds (1s + 2s + 4s)",
    option_c: "15 seconds",
    option_d: "30 seconds",
    correct_answer: "B",
    explanation: "With 1s base and 3 retries: 1s + 2s + 4s = 7 seconds total maximum wait time (before jitter). This is the sum of all retry delays.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production app needs retry logic. The Anthropic SDK already implements exponential backoff with jitter correctly. You should:",
    option_a: "Yes, always implement custom backoff",
    option_b: "No, use SDK defaults which implement it correctly",
    option_c: "Only for production environments",
    option_d: "Only for Enterprise accounts",
    correct_answer: "B",
    explanation: "Use SDK defaults which implement exponential backoff with jitter correctly. Only implement custom backoff if you have specific requirements the SDK doesn't meet.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your retry implementation uses exponential backoff (1s, 2s, 4s, 8s) WITHOUT jitter. During a 503 outage, 5,000 concurrent users all retry at exactly the same time. The risk is:",
    option_a: "Too slow retries",
    option_b: "Thundering herd - all clients retry simultaneously",
    option_c: "Higher API costs",
    option_d: "Lower success rates",
    correct_answer: "B",
    explanation: "Without jitter, all clients experiencing the same error wait identical times and retry simultaneously, creating thundering herd problems that can overwhelm the recovering service.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your exponential backoff calculates delays: 1s, 2s, 4s, 8s, 16s, 32s, 64s. The 64-second delay feels excessive for your use case. You should:",
    option_a: "No, let it grow indefinitely",
    option_b: "Yes, cap at a reasonable maximum like 60 seconds",
    option_c: "Only cap for Enterprise accounts",
    option_d: "Only cap during peak hours",
    correct_answer: "B",
    explanation: "Cap maximum backoff delay at a reasonable limit (e.g., 60 seconds) to prevent excessively long waits while still providing adequate spacing between retries.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API returns 429 with header 'retry-after: 45'. Your exponential backoff calculates 8 seconds. Best practice is to:",
    option_a: "Ignore retry-after and use only backoff (8s)",
    option_b: "Use retry-after if provided (45s), otherwise use backoff",
    option_c: "Use whichever is longer (45s)",
    option_d: "Retry-after disables backoff",
    correct_answer: "B",
    explanation: "Respect the retry-after header if provided (especially for 429 errors), as it tells you exactly when to retry. Fall back to exponential backoff if no header is present.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your chatbot uses fixed 5-second delays between retries. During peak traffic, 80% of retries fail. Switching to exponential backoff (1s, 2s, 4s, 8s) improves success to 95% because:",
    option_a: "Simpler to implement",
    option_b: "Adapts to issue severity - gives more time for persistent problems",
    option_c: "Always faster",
    option_d: "Uses less memory",
    correct_answer: "B",
    explanation: "Exponential backoff adapts to issue severity - quick retries for transient issues, longer delays for persistent problems. This is more efficient than fixed delays which don't adapt.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production API serves 1000 concurrent clients. All hit 429 rate limits simultaneously. Without jitter, what does exponential backoff prevent?",
    option_a: "Individual failures",
    option_b: "All 1000 clients retrying at exactly the same time (distributes over the backoff window)",
    option_c: "Rate limit errors",
    option_d: "Network congestion",
    correct_answer: "B",
    explanation: "Jitter prevents all 1000 clients from retrying at exactly the same time, which would immediately hit rate limits again. It distributes retries over the backoff window.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your exponential backoff sequence: 1s, 2s, 4s, 8s, 16s, 32s, 64s. For user experience, you want to cap delays. Industry best practice caps at:",
    option_a: "5 seconds",
    option_b: "30-60 seconds",
    option_c: "5 minutes",
    option_d: "No cap needed",
    correct_answer: "B",
    explanation: "A typical maximum cap is 30-60 seconds. This prevents excessive waiting while still providing adequate spacing. The exact value depends on your application's timeout tolerance.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your SDK documentation says 'implements full jitter'. In code, for a calculated 8s backoff, the actual wait time will be:",
    option_a: "Add a fixed 500ms to 8s",
    option_b: "Random value between 0 and 8 seconds",
    option_c: "Add random ±10% to 8s (7.2-8.8s)",
    option_d: "Only apply jitter to first retry",
    correct_answer: "B",
    explanation: "Best practice is full jitter: select a random value between 0 and the calculated exponential backoff time. This provides maximum distribution and prevents thundering herd.",
    difficulty: "medium"
  },

  // Rate limiting and overload handling (15 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your app sends 5,000 requests/hour to Claude API. Rate limit is 3,000/hour. You implement client-side rate limiting at 3,000/hour to prevent 429 errors before they occur. This is:",
    option_a: "Server-side enforcement using API gateway throttling mechanisms automatically",
    option_b: "Client controls its own request rate to stay within limits",
    option_c: "Distributed rate limiting across multiple backend server instances",
    option_d: "Dynamic throttling based on real-time server capacity metrics",
    correct_answer: "B",
    explanation: "Client-side rate limiting means the client proactively controls its request rate to stay within known limits, preventing server-side rate limit errors before they occur.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production app experiences 429 rate limit errors 500 times/day, causing retries and user delays. Implementing client-side rate limiting proactively prevents errors and improves:",
    option_a: "Required by API terms of service for production deployments",
    option_b: "Prevents rate limit errors (429) and improves reliability",
    option_c: "Reduces token consumption costs through request batching optimization",
    option_d: "Improves response accuracy by allowing better model resource allocation",
    correct_answer: "B",
    explanation: "Client-side rate limiting prevents rate limit errors before they occur, improving reliability and user experience by avoiding error-retry cycles.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API returns 529 Overloaded errors during peak hours. To maximize success while allowing system recovery, you should:",
    option_a: "Fail immediately and alert operations team for manual intervention",
    option_b: "Retry with backoff, consider fallback to alternative models",
    option_c: "Switch to multi-region deployment across US-EAST and EU-WEST",
    option_d: "Queue requests for delayed processing when capacity available",
    correct_answer: "B",
    explanation: "For overload errors, retry with exponential backoff to allow the system to recover. Consider fallback to alternative models or cached responses if overload persists.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API receives 429 with header 'retry-after: 60'. This retry-after header tells you:",
    option_a: "Detailed error diagnostics for debugging rate limit violations",
    option_b: "Wait 60 seconds before retrying",
    option_c: "API version compatibility and deprecation notice information urgently",
    option_d: "Current rate limit quota consumption and remaining capacity",
    correct_answer: "B",
    explanation: "Retry-after headers tell you exactly how long to wait before retrying, often provided with 429 rate limit responses. Always respect these headers.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your application sends 100 requests/minute but the limit is 60/minute. To prevent 429 errors, you should:",
    option_a: "Send all 100 requests with exponential backoff handling errors",
    option_b: "Implement client-side rate limiting at 60/minute",
    option_c: "Add random jitter delays between requests for distribution",
    option_d: "Reduce to 50 requests per minute maintaining safety buffer",
    correct_answer: "B",
    explanation: "Implement client-side rate limiting at exactly 60 requests/minute. This prevents rate limit errors while maximizing your allowed throughput.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your monitoring shows 429 errors with retry-after headers averaging 45 seconds. Ignoring these headers and retrying after 1 second causes extended rate limiting. You should:",
    option_a: "No, they're just suggestions",
    option_b: "Yes, always respect them to avoid continued rate limiting",
    option_c: "Only for Enterprise accounts",
    option_d: "Only if they're under 10 seconds",
    correct_answer: "B",
    explanation: "Always respect retry-after headers. They provide authoritative information about when you can retry without continued rate limiting. Ignoring them can lead to extended rate limiting.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your app uses a token bucket algorithm: bucket holds 60 tokens, refills at 1 token/second. Each request consumes 1 token. This allows bursts of 60 requests while maintaining 60/minute average. The algorithm is used for:",
    option_a: "Token counting",
    option_b: "Client-side rate limiting with burst handling",
    option_c: "Caching tokens",
    option_d: "Error detection",
    correct_answer: "B",
    explanation: "Token bucket algorithm is a common pattern for client-side rate limiting that allows controlled bursts while maintaining average rate limits over time.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API experiences sustained 529 Overloaded errors for 30 minutes. Retrying indefinitely wastes resources. Best practice for sustained overload is:",
    option_a: "Keep retrying indefinitely",
    option_b: "Implement fallback strategies (cached responses, degraded service, circuit breaker)",
    option_c: "Give up immediately",
    option_d: "Double the request rate",
    correct_answer: "B",
    explanation: "For sustained overload, implement fallback strategies like serving cached responses, degraded service with simpler models, or circuit breakers to prevent cascading failures.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your system architecture: client-side rate limiting prevents 429 errors proactively, exponential backoff handles errors reactively. The relationship between them is:",
    option_a: "They're the same thing",
    option_b: "Rate limiting is proactive (preventing errors); backoff is reactive (handling errors)",
    option_c: "They're incompatible",
    option_d: "Only use one, not both",
    correct_answer: "B",
    explanation: "Rate limiting is proactive (preventing errors), while exponential backoff is reactive (handling errors). Use both: rate limiting to minimize errors, backoff to handle any that occur.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your dashboard tracks: requests sent: 55,000/hour, rate limit: 60,000/hour, 429 errors: 0/hour. To optimize and avoid hitting limits, you should monitor:",
    option_a: "It's not possible",
    option_b: "Track requests sent vs limits (currently at 92% capacity), monitor 429 error rates",
    option_c: "Only available in Enterprise dashboards",
    option_d: "Rate limits are unlimited",
    correct_answer: "B",
    explanation: "Monitor rate limit consumption by tracking requests sent against known limits and monitoring 429 error rates. This helps optimize request patterns and avoid limits.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API receives traffic spikes: 10 req/min normally, but 500 req/min during product launches. To handle spikes without 429 errors, implement:",
    option_a: "Sending all requests immediately",
    option_b: "Queueing requests and processing at controlled rate (60/min)",
    option_c: "Randomly dropping requests",
    option_d: "Duplicating all requests",
    correct_answer: "B",
    explanation: "Queue-based rate limiting queues incoming requests and processes them at a controlled rate that stays within limits. This smooths bursts and prevents rate limit errors.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your Black Friday traffic: 1,000 req/min spike vs 60/min limit. To handle gracefully without dropping requests, you should:",
    option_a: "Reject requests during spikes",
    option_b: "Implement queuing with rate limiting (60/min processing) and backpressure (queue limits)",
    option_c: "Process everything and handle errors",
    option_d: "Cache everything permanently",
    correct_answer: "B",
    explanation: "Implement queuing with rate limiting and backpressure to handle spikes gracefully. Queue excess requests and process at sustainable rates, with backpressure to prevent queue overflow.",
    difficulty: "hard"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your monitoring shows 429 error rate increasing: Week 1: 0%, Week 2: 2%, Week 3: 8%, Week 4: 15%. This trend indicates:",
    option_a: "Slower response times",
    option_b: "Approaching or exceeding rate limits - need to adjust request rates",
    option_c: "Lower accuracy",
    option_d: "Higher token costs",
    correct_answer: "B",
    explanation: "An increasing 429 error rate indicates you're approaching or exceeding rate limits. Monitor this metric to adjust request rates proactively.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production app uses Claude Opus (rate limit: 10 req/min) and Claude Haiku (rate limit: 100 req/min). Do rate limits vary by model?",
    option_a: "No, all limits are identical",
    option_b: "Yes, check documentation for specific limits per model/tier",
    option_c: "Only Enterprise has different limits",
    option_d: "Limits don't exist",
    correct_answer: "B",
    explanation: "Rate limits can vary by model, pricing tier, and account type. Check documentation for specific limits and implement appropriate client-side limiting for your configuration.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your monitoring shows 503 errors increasing from 1% to 25% over 5 minutes (system degrading). After 10 consecutive 503s in 30 seconds, your circuit breaker pattern should:",
    option_a: "Continue sending all requests",
    option_b: "Temporarily stop requests (circuit open) to allow recovery, test periodically",
    option_c: "Permanently block all requests",
    option_d: "Randomly sample requests",
    correct_answer: "B",
    explanation: "Circuit breaker pattern temporarily stops requests after repeated failures, giving the system time to recover. After a timeout, it allows test requests to check if service has recovered.",
    difficulty: "hard"
  },

  // Timeout strategies (10 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your customer support chatbot must respond within 10 seconds or users abandon. For simple queries ('What are your hours?'), set timeout to:",
    option_a: "3 seconds for immediate user feedback in chat interfaces",
    option_b: "5-10 seconds",
    option_c: "15 seconds to accommodate p95 latency with safety margin",
    option_d: "30 seconds allowing extended processing for complex queries",
    correct_answer: "B",
    explanation: "For simple chat interactions, 5-10 seconds is appropriate. This balances user experience (not too long to wait) with giving the model time to generate responses.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API processes standard document analysis requests (5-10 page PDFs). Based on testing, 95% complete within 45 seconds. Set timeout to:",
    option_a: "15-20 seconds for quick document processing with user feedback",
    option_b: "30-60 seconds (allows for p95 latency)",
    option_c: "90-120 seconds accommodating complex document analysis with citations",
    option_d: "180 seconds for comprehensive multi-document comparative analysis tasks",
    correct_answer: "B",
    explanation: "For standard API calls with moderate complexity, 30-60 seconds is recommended. This accommodates processing time while preventing indefinite waiting.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your research paper analysis processes 50-page technical papers with complex reasoning. Based on production data, p99 latency is 180 seconds. Set timeout to:",
    option_a: "60 seconds assuming efficient document chunking and parallel processing",
    option_b: "90 seconds for typical research paper length with citations",
    option_c: "2-5 minutes (accommodates complex analysis)",
    option_d: "10 minutes allowing comprehensive multi-stage reasoning with context",
    correct_answer: "C",
    explanation: "Complex analysis tasks (large documents, multi-step reasoning) may require 2-5 minutes. Set timeouts based on task complexity and acceptable user wait times.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API processes: simple queries (5s timeout), standard analysis (60s timeout), complex reports (300s timeout). Varying timeouts by task complexity:",
    option_a: "No, use a fixed timeout for all requests",
    option_b: "Yes, set timeouts based on expected task complexity",
    option_c: "Only vary for Enterprise accounts",
    option_d: "Timeouts aren't necessary",
    correct_answer: "B",
    explanation: "Vary timeouts based on task complexity: shorter for simple chat (5-10s), longer for complex analysis (2-5min). This optimizes both user experience and resource usage.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API call times out after 60 seconds. Request might have succeeded but response was delayed. When treating timeouts as errors, you should:",
    option_a: "Immediately retry with the same timeout",
    option_b: "Consider it a retryable error with exponential backoff, but be cautious about idempotency",
    option_c: "Never retry timeouts",
    option_d: "Double the timeout and retry immediately",
    correct_answer: "B",
    explanation: "Treat timeouts as potentially retryable errors with exponential backoff, but be cautious about idempotency. Consider whether the request might have succeeded but response was delayed.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Users complain responses take 8 seconds (timeout 10s). You have options: reduce timeout to 5s, analyze root causes, enable streaming, optimize prompts. Best approach:",
    option_a: "Reduce timeout to 2 seconds",
    option_b: "Analyze root causes: Are tasks too complex? Would streaming help? Can prompts be optimized?",
    option_c: "Increase timeout to 30 seconds",
    option_d: "Remove timeouts entirely",
    correct_answer: "B",
    explanation: "Rather than just adjusting timeouts, analyze root causes: Are tasks too complex? Would streaming improve perceived performance? Can prompts be optimized? Address underlying issues, not just symptoms.",
    difficulty: "hard"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your retry logic: Request 1 times out (60s) → waits 1s → Request 2 times out (60s) → waits 2s → Request 3 succeeds (45s). Total time: 60+1+60+2+45=168s. The relationship between timeouts and backoff:",
    option_a: "They're unrelated",
    option_b: "Total time including retries can exceed individual timeout",
    option_c: "Backoff resets timeout",
    option_d: "Timeouts disable backoff",
    correct_answer: "B",
    explanation: "Individual requests have timeouts, but total time including retries and backoff delays can be much longer. Set overall operation timeouts separate from per-request timeouts.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your streaming API sends first chunk in 2s, continues streaming for 3 minutes total. Your non-streaming API has 60s timeout. Should streaming have different timeout?",
    option_a: "No, always use identical timeouts",
    option_b: "Yes, streaming can have longer total timeout since output arrives incrementally (better UX)",
    option_c: "Streaming doesn't support timeouts",
    option_d: "Only for Enterprise accounts",
    correct_answer: "B",
    explanation: "Streaming requests can have longer total timeouts since users see incremental output, improving perceived responsiveness. The first chunk should arrive quickly, but total generation can be longer.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your document summarization processes 50K token documents. Testing shows: p50=90s, p95=150s, p99=240s. To accommodate 95% of requests while preventing indefinite waits, set timeout to:",
    option_a: "5 seconds",
    option_b: "30 seconds",
    option_c: "2-3 minutes (slightly above p95)",
    option_d: "10 minutes",
    correct_answer: "C",
    explanation: "For large document summarization (50K tokens), 2-3 minutes is reasonable. Large inputs require more processing time. Consider streaming to improve user experience during long operations.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API has 60s timeout. Users see loading spinner but no progress indication. Request takes 55s and succeeds, but users abandon. Best UX practice:",
    option_a: "Don't inform users",
    option_b: "Show progress indicators and explain that complex tasks take time (better UX)",
    option_c: "Always hide processing time",
    option_d: "Only show errors when timeouts occur",
    correct_answer: "B",
    explanation: "Show progress indicators and set expectations that complex tasks take time. Good UX communicates that processing is happening, especially for longer timeouts.",
    difficulty: "easy"
  },

  // Observability and logging (15 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production dashboard needs comprehensive health metrics for Claude API integration. To detect issues early and optimize performance, monitor:",
    option_a: "Error rates with severity classification and root cause analysis",
    option_b: "Error rates (by type: 4xx, 5xx), retry success %, latency percentiles (p50, p95, p99), circuit breaker state",
    option_c: "Response times with geographic distribution and regional latency breakdown",
    option_d: "Token usage patterns with cost tracking and budget alerting",
    correct_answer: "B",
    explanation: "Monitor comprehensive metrics: error rates (by type), retry success rates, latency percentiles (p50, p95, p99), circuit breaker state, and rate limit proximity for complete health visibility.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your debugging workflow requires tracing failed requests across retries and services. For each API request, you should log:",
    option_a: "Error codes with stack traces for debugging production issues",
    option_b: "Inputs (sanitized), outputs, latency, token usage, correlation IDs, errors, retry attempts",
    option_c: "Successful requests only with performance metrics and optimization data",
    option_d: "Minimal logging for privacy compliance excluding all user content",
    correct_answer: "B",
    explanation: "Log comprehensive information: inputs (sanitized if needed), outputs, latency, token usage, correlation IDs, errors, and retry attempts. This enables debugging and optimization.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Request 12345 fails → Retry 1 (12345-r1) fails → Retry 2 (12345-r2) succeeds. To trace this request across services, microservices, and retry attempts, use:",
    option_a: "Reduce token costs through efficient request deduplication tracking",
    option_b: "Correlation IDs enable tracing requests across services and retry attempts",
    option_c: "Improve response accuracy through contextual request association mechanisms",
    option_d: "Required by API specification for production compliance and auditing",
    correct_answer: "B",
    explanation: "Correlation IDs enable tracing requests across services, retry attempts, and log entries, making it possible to follow the complete journey of a request through your system.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your monitoring shows average latency 2s, but users complain about slow responses. You add percentile tracking: p50=2s, p95=15s, p99=45s. Percentiles reveal:",
    option_a: "Average response times only",
    option_b: "Distribution of latencies (p50=typical, p95/p99=worst-case). Averages hide tail latency problems.",
    option_c: "Maximum latency only",
    option_d: "Minimum latency only",
    correct_answer: "B",
    explanation: "Latency percentiles (p50, p95, p99) show the distribution of response times: p50 is median (typical), p95/p99 show tail latency (worst cases). Averages can hide problems that percentiles reveal.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your logs contain: API keys (sk-ant-...), user emails, credit card numbers. Security audit finds GDPR violations. Best practice for logging sensitive data:",
    option_a: "Yes, log everything for debugging",
    option_b: "No, sanitize or redact sensitive information (API keys, PII, credentials)",
    option_c: "Only in production",
    option_d: "Only log encrypted versions",
    correct_answer: "B",
    explanation: "Never log API keys, passwords, or sensitive user data. Sanitize or redact sensitive information while logging enough context for debugging. Follow security best practices and regulations.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your circuit breaker opened after 10 consecutive 503 errors, blocking requests for 60 seconds to allow recovery. Monitoring circuit breaker state (open/closed/half-open) helps:",
    option_a: "Measuring electrical usage",
    option_b: "Understanding if requests are being blocked to prevent cascading failures",
    option_c: "Tracking token usage",
    option_d: "Measuring accuracy",
    correct_answer: "B",
    explanation: "Circuit breaker state (open/closed/half-open) indicates if requests are being blocked to prevent cascading failures. Monitoring this helps understand system health and protection mechanisms.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API shows: 1000 initial failures (503 errors), 850 succeed after retries. Retry success rate is 85%. To validate your retry strategy effectiveness, track:",
    option_a: "It's not necessary to monitor retries",
    option_b: "Percentage of requests that succeed after retrying (85% indicates effective strategy)",
    option_c: "Only monitor failures",
    option_d: "Only monitor first attempts",
    correct_answer: "B",
    explanation: "Track what percentage of requests succeed after retrying (vs failing permanently). High retry success indicates good error handling; low success suggests systemic issues needing investigation.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your logs show: '2024-03-15 14:23:45 ERROR Failed request' (hard to search). Switching to structured JSON logs: {timestamp, level, error_type, correlation_id} enables:",
    option_a: "It's prettier",
    option_b: "Machine-readable format enabling automated analysis, searching, alerting, and integration with observability tools",
    option_c: "It uses less storage",
    option_d: "It's required by the API",
    correct_answer: "B",
    explanation: "Structured logging (JSON, etc.) provides machine-readable format enabling automated analysis, searching, alerting, and integration with observability tools. Much more powerful than unstructured text logs.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your monitoring shows p50=2s (median), p99=30s (99th percentile). This means 1% of requests take 15x longer than typical. This large gap indicates:",
    option_a: "System is performing well",
    option_b: "1% of requests experiencing very high latency (tail latency problem) - investigate",
    option_c: "No issues, these numbers are normal",
    option_d: "Average performance is good",
    correct_answer: "B",
    explanation: "Large gap between p50 and p99 indicates tail latency problems: 1% of requests experience 15x typical latency. This affects user experience and warrants investigation even if most requests are fast.",
    difficulty: "hard"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API has 1000 req/hour limit. Monitoring shows: current rate 950 req/hour (95% capacity), trending up 10%/day. To prevent hitting limits, implement proactive alerting at:",
    option_a: "Only wait for 429 errors",
    option_b: "Track request rate vs known limits, alert at 80% capacity before hitting limits",
    option_c: "Rate limits are unlimited",
    option_d: "Only monitor after errors occur",
    correct_answer: "B",
    explanation: "Proactively monitor request rate vs known limits, tracking trending toward capacity. Alert before hitting limits (e.g., at 80%) so you can adjust before errors occur.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your cost optimization team needs to identify expensive requests. Logging shows: Request A: 50K tokens ($5), Request B: 500 tokens ($0.05). Logging token usage per request enables:",
    option_a: "Logging doesn't affect tokens",
    option_b: "Identifying high-cost patterns to optimize prompts and track costs",
    option_c: "Logging reduces token costs automatically",
    option_d: "Only Enterprise can log tokens",
    correct_answer: "B",
    explanation: "Logging token usage per request enables analysis to identify high-cost patterns, opportunities for prompt optimization, and track costs over time for budgeting and optimization.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your error dashboard shows: 4xx errors (client issues): 200/hour, 5xx errors (server issues): 10/hour. Monitoring these separately helps because:",
    option_a: "No, only monitor total errors",
    option_b: "Yes, 4xx indicates client bugs/invalid inputs; 5xx indicates server-side issues - different fixes needed",
    option_c: "Only monitor 5xx errors",
    option_d: "Only monitor 4xx errors",
    correct_answer: "B",
    explanation: "Monitor errors by type: 4xx indicates client-side issues (bugs, invalid inputs), 5xx indicates server-side issues. Different types require different responses and fixes.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your compliance team (GDPR, HIPAA) requires logs for 7 years. Storage costs $1,000/month. Finance wants to delete logs after 30 days ($50/month). Best practice for log retention:",
    option_a: "Delete logs immediately",
    option_b: "Retain based on compliance requirements (7 years) and debugging needs",
    option_c: "Keep all logs forever",
    option_d: "Only keep error logs",
    correct_answer: "B",
    explanation: "Set retention policies based on compliance requirements (e.g., GDPR, HIPAA) and practical debugging needs. Balance storage costs with the value of historical data for troubleshooting.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your retry monitoring shows: Initial failures: 1000 (100%), After retries: 200 failures (20%). Retry success rate: 80%. This indicates:",
    option_a: "It's not measurable",
    option_b: "80% of initially failed requests succeed after retries (effective retry strategy)",
    option_c: "Only count successful requests",
    option_d: "Only count failed requests",
    correct_answer: "B",
    explanation: "Monitor how many initially failed requests succeed after retries. High retry success (e.g., 80%+) indicates effective retry strategy for transient errors; low success suggests systemic issues.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production SRE team needs to detect issues quickly. Configure alerts for: error rate >5% (abnormal), p99 latency >30s (spike), rate limit at 95%, circuit breaker trips. These alerts:",
    option_a: "No alerts needed",
    option_b: "Alert on: high error rates, p99 latency spikes, rate limit proximity, circuit breaker trips",
    option_c: "Only alert on total system failures",
    option_d: "Alert on every single error",
    correct_answer: "B",
    explanation: "Configure alerts for: abnormally high error rates, p99 latency spikes, approaching rate limits, circuit breaker trips, and sustained retry failures. Balance signal vs noise.",
    difficulty: "medium"
  },

  // Fallback strategies (10 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your real-time API fails during Claude outage. Users see errors and abandon. To ensure continued service (potentially degraded) rather than complete failure, implement:",
    option_a: "Graceful degradation with reduced feature set during outages",
    option_b: "Fallback strategy: alternative approach when primary method fails",
    option_c: "Automatic retry with circuit breaker pattern for failure detection",
    option_d: "Enhanced error logging with real-time alerting and escalation",
    correct_answer: "B",
    explanation: "Fallback strategy provides an alternative approach when the primary method fails, ensuring continued service (potentially degraded) rather than complete failure.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your FAQ chatbot uses Claude API. During an outage, instead of showing errors, you serve cached responses for common questions. This is an example of:",
    option_a: "Retrying with exponential backoff until API recovers successfully",
    option_b: "Serving cached responses when API fails",
    option_c: "Displaying user-friendly error messages with recovery time estimates",
    option_d: "Comprehensive error logging with alerting to operations teams",
    correct_answer: "B",
    explanation: "Serving cached responses when the API fails is a common fallback strategy, providing users with slightly stale but functional responses instead of errors.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your Claude Opus-based analysis tool experiences sustained outages. To maintain functionality at potentially lower quality, you implement:",
    option_a: "Accept lower quality with explicit warnings to users transparently",
    option_b: "Falling back to a faster/cheaper model (Sonnet or Haiku) when Opus fails",
    option_c: "Disable advanced features while maintaining core functionality with caching",
    option_d: "Display graceful error messages with retry options for users",
    correct_answer: "B",
    explanation: "Model degradation means falling back to a faster or cheaper model (e.g., from Opus to Sonnet or Haiku) when the primary model is unavailable, maintaining functionality at potentially lower quality.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your e-commerce platform generates product descriptions with Claude. During Black Friday, API availability is more critical than perfect quality. When should you implement fallback strategies?",
    option_a: "Never, always fail fast",
    option_b: "For mission-critical applications where availability is important",
    option_c: "Only for Enterprise accounts",
    option_d: "Only during development",
    correct_answer: "B",
    explanation: "Implement fallback strategies for mission-critical applications where availability is more important than perfect functionality. Accept degraded service over no service.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your architecture: Primary Claude API → Fallback cached responses → Fallback simpler rule-based system. This increases complexity (more code) but improves availability (99.9% uptime). The trade-off is:",
    option_a: "Higher costs with no benefits",
    option_b: "Increased complexity vs improved availability",
    option_c: "Lower accuracy always",
    option_d: "No trade-offs exist",
    correct_answer: "B",
    explanation: "Fallback strategies increase system complexity (more code, more things to maintain) but improve availability and resilience. The trade-off is worth it for critical systems.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your customer support bot uses Claude API. During a 2-hour outage, instead of showing 'Service unavailable', you:",
    option_a: "Show 'Service unavailable' message",
    option_b: "Serve cached responses for common questions or fallback to simpler model",
    option_c: "Shut down the entire bot",
    option_d: "Queue all requests indefinitely",
    correct_answer: "B",
    explanation: "Fallback to cached responses for common questions or a simpler model keeps the bot functional during outages, maintaining customer service even if degraded.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your AI-powered email categorizer uses Claude for nuanced classification. During outages, you fall back to simple rule-based classification (keywords, sender patterns). This simplified logic fallback:",
    option_a: "Making code simpler",
    option_b: "Using rule-based or simpler logic when AI is unavailable",
    option_c: "Removing all features",
    option_d: "Logging errors",
    correct_answer: "B",
    explanation: "Simplified logic fallback uses rule-based systems or simpler logic when AI is unavailable, providing basic functionality without full AI capabilities.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your chatbot falls back to cached responses during outages. Users appreciate continued service but should know responses may be stale. You should:",
    option_a: "Never inform users",
    option_b: "Yes, show 'Using cached responses' banner to manage expectations",
    option_c: "Only inform for Enterprise users",
    option_d: "Only inform after full recovery",
    correct_answer: "B",
    explanation: "Inform users when in fallback mode (e.g., 'Using cached responses' or 'Running in limited mode'). Transparency manages expectations and maintains trust.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your global SaaS uses Claude API in US-EAST region. During regional outage, your architecture automatically routes to EU-WEST region. This multi-region failover provides:",
    option_a: "Using multiple models",
    option_b: "Failing over to API endpoints in different regions",
    option_c: "Caching in multiple locations",
    option_d: "Retrying with delays",
    correct_answer: "B",
    explanation: "Multi-region failover routes requests to API endpoints in different regions if primary region fails, providing geographic redundancy for mission-critical systems.",
    difficulty: "hard"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your staging environment needs to verify fallback to cached responses works correctly before production deployment. To test fallback strategies before real incidents:",
    option_a: "Wait for real failures",
    option_b: "Chaos engineering - intentionally trigger failures in test environments",
    option_c: "Fallbacks can't be tested",
    option_d: "Only test in production",
    correct_answer: "B",
    explanation: "Use chaos engineering: intentionally trigger failures in test/staging environments to verify fallback strategies work correctly before real incidents occur.",
    difficulty: "medium"
  },

  // Production best practices (10 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your team debates: implement custom retry logic, multi-region failover, circuit breakers, and fallbacks immediately, or start simple? Best practice for production integration:",
    option_a: "Custom implementation with fine-tuned parameters for specific use case",
    option_b: "Use SDK defaults (exponential backoff included), add complexity only as specific needs arise",
    option_c: "Implement comprehensive resilience patterns including circuit breakers and fallbacks",
    option_d: "Basic error handling with enhanced monitoring and alerting infrastructure",
    correct_answer: "B",
    explanation: "Start with SDK defaults which include best practices like exponential backoff. Add complexity (custom retry logic, fallbacks, etc.) only as specific needs arise. Don't over-engineer.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your fintech payment processing API handles $10M daily transactions. A cascading failure could be catastrophic. For this mission-critical system, implement circuit breakers:",
    option_a: "For all production integrations regardless of criticality level consistently",
    option_b: "For mission-critical systems to prevent cascading failures",
    option_c: "Only when monitoring indicates sustained failure patterns requiring intervention",
    option_d: "For high-traffic systems exceeding 1000 requests per minute",
    correct_answer: "B",
    explanation: "Implement circuit breakers for mission-critical systems where cascading failures could be catastrophic. For simpler systems, retry logic with backoff may be sufficient.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your startup MVP uses Claude API. Instead of implementing custom retry logic, circuit breakers, and fallbacks immediately, you start with SDK defaults, monitor production, then add sophistication as needed. This progressive enhancement pattern:",
    option_a: "Start complex, simplify later",
    option_b: "Start with basics (SDK defaults), add sophistication as specific needs emerge",
    option_c: "Ignore errors initially",
    option_d: "Handle all errors identically",
    correct_answer: "B",
    explanation: "Progressive enhancement means starting with basic, proven patterns (SDK defaults) and adding sophistication (custom strategies, fallbacks, circuit breakers) only as specific needs emerge.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your e-commerce site generates $100K revenue/day. Implementing multi-region failover costs $10K setup + $2K/month ongoing. This complexity is justified only for mission-critical systems because:",
    option_a: "It doesn't work",
    option_b: "It adds significant complexity and cost that's only justified for critical systems",
    option_c: "It's only available for Enterprise",
    option_d: "It reduces performance",
    correct_answer: "B",
    explanation: "Multi-region failover adds significant complexity, cost, and maintenance burden. It's only justified for mission-critical systems where the availability benefits outweigh these costs.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your MVP uses just SDK defaults (no custom logic). It's reliable. Your enterprise version adds custom retry logic, circuit breakers, fallbacks, and multi-region failover. New bugs appear. This demonstrates:",
    option_a: "More complexity always means more reliability",
    option_b: "Balance needed - too little OR too much complexity reduces reliability",
    option_c: "Complexity doesn't affect reliability",
    option_d: "Simpler is always better",
    correct_answer: "B",
    explanation: "Balance is key: too little complexity (no error handling) causes failures; too much complexity (over-engineering) introduces bugs and maintenance burden. Right-size for your needs.",
    difficulty: "hard"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Anthropic SDK implements retry logic with exponential backoff and jitter correctly. Your team debates implementing custom retry logic for a slight variation. You should:",
    option_a: "Yes, always customize everything",
    option_b: "Only if you have specific requirements SDK doesn't meet",
    option_c: "Never use SDK defaults",
    option_d: "Always implement both",
    correct_answer: "B",
    explanation: "Use SDK default retry logic unless you have specific requirements it doesn't meet. SDK defaults are well-tested and sufficient for most use cases. Custom logic adds complexity.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production system implements: custom retry logic (different from SDK), 3 fallback layers, circuit breakers, multi-region failover, but reliability is 95% (worse than 99% with SDK defaults). This demonstrates the common mistake of:",
    option_a: "Using SDK defaults",
    option_b: "Over-engineering with unnecessary complexity",
    option_c: "Logging errors",
    option_d: "Monitoring metrics",
    correct_answer: "B",
    explanation: "Over-engineering (implementing every possible pattern, multiple fallback layers, etc.) adds complexity without proportional benefit. Start simple, add sophistication based on actual needs.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your team's production readiness checklist: (1) Basic monitoring + SDK defaults → (2) Deploy to production → (3) Learn from real usage → (4) Add advanced patterns only as needed. This incremental approach:",
    option_a: "Deploy immediately with minimal preparation",
    option_b: "Incremental: monitoring + error handling (SDK defaults) → deploy → learn → add advanced patterns as needed",
    option_c: "Implement all features before any deployment",
    option_d: "Copy another system exactly",
    correct_answer: "B",
    explanation: "Take an incremental approach: start with basic monitoring and error handling (SDK defaults), deploy, learn from real usage, then add advanced patterns only as specific needs emerge.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your staging environment tests: SDK retry logic works, error logging captures failures, fallback to cached responses succeeds, circuit breaker trips correctly after 5 consecutive failures. Staging environments serve to:",
    option_a: "Staging isn't necessary",
    option_b: "Test error handling, fallbacks, and load patterns before production",
    option_c: "Only for Enterprise accounts",
    option_d: "Only for initial development",
    correct_answer: "B",
    explanation: "Use staging environments to test error handling, fallback strategies, retry logic, and load patterns under realistic conditions before production deployment. Catch issues early.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production evolution: Month 1: SDK defaults + basic monitoring (99% uptime) → Month 3: Added metrics show 2% 429 errors, implemented client-side rate limiting (99.5% uptime) → Month 6: Added circuit breaker for sustained failures (99.9% uptime). This demonstrates:",
    option_a: "Big bang redesigns",
    option_b: "Start with SDK defaults, monitor, iterate based on data",
    option_c: "Never change production systems",
    option_d: "Change everything frequently",
    correct_answer: "B",
    explanation: "Start with proven SDK defaults, deploy with comprehensive monitoring, collect data on actual behavior, then iterate and add sophistication based on real needs and patterns observed.",
    difficulty: "medium"
  },

  // SDK usage patterns (5 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your production app uses Anthropic Python SDK. During a 503 outage, requests automatically retry with exponential backoff and jitter, succeeding after 2 attempts. This works because:",
    option_a: "No SDKs provide this",
    option_b: "Anthropic Python and Node.js SDKs include built-in exponential backoff",
    option_c: "Only Python SDK",
    option_d: "Only custom-built SDKs",
    correct_answer: "B",
    explanation: "Both Anthropic Python and Node.js SDKs provide built-in exponential backoff with jitter for retryable errors, eliminating the need to implement this yourself.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your team debates: use Anthropic official SDK (includes retry logic, error handling, exponential backoff, maintained by Anthropic) vs implement direct HTTP calls. The advantage of official SDKs:",
    option_a: "Slightly improved performance through optimized HTTP client configurations",
    option_b: "Built-in best practices (retry logic, error handling), easier API usage, maintained by Anthropic",
    option_c: "Token cost optimization through efficient request batching mechanisms",
    option_d: "Reduced latency via persistent connection pooling and keepalive",
    correct_answer: "B",
    explanation: "Official SDKs include built-in best practices (retry logic, error handling, exponential backoff), easier API usage, and are maintained by Anthropic with updates for API changes.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Anthropic SDK defaults to 3 retries with exponential backoff. Your critical financial app needs 5 retries. Can you configure this in the SDK?",
    option_a: "No, SDK retry behavior fixed at 3 attempts maximum",
    option_b: "Yes, most SDKs allow customizing retry parameters",
    option_c: "Only for Enterprise tier accounts with premium support",
    option_d: "Yes, through environment variables configuring SDK retry behavior",
    correct_answer: "B",
    explanation: "Anthropic SDKs allow customizing retry parameters (max attempts, backoff strategy) while still leveraging SDK infrastructure. Start with defaults; customize only if needed.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your team uses Rust for backend services. Anthropic doesn't provide an official Rust SDK. When should you make direct API calls instead of using an SDK?",
    option_a: "Always use direct API calls",
    option_b: "Only when SDK doesn't exist for your language or has specific limitations",
    option_c: "Never, always use SDKs",
    option_d: "Only for testing",
    correct_answer: "B",
    explanation: "Use official SDKs when available for their built-in best practices. Only make direct API calls when no SDK exists for your language or SDK has specific limitations for your use case.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Anthropic releases Claude 4 with new features. Your app uses the Anthropic Python SDK. SDK version 2.0 supports Claude 4. You update SDK version and immediately get Claude 4 support. This demonstrates SDKs:",
    option_a: "They don't handle version changes",
    option_b: "SDKs are updated by Anthropic to maintain compatibility with API changes",
    option_c: "You must manually update for every API change",
    option_d: "Version changes break SDKs permanently",
    correct_answer: "B",
    explanation: "Official SDKs are maintained by Anthropic and updated to handle API version changes, providing a more stable integration layer than direct API calls which require manual updates.",
    difficulty: "medium"
  }
];
