export interface Question {
  week?: number;
  domain: string;
  topic: string;
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_answer: string;
  explanation: string;
  difficulty?: string;
}

export const topic11Questions: Question[] = [
  // Error types and retry logic (20 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Which HTTP status codes should you retry?",
    option_a: "All error codes",
    option_b: "429 and 5xx errors",
    option_c: "All 4xx and 5xx errors",
    option_d: "Only 500 errors",
    correct_answer: "B",
    explanation: "Retry 429 (rate limit) and 5xx (server errors) as these are typically transient. Do not retry 4xx errors (except 429) as they indicate client-side problems that won't be resolved by retrying.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Should you retry 400 Bad Request errors?",
    option_a: "Yes, always retry all errors",
    option_b: "No, 400 indicates a client-side problem that won't be fixed by retrying",
    option_c: "Yes, but only once",
    option_d: "Only for Enterprise accounts",
    correct_answer: "B",
    explanation: "Never retry 400 errors as they indicate client-side problems (invalid request format, parameters, etc.) that won't be resolved by retrying. Fix the request instead.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What does a 429 status code indicate?",
    option_a: "Server error",
    option_b: "Rate limit exceeded",
    option_c: "Invalid API key",
    option_d: "Request timeout",
    correct_answer: "B",
    explanation: "429 status code indicates rate limit exceeded. This is a retryable error - wait and retry with exponential backoff, respecting retry-after headers.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API call returns a 503 Service Unavailable. What should you do?",
    option_a: "Immediately fail and report error",
    option_b: "Retry with exponential backoff",
    option_c: "Switch to a different model",
    option_d: "Never retry 5xx errors",
    correct_answer: "B",
    explanation: "503 is a server-side error indicating temporary unavailability. Retry with exponential backoff as the service will likely recover.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the recommended retry strategy for rate limit errors (429)?",
    option_a: "Retry immediately",
    option_b: "Respect retry-after header and use exponential backoff",
    option_c: "Never retry",
    option_d: "Wait exactly 1 second and retry",
    correct_answer: "B",
    explanation: "For 429 errors, respect the retry-after header if provided, and use exponential backoff. This prevents overwhelming the system while ensuring requests eventually succeed.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "You receive a 401 Unauthorized error. What's the appropriate action?",
    option_a: "Retry with exponential backoff",
    option_b: "Fix authentication (API key) - do not retry",
    option_c: "Retry once then fail",
    option_d: "Switch to a different endpoint",
    correct_answer: "B",
    explanation: "401 indicates an authentication problem (invalid or missing API key). Don't retry - fix the authentication issue. Retrying won't help and wastes resources.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What error handling approach do Anthropic SDKs use by default?",
    option_a: "No automatic retries",
    option_b: "Exponential backoff with jitter for retryable errors",
    option_c: "Fixed 1-second delays between retries",
    option_d: "Retry all errors exactly 3 times",
    correct_answer: "B",
    explanation: "Anthropic Python and Node.js SDKs automatically implement exponential backoff with jitter for retryable errors (429, 5xx), which is the recommended approach.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API call returns a 400 error saying the request exceeds token limits. What should you do?",
    option_a: "Retry with exponential backoff",
    option_b: "Modify or split the request - do not retry",
    option_c: "Wait 1 minute and retry",
    option_d: "Retry with a smaller timeout",
    correct_answer: "B",
    explanation: "Token limit errors (400) are client-side errors requiring request modification (reduce content, split into multiple requests). Retrying without changes won't help.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Which SDK provides built-in retry logic with exponential backoff?",
    option_a: "Only custom implementations have this",
    option_b: "Anthropic Python and Node.js SDKs",
    option_c: "Only Enterprise SDKs",
    option_d: "No SDKs provide this",
    correct_answer: "B",
    explanation: "Both Anthropic Python and Node.js SDKs provide built-in retry logic with exponential backoff for retryable errors, eliminating the need for custom retry implementation.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the difference between retryable and non-retryable errors?",
    option_a: "All errors are retryable",
    option_b: "Retryable errors are transient (429, 5xx); non-retryable need fixing (4xx)",
    option_c: "Only 500 errors are retryable",
    option_d: "All 4xx errors are retryable",
    correct_answer: "B",
    explanation: "Retryable errors (429, 5xx) are transient and may succeed on retry. Non-retryable errors (most 4xx) indicate client-side problems requiring fixes, not retries.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your application receives intermittent 502 Bad Gateway errors. What's the best strategy?",
    option_a: "Fail immediately for all 502 errors",
    option_b: "Implement retry with exponential backoff",
    option_c: "Log and ignore these errors",
    option_d: "Switch APIs permanently",
    correct_answer: "B",
    explanation: "502 is a transient server-side error. Implement retry with exponential backoff - these errors typically resolve quickly and requests succeed on retry.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's a 'documented exception' to the 4xx no-retry rule?",
    option_a: "All 4xx errors should be retried",
    option_b: "429 (rate limit) is retryable despite being 4xx",
    option_c: "There are no exceptions",
    option_d: "Only 404 errors are exceptions",
    correct_answer: "B",
    explanation: "429 is the main documented exception to the 4xx no-retry rule. It's a client-side status code but indicates a transient condition (rate limiting) that resolves over time.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How should you handle network timeout errors?",
    option_a: "Never retry timeouts",
    option_b: "Retry with backoff, but be cautious of idempotency",
    option_c: "Only retry for GET requests",
    option_d: "Increase timeout and retry immediately",
    correct_answer: "B",
    explanation: "Retry timeouts with exponential backoff, but be cautious about idempotency - ensure retrying doesn't cause duplicate processing. Consider whether the original request might have succeeded.",
    difficulty: "hard"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What error handling pattern should you avoid?",
    option_a: "Exponential backoff",
    option_b: "Retrying all errors without discrimination",
    option_c: "Using SDK defaults",
    option_d: "Logging errors",
    correct_answer: "B",
    explanation: "Avoid retrying all errors indiscriminately. This wastes resources on non-retryable errors (4xx) and can create cascading failures. Only retry appropriate errors (429, 5xx).",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your API key has been rotated but the application still uses the old one. What error do you expect?",
    option_a: "429 Rate Limit",
    option_b: "401 Unauthorized",
    option_c: "500 Internal Server Error",
    option_d: "400 Bad Request",
    correct_answer: "B",
    explanation: "An invalid or expired API key results in 401 Unauthorized. This is a non-retryable error - update the API key configuration.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the maximum number of retries you should typically implement?",
    option_a: "Unlimited retries",
    option_b: "3-5 retries with exponential backoff",
    option_c: "Always exactly 3 retries",
    option_d: "Never retry",
    correct_answer: "B",
    explanation: "Typically implement 3-5 retries with exponential backoff. This balances giving transient errors time to resolve while avoiding excessive waiting for persistent failures.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How should you log retry attempts?",
    option_a: "Don't log retries",
    option_b: "Log each attempt with context for debugging",
    option_c: "Only log final failure",
    option_d: "Only log successful retries",
    correct_answer: "B",
    explanation: "Log each retry attempt with context (attempt number, error, backoff duration) for debugging. This helps identify patterns and optimize retry strategies.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What should you do if retries consistently fail after maximum attempts?",
    option_a: "Retry indefinitely",
    option_b: "Return error, log for investigation, consider fallback strategies",
    option_c: "Silently drop the request",
    option_d: "Immediately switch APIs",
    correct_answer: "B",
    explanation: "After maximum retries fail, return an error to the caller, log comprehensively for investigation, and consider fallback strategies (cached responses, degraded service, circuit breaker).",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Can you override SDK default retry behavior?",
    option_a: "No, SDK behavior is fixed",
    option_b: "Yes, SDKs allow customizing retry strategies",
    option_c: "Only for Enterprise accounts",
    option_d: "Only by forking the SDK",
    correct_answer: "B",
    explanation: "Anthropic SDKs allow customizing retry strategies (max attempts, backoff parameters), but start with SDK defaults and only customize if you have specific requirements.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the main risk of aggressive retry strategies?",
    option_a: "Lower accuracy",
    option_b: "Thundering herd and cascading failures",
    option_c: "Higher costs",
    option_d: "Slower initial response",
    correct_answer: "B",
    explanation: "Aggressive retries (immediate, no backoff, too many clients) can cause thundering herd problems and cascading failures, overwhelming systems during recovery and prolonging outages.",
    difficulty: "hard"
  },

  // Exponential backoff and jitter (15 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What is exponential backoff?",
    option_a: "Waiting a fixed time between retries",
    option_b: "Doubling wait time with each retry attempt",
    option_c: "Random wait times between retries",
    option_d: "Decreasing wait time with each retry",
    correct_answer: "B",
    explanation: "Exponential backoff doubles the wait time with each retry attempt (e.g., 1s, 2s, 4s, 8s), allowing more time for transient issues to resolve while preventing system overload.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What is the recommended base delay for exponential backoff?",
    option_a: "100 milliseconds",
    option_b: "1 second",
    option_c: "5 seconds",
    option_d: "10 seconds",
    correct_answer: "B",
    explanation: "The recommended base delay is 1 second. This provides a reasonable starting point that doubles to 2s, 4s, 8s, etc., balancing responsiveness with giving errors time to resolve.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What is jitter in the context of retries?",
    option_a: "Network latency variations",
    option_b: "Random variation added to backoff delays",
    option_c: "Error in time calculations",
    option_d: "Maximum wait time",
    correct_answer: "B",
    explanation: "Jitter is random variation added to backoff delays to prevent many clients from retrying simultaneously (thundering herd), distributing retry load over time.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Why is jitter important?",
    option_a: "It makes delays more predictable",
    option_b: "It prevents thundering herd by distributing retries",
    option_c: "It reduces total wait time",
    option_d: "It's required by the API",
    correct_answer: "B",
    explanation: "Jitter prevents thundering herd problems where many clients retry simultaneously, overwhelming the recovering service. It distributes retry attempts over time.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What is full jitter?",
    option_a: "No randomization",
    option_b: "Random value between 0 and the calculated backoff time",
    option_c: "Fixed percentage variation",
    option_d: "Only applying jitter to the first retry",
    correct_answer: "B",
    explanation: "Full jitter selects a random value between 0 and the calculated exponential backoff time (e.g., for 4s backoff, randomly choose between 0-4s), providing maximum distribution of retries.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "With 1s base and exponential backoff, what are the approximate delays for 4 retries without jitter?",
    option_a: "1s, 1s, 1s, 1s",
    option_b: "1s, 2s, 4s, 8s",
    option_c: "1s, 3s, 5s, 7s",
    option_d: "1s, 2s, 3s, 4s",
    correct_answer: "B",
    explanation: "With 1s base and exponential backoff, delays double each time: 1s, 2s, 4s, 8s. This is before jitter is applied.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the total maximum wait time for 3 retries with 1s base exponential backoff?",
    option_a: "3 seconds",
    option_b: "7 seconds",
    option_c: "15 seconds",
    option_d: "30 seconds",
    correct_answer: "B",
    explanation: "With 1s base and 3 retries: 1s + 2s + 4s = 7 seconds total maximum wait time (before jitter). This is the sum of all retry delays.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Should you implement exponential backoff yourself?",
    option_a: "Yes, always implement custom backoff",
    option_b: "No, use SDK defaults which implement it correctly",
    option_c: "Only for production environments",
    option_d: "Only for Enterprise accounts",
    correct_answer: "B",
    explanation: "Use SDK defaults which implement exponential backoff with jitter correctly. Only implement custom backoff if you have specific requirements the SDK doesn't meet.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's a risk of exponential backoff without jitter?",
    option_a: "Too slow retries",
    option_b: "Thundering herd - all clients retry simultaneously",
    option_c: "Higher API costs",
    option_d: "Lower success rates",
    correct_answer: "B",
    explanation: "Without jitter, all clients experiencing the same error wait identical times and retry simultaneously, creating thundering herd problems that can overwhelm the recovering service.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Should you cap the maximum backoff delay?",
    option_a: "No, let it grow indefinitely",
    option_b: "Yes, cap at a reasonable maximum like 60 seconds",
    option_c: "Only cap for Enterprise accounts",
    option_d: "Only cap during peak hours",
    correct_answer: "B",
    explanation: "Cap maximum backoff delay at a reasonable limit (e.g., 60 seconds) to prevent excessively long waits while still providing adequate spacing between retries.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How does the retry-after header interact with exponential backoff?",
    option_a: "Ignore retry-after and use only backoff",
    option_b: "Use retry-after if provided, otherwise use backoff",
    option_c: "Use whichever is longer",
    option_d: "Retry-after disables backoff",
    correct_answer: "B",
    explanation: "Respect the retry-after header if provided (especially for 429 errors), as it tells you exactly when to retry. Fall back to exponential backoff if no header is present.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the advantage of exponential backoff over fixed delays?",
    option_a: "Simpler to implement",
    option_b: "Adapts to issue severity - gives more time for persistent problems",
    option_c: "Always faster",
    option_d: "Uses less memory",
    correct_answer: "B",
    explanation: "Exponential backoff adapts to issue severity - quick retries for transient issues, longer delays for persistent problems. This is more efficient than fixed delays which don't adapt.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your application has 1000 concurrent clients. All hit a rate limit simultaneously. What does jitter prevent?",
    option_a: "Individual failures",
    option_b: "All 1000 clients retrying at exactly the same time",
    option_c: "Rate limit errors",
    option_d: "Network congestion",
    correct_answer: "B",
    explanation: "Jitter prevents all 1000 clients from retrying at exactly the same time, which would immediately hit rate limits again. It distributes retries over the backoff window.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's a typical maximum cap for exponential backoff delays?",
    option_a: "5 seconds",
    option_b: "30-60 seconds",
    option_c: "5 minutes",
    option_d: "No cap needed",
    correct_answer: "B",
    explanation: "A typical maximum cap is 30-60 seconds. This prevents excessive waiting while still providing adequate spacing. The exact value depends on your application's timeout tolerance.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How should you implement jitter?",
    option_a: "Add a fixed 500ms to each delay",
    option_b: "Use random value between 0 and calculated backoff (full jitter)",
    option_c: "Add random ±10% to delay",
    option_d: "Only apply to first retry",
    correct_answer: "B",
    explanation: "Best practice is full jitter: select a random value between 0 and the calculated exponential backoff time. This provides maximum distribution and prevents thundering herd.",
    difficulty: "medium"
  },

  // Rate limiting and overload handling (15 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What is client-side rate limiting?",
    option_a: "Server-enforced request limits",
    option_b: "Client controls its own request rate to stay within limits",
    option_c: "Blocking all requests for a period",
    option_d: "Random request throttling",
    correct_answer: "B",
    explanation: "Client-side rate limiting means the client proactively controls its request rate to stay within known limits, preventing server-side rate limit errors before they occur.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Why implement client-side rate limiting?",
    option_a: "It's required by the API",
    option_b: "To prevent rate limit errors and improve reliability",
    option_c: "To reduce API costs",
    option_d: "To improve response accuracy",
    correct_answer: "B",
    explanation: "Client-side rate limiting prevents rate limit errors before they occur, improving reliability and user experience by avoiding error-retry cycles.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What should you do when receiving overload errors?",
    option_a: "Fail immediately",
    option_b: "Retry with backoff, consider fallback to alternative models",
    option_c: "Switch APIs permanently",
    option_d: "Increase request rate",
    correct_answer: "B",
    explanation: "For overload errors, retry with exponential backoff to allow the system to recover. Consider fallback to alternative models or cached responses if overload persists.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What information do retry-after headers provide?",
    option_a: "Error details",
    option_b: "How long to wait before retrying",
    option_c: "API version information",
    option_d: "Current rate limit status",
    correct_answer: "B",
    explanation: "Retry-after headers tell you exactly how long to wait before retrying, often provided with 429 rate limit responses. Always respect these headers.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your application sends 100 requests/minute but the limit is 60/minute. What's the best solution?",
    option_a: "Send all 100 and handle rate limit errors",
    option_b: "Implement client-side rate limiting at 60/minute",
    option_c: "Add delays randomly",
    option_d: "Reduce to 50/minute to be safe",
    correct_answer: "B",
    explanation: "Implement client-side rate limiting at exactly 60 requests/minute. This prevents rate limit errors while maximizing your allowed throughput.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Should you respect retry-after headers?",
    option_a: "No, they're just suggestions",
    option_b: "Yes, always respect them to avoid continued rate limiting",
    option_c: "Only for Enterprise accounts",
    option_d: "Only if they're under 10 seconds",
    correct_answer: "B",
    explanation: "Always respect retry-after headers. They provide authoritative information about when you can retry without continued rate limiting. Ignoring them can lead to extended rate limiting.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's a token bucket algorithm used for?",
    option_a: "Token counting",
    option_b: "Client-side rate limiting with burst handling",
    option_c: "Caching tokens",
    option_d: "Error detection",
    correct_answer: "B",
    explanation: "Token bucket algorithm is a common pattern for client-side rate limiting that allows controlled bursts while maintaining average rate limits over time.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How should you handle sustained overload conditions?",
    option_a: "Keep retrying indefinitely",
    option_b: "Implement fallback strategies (cached responses, degraded service)",
    option_c: "Give up immediately",
    option_d: "Double the request rate",
    correct_answer: "B",
    explanation: "For sustained overload, implement fallback strategies like serving cached responses, degraded service with simpler models, or circuit breakers to prevent cascading failures.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the relationship between rate limiting and exponential backoff?",
    option_a: "They're the same thing",
    option_b: "Rate limiting is proactive; backoff is reactive to errors",
    option_c: "They're incompatible",
    option_d: "Only use one, not both",
    correct_answer: "B",
    explanation: "Rate limiting is proactive (preventing errors), while exponential backoff is reactive (handling errors). Use both: rate limiting to minimize errors, backoff to handle any that occur.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How can you monitor rate limit consumption?",
    option_a: "It's not possible",
    option_b: "Track requests sent vs limits, monitor 429 error rates",
    option_c: "Only available in Enterprise dashboards",
    option_d: "Rate limits are unlimited",
    correct_answer: "B",
    explanation: "Monitor rate limit consumption by tracking requests sent against known limits and monitoring 429 error rates. This helps optimize request patterns and avoid limits.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's a queue-based approach to rate limiting?",
    option_a: "Sending all requests immediately",
    option_b: "Queueing requests and processing at controlled rate",
    option_c: "Randomly dropping requests",
    option_d: "Duplicating all requests",
    correct_answer: "B",
    explanation: "Queue-based rate limiting queues incoming requests and processes them at a controlled rate that stays within limits. This smooths bursts and prevents rate limit errors.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your application needs to handle traffic spikes. What's the best approach?",
    option_a: "Reject requests during spikes",
    option_b: "Implement queuing with rate limiting and backpressure",
    option_c: "Process everything and handle errors",
    option_d: "Cache everything permanently",
    correct_answer: "B",
    explanation: "Implement queuing with rate limiting and backpressure to handle spikes gracefully. Queue excess requests and process at sustainable rates, with backpressure to prevent queue overflow.",
    difficulty: "hard"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What indicates you're approaching rate limits?",
    option_a: "Slower response times",
    option_b: "Increasing 429 error rate",
    option_c: "Lower accuracy",
    option_d: "Higher token costs",
    correct_answer: "B",
    explanation: "An increasing 429 error rate indicates you're approaching or exceeding rate limits. Monitor this metric to adjust request rates proactively.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Should rate limits vary by model or tier?",
    option_a: "No, all limits are identical",
    option_b: "Yes, check documentation for specific limits per model/tier",
    option_c: "Only Enterprise has different limits",
    option_d: "Limits don't exist",
    correct_answer: "B",
    explanation: "Rate limits can vary by model, pricing tier, and account type. Check documentation for specific limits and implement appropriate client-side limiting for your configuration.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's a circuit breaker pattern in the context of overload?",
    option_a: "Electrical safety mechanism",
    option_b: "Temporarily stopping requests after repeated failures to allow recovery",
    option_c: "Permanent request blocking",
    option_d: "Random request sampling",
    correct_answer: "B",
    explanation: "Circuit breaker pattern temporarily stops requests after repeated failures, giving the system time to recover. After a timeout, it allows test requests to check if service has recovered.",
    difficulty: "hard"
  },

  // Timeout strategies (10 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the recommended timeout for simple chat interactions?",
    option_a: "1 second",
    option_b: "5-10 seconds",
    option_c: "30 seconds",
    option_d: "2 minutes",
    correct_answer: "B",
    explanation: "For simple chat interactions, 5-10 seconds is appropriate. This balances user experience (not too long to wait) with giving the model time to generate responses.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the recommended timeout for standard API calls?",
    option_a: "5-10 seconds",
    option_b: "30-60 seconds",
    option_c: "2-5 minutes",
    option_d: "10 minutes",
    correct_answer: "B",
    explanation: "For standard API calls with moderate complexity, 30-60 seconds is recommended. This accommodates processing time while preventing indefinite waiting.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What timeout is appropriate for complex analysis tasks?",
    option_a: "10 seconds",
    option_b: "30 seconds",
    option_c: "2-5 minutes",
    option_d: "No timeout needed",
    correct_answer: "C",
    explanation: "Complex analysis tasks (large documents, multi-step reasoning) may require 2-5 minutes. Set timeouts based on task complexity and acceptable user wait times.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Should timeouts vary based on expected task complexity?",
    option_a: "No, use a fixed timeout for all requests",
    option_b: "Yes, set timeouts based on expected task complexity",
    option_c: "Only vary for Enterprise accounts",
    option_d: "Timeouts aren't necessary",
    correct_answer: "B",
    explanation: "Vary timeouts based on task complexity: shorter for simple chat (5-10s), longer for complex analysis (2-5min). This optimizes both user experience and resource usage.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What should you do when a request times out?",
    option_a: "Immediately retry with the same timeout",
    option_b: "Consider it a retryable error, use exponential backoff",
    option_c: "Never retry timeouts",
    option_d: "Double the timeout and retry immediately",
    correct_answer: "B",
    explanation: "Treat timeouts as potentially retryable errors with exponential backoff, but be cautious about idempotency. Consider whether the request might have succeeded but response was delayed.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your users complain that responses are slow. You have a 5-second timeout. What should you consider?",
    option_a: "Reduce timeout to 2 seconds",
    option_b: "Analyze if tasks are too complex, consider streaming, or optimize prompts",
    option_c: "Increase timeout to 30 seconds",
    option_d: "Remove timeouts entirely",
    correct_answer: "B",
    explanation: "Rather than just adjusting timeouts, analyze root causes: Are tasks too complex? Would streaming improve perceived performance? Can prompts be optimized? Address underlying issues, not just symptoms.",
    difficulty: "hard"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How do timeouts interact with exponential backoff?",
    option_a: "They're unrelated",
    option_b: "Total time including retries can exceed individual timeout",
    option_c: "Backoff resets timeout",
    option_d: "Timeouts disable backoff",
    correct_answer: "B",
    explanation: "Individual requests have timeouts, but total time including retries and backoff delays can be much longer. Set overall operation timeouts separate from per-request timeouts.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Should you use different timeouts for streaming vs non-streaming requests?",
    option_a: "No, always use identical timeouts",
    option_b: "Yes, streaming can have longer timeouts since output arrives incrementally",
    option_c: "Streaming doesn't support timeouts",
    option_d: "Only for Enterprise accounts",
    correct_answer: "B",
    explanation: "Streaming requests can have longer total timeouts since users see incremental output, improving perceived responsiveness. The first chunk should arrive quickly, but total generation can be longer.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's a reasonable timeout for a document summarization task with a 50K token document?",
    option_a: "5 seconds",
    option_b: "30 seconds",
    option_c: "2-3 minutes",
    option_d: "10 minutes",
    correct_answer: "C",
    explanation: "For large document summarization (50K tokens), 2-3 minutes is reasonable. Large inputs require more processing time. Consider streaming to improve user experience during long operations.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How should you communicate timeouts to users?",
    option_a: "Don't inform users",
    option_b: "Show progress indicators and explain that complex tasks take time",
    option_c: "Always hide processing time",
    option_d: "Only show errors when timeouts occur",
    correct_answer: "B",
    explanation: "Show progress indicators and set expectations that complex tasks take time. Good UX communicates that processing is happening, especially for longer timeouts.",
    difficulty: "easy"
  },

  // Observability and logging (15 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What key metrics should you monitor for API integration health?",
    option_a: "Only error rates",
    option_b: "Error rates, retry success, latency percentiles, circuit breaker state",
    option_c: "Only response times",
    option_d: "Only token usage",
    correct_answer: "B",
    explanation: "Monitor comprehensive metrics: error rates (by type), retry success rates, latency percentiles (p50, p95, p99), circuit breaker state, and rate limit proximity for complete health visibility.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What should you log for each API request?",
    option_a: "Only errors",
    option_b: "Inputs, outputs, latency, token usage, correlation IDs",
    option_c: "Only successful requests",
    option_d: "Nothing for privacy",
    correct_answer: "B",
    explanation: "Log comprehensive information: inputs (sanitized if needed), outputs, latency, token usage, correlation IDs, errors, and retry attempts. This enables debugging and optimization.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Why are correlation IDs important?",
    option_a: "They reduce costs",
    option_b: "They enable tracing requests across services and retry attempts",
    option_c: "They improve accuracy",
    option_d: "They're required by the API",
    correct_answer: "B",
    explanation: "Correlation IDs enable tracing requests across services, retry attempts, and log entries, making it possible to follow the complete journey of a request through your system.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What are latency percentiles and why monitor them?",
    option_a: "Average response times only",
    option_b: "Distribution of latencies (p50, p95, p99) showing typical and worst-case performance",
    option_c: "Maximum latency only",
    option_d: "Minimum latency only",
    correct_answer: "B",
    explanation: "Latency percentiles (p50, p95, p99) show the distribution of response times: p50 is median (typical), p95/p99 show tail latency (worst cases). Averages can hide problems that percentiles reveal.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Should you log API keys or sensitive user data?",
    option_a: "Yes, log everything for debugging",
    option_b: "No, sanitize or redact sensitive information",
    option_c: "Only in production",
    option_d: "Only log encrypted versions",
    correct_answer: "B",
    explanation: "Never log API keys, passwords, or sensitive user data. Sanitize or redact sensitive information while logging enough context for debugging. Follow security best practices and regulations.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the purpose of a circuit breaker state metric?",
    option_a: "Measuring electrical usage",
    option_b: "Monitoring if the circuit breaker is open/closed to prevent cascading failures",
    option_c: "Tracking token usage",
    option_d: "Measuring accuracy",
    correct_answer: "B",
    explanation: "Circuit breaker state (open/closed/half-open) indicates if requests are being blocked to prevent cascading failures. Monitoring this helps understand system health and protection mechanisms.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How should you monitor retry success rates?",
    option_a: "It's not necessary to monitor retries",
    option_b: "Track percentage of requests that succeed after retrying",
    option_c: "Only monitor failures",
    option_d: "Only monitor first attempts",
    correct_answer: "B",
    explanation: "Track what percentage of requests succeed after retrying (vs failing permanently). High retry success indicates good error handling; low success suggests systemic issues needing investigation.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the benefit of structured logging?",
    option_a: "It's prettier",
    option_b: "Machine-readable format enabling automated analysis and alerting",
    option_c: "It uses less storage",
    option_d: "It's required by the API",
    correct_answer: "B",
    explanation: "Structured logging (JSON, etc.) provides machine-readable format enabling automated analysis, searching, alerting, and integration with observability tools. Much more powerful than unstructured text logs.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your p99 latency is 30 seconds but p50 is 2 seconds. What does this indicate?",
    option_a: "System is performing well",
    option_b: "1% of requests are experiencing very high latency - investigate",
    option_c: "No issues, these numbers are normal",
    option_d: "Average performance is good",
    correct_answer: "B",
    explanation: "Large gap between p50 and p99 indicates tail latency problems: 1% of requests experience 15x typical latency. This affects user experience and warrants investigation even if most requests are fast.",
    difficulty: "hard"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What should you monitor to detect approaching rate limits?",
    option_a: "Only wait for 429 errors",
    option_b: "Track request rate vs known limits, trending toward capacity",
    option_c: "Rate limits are unlimited",
    option_d: "Only monitor after errors occur",
    correct_answer: "B",
    explanation: "Proactively monitor request rate vs known limits, tracking trending toward capacity. Alert before hitting limits (e.g., at 80%) so you can adjust before errors occur.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How can logging help optimize token usage?",
    option_a: "Logging doesn't affect tokens",
    option_b: "Log token usage per request to identify high-cost patterns",
    option_c: "Logging reduces token costs automatically",
    option_d: "Only Enterprise can log tokens",
    correct_answer: "B",
    explanation: "Logging token usage per request enables analysis to identify high-cost patterns, opportunities for prompt optimization, and track costs over time for budgeting and optimization.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Should you monitor error rates by error type (4xx vs 5xx)?",
    option_a: "No, only monitor total errors",
    option_b: "Yes, different types indicate different problems",
    option_c: "Only monitor 5xx errors",
    option_d: "Only monitor 4xx errors",
    correct_answer: "B",
    explanation: "Monitor errors by type: 4xx indicates client-side issues (bugs, invalid inputs), 5xx indicates server-side issues. Different types require different responses and fixes.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's a good practice for log retention?",
    option_a: "Delete logs immediately",
    option_b: "Retain based on compliance requirements and debugging needs",
    option_c: "Keep all logs forever",
    option_d: "Only keep error logs",
    correct_answer: "B",
    explanation: "Set retention policies based on compliance requirements (e.g., GDPR, HIPAA) and practical debugging needs. Balance storage costs with the value of historical data for troubleshooting.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How can you monitor the effectiveness of your retry strategy?",
    option_a: "It's not measurable",
    option_b: "Compare initial failure rate to final failure rate after retries",
    option_c: "Only count successful requests",
    option_d: "Only count failed requests",
    correct_answer: "B",
    explanation: "Monitor how many initially failed requests succeed after retries. High retry success (e.g., 80%+) indicates effective retry strategy for transient errors; low success suggests systemic issues.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What alerts should you configure for production systems?",
    option_a: "No alerts needed",
    option_b: "High error rates, p99 latency spikes, rate limit proximity, circuit breaker trips",
    option_c: "Only alert on total system failures",
    option_d: "Alert on every single error",
    correct_answer: "B",
    explanation: "Configure alerts for: abnormally high error rates, p99 latency spikes, approaching rate limits, circuit breaker trips, and sustained retry failures. Balance signal vs noise.",
    difficulty: "medium"
  },

  // Fallback strategies (10 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What is a fallback strategy?",
    option_a: "Giving up on errors",
    option_b: "Alternative approach when primary method fails",
    option_c: "Automatic retry mechanism",
    option_d: "Error logging",
    correct_answer: "B",
    explanation: "Fallback strategy provides an alternative approach when the primary method fails, ensuring continued service (potentially degraded) rather than complete failure.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's an example of a fallback strategy?",
    option_a: "Retrying indefinitely",
    option_b: "Serving cached responses when API fails",
    option_c: "Showing detailed error messages",
    option_d: "Logging errors",
    correct_answer: "B",
    explanation: "Serving cached responses when the API fails is a common fallback strategy, providing users with slightly stale but functional responses instead of errors.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What is model degradation as a fallback?",
    option_a: "Accepting lower quality responses",
    option_b: "Falling back to a faster/cheaper model when primary fails",
    option_c: "Disabling all features",
    option_d: "Showing error messages",
    correct_answer: "B",
    explanation: "Model degradation means falling back to a faster or cheaper model (e.g., from Opus to Sonnet or Haiku) when the primary model is unavailable, maintaining functionality at potentially lower quality.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "When should you implement fallback strategies?",
    option_a: "Never, always fail fast",
    option_b: "For mission-critical applications where availability is important",
    option_c: "Only for Enterprise accounts",
    option_d: "Only during development",
    correct_answer: "B",
    explanation: "Implement fallback strategies for mission-critical applications where availability is more important than perfect functionality. Accept degraded service over no service.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the trade-off of fallback strategies?",
    option_a: "Higher costs with no benefits",
    option_b: "Increased complexity vs improved availability",
    option_c: "Lower accuracy always",
    option_d: "No trade-offs exist",
    correct_answer: "B",
    explanation: "Fallback strategies increase system complexity (more code, more things to maintain) but improve availability and resilience. The trade-off is worth it for critical systems.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Your customer support bot uses Claude. API is down. What's a good fallback?",
    option_a: "Show 'Service unavailable' message",
    option_b: "Serve cached responses for common questions or fallback to simpler model",
    option_c: "Shut down the entire bot",
    option_d: "Queue all requests indefinitely",
    correct_answer: "B",
    explanation: "Fallback to cached responses for common questions or a simpler model keeps the bot functional during outages, maintaining customer service even if degraded.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What is simplified logic as a fallback?",
    option_a: "Making code simpler",
    option_b: "Using rule-based or simpler logic when AI is unavailable",
    option_c: "Removing all features",
    option_d: "Logging errors",
    correct_answer: "B",
    explanation: "Simplified logic fallback uses rule-based systems or simpler logic when AI is unavailable, providing basic functionality without full AI capabilities.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Should you inform users when operating in fallback mode?",
    option_a: "Never inform users",
    option_b: "Yes, transparency about degraded service manages expectations",
    option_c: "Only inform for Enterprise users",
    option_d: "Only inform after full recovery",
    correct_answer: "B",
    explanation: "Inform users when in fallback mode (e.g., 'Using cached responses' or 'Running in limited mode'). Transparency manages expectations and maintains trust.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's a multi-region failover strategy?",
    option_a: "Using multiple models",
    option_b: "Failing over to API endpoints in different regions",
    option_c: "Caching in multiple locations",
    option_d: "Retrying with delays",
    correct_answer: "B",
    explanation: "Multi-region failover routes requests to API endpoints in different regions if primary region fails, providing geographic redundancy for mission-critical systems.",
    difficulty: "hard"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How do you test fallback strategies?",
    option_a: "Wait for real failures",
    option_b: "Chaos engineering - intentionally trigger failures in test environments",
    option_c: "Fallbacks can't be tested",
    option_d: "Only test in production",
    correct_answer: "B",
    explanation: "Use chaos engineering: intentionally trigger failures in test/staging environments to verify fallback strategies work correctly before real incidents occur.",
    difficulty: "medium"
  },

  // Production best practices (10 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the recommended starting point for production integration?",
    option_a: "Custom implementation from scratch",
    option_b: "Use SDK defaults and add complexity only as needed",
    option_c: "Implement all advanced features immediately",
    option_d: "Minimal error handling",
    correct_answer: "B",
    explanation: "Start with SDK defaults which include best practices like exponential backoff. Add complexity (custom retry logic, fallbacks, etc.) only as specific needs arise. Don't over-engineer.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "When should you implement circuit breakers?",
    option_a: "Always, for every integration",
    option_b: "For mission-critical systems to prevent cascading failures",
    option_c: "Never, they're too complex",
    option_d: "Only for Enterprise accounts",
    correct_answer: "B",
    explanation: "Implement circuit breakers for mission-critical systems where cascading failures could be catastrophic. For simpler systems, retry logic with backoff may be sufficient.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the principle of 'progressive enhancement' in error handling?",
    option_a: "Start complex, simplify later",
    option_b: "Start with basics (SDK defaults), add sophistication as needed",
    option_c: "Ignore errors initially",
    option_d: "Handle all errors identically",
    correct_answer: "B",
    explanation: "Progressive enhancement means starting with basic, proven patterns (SDK defaults) and adding sophistication (custom strategies, fallbacks, circuit breakers) only as specific needs emerge.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Why is multi-region failover recommended only for mission-critical systems?",
    option_a: "It doesn't work",
    option_b: "It adds significant complexity and cost that's only justified for critical systems",
    option_c: "It's only available for Enterprise",
    option_d: "It reduces performance",
    correct_answer: "B",
    explanation: "Multi-region failover adds significant complexity, cost, and maintenance burden. It's only justified for mission-critical systems where the availability benefits outweigh these costs.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the relationship between complexity and reliability?",
    option_a: "More complexity always means more reliability",
    option_b: "Balance needed - too little OR too much complexity reduces reliability",
    option_c: "Complexity doesn't affect reliability",
    option_d: "Simpler is always better",
    correct_answer: "B",
    explanation: "Balance is key: too little complexity (no error handling) causes failures; too much complexity (over-engineering) introduces bugs and maintenance burden. Right-size for your needs.",
    difficulty: "hard"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Should you implement custom retry logic if the SDK already handles retries?",
    option_a: "Yes, always customize everything",
    option_b: "Only if you have specific requirements SDK doesn't meet",
    option_c: "Never use SDK defaults",
    option_d: "Always implement both",
    correct_answer: "B",
    explanation: "Use SDK default retry logic unless you have specific requirements it doesn't meet. SDK defaults are well-tested and sufficient for most use cases. Custom logic adds complexity.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's a common mistake in production error handling?",
    option_a: "Using SDK defaults",
    option_b: "Over-engineering with unnecessary complexity",
    option_c: "Logging errors",
    option_d: "Monitoring metrics",
    correct_answer: "B",
    explanation: "Over-engineering (implementing every possible pattern, multiple fallback layers, etc.) adds complexity without proportional benefit. Start simple, add sophistication based on actual needs.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How should you approach production readiness?",
    option_a: "Deploy immediately with minimal preparation",
    option_b: "Incremental approach: monitoring, then error handling, then advanced patterns as needed",
    option_c: "Implement all features before any deployment",
    option_d: "Copy another system exactly",
    correct_answer: "B",
    explanation: "Take an incremental approach: start with basic monitoring and error handling (SDK defaults), deploy, learn from real usage, then add advanced patterns only as specific needs emerge.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the purpose of staging environments in API integration?",
    option_a: "Staging isn't necessary",
    option_b: "Test error handling, fallbacks, and load patterns before production",
    option_c: "Only for Enterprise accounts",
    option_d: "Only for initial development",
    correct_answer: "B",
    explanation: "Use staging environments to test error handling, fallback strategies, retry logic, and load patterns under realistic conditions before production deployment. Catch issues early.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the recommended pattern for evolving production systems?",
    option_a: "Big bang redesigns",
    option_b: "Start with SDK defaults, monitor, iterate based on data",
    option_c: "Never change production systems",
    option_d: "Change everything frequently",
    correct_answer: "B",
    explanation: "Start with proven SDK defaults, deploy with comprehensive monitoring, collect data on actual behavior, then iterate and add sophistication based on real needs and patterns observed.",
    difficulty: "medium"
  },

  // SDK usage patterns (5 questions)
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Which SDKs provide built-in exponential backoff?",
    option_a: "No SDKs provide this",
    option_b: "Anthropic Python and Node.js SDKs",
    option_c: "Only Python SDK",
    option_d: "Only custom-built SDKs",
    correct_answer: "B",
    explanation: "Both Anthropic Python and Node.js SDKs provide built-in exponential backoff with jitter for retryable errors, eliminating the need to implement this yourself.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "What's the advantage of using official SDKs over direct API calls?",
    option_a: "No real advantage",
    option_b: "Built-in best practices, retry logic, and easier maintenance",
    option_c: "Only cost savings",
    option_d: "Only faster responses",
    correct_answer: "B",
    explanation: "Official SDKs include built-in best practices (retry logic, error handling, exponential backoff), easier API usage, and are maintained by Anthropic with updates for API changes.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "Can you customize SDK retry behavior?",
    option_a: "No, SDK behavior is completely fixed",
    option_b: "Yes, most SDKs allow customizing retry parameters",
    option_c: "Only for Enterprise accounts",
    option_d: "Only by modifying SDK source code",
    correct_answer: "B",
    explanation: "Anthropic SDKs allow customizing retry parameters (max attempts, backoff strategy) while still leveraging SDK infrastructure. Start with defaults; customize only if needed.",
    difficulty: "medium"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "When should you make direct API calls instead of using an SDK?",
    option_a: "Always use direct API calls",
    option_b: "Only when SDK doesn't exist for your language or has specific limitations",
    option_c: "Never, always use SDKs",
    option_d: "Only for testing",
    correct_answer: "B",
    explanation: "Use official SDKs when available for their built-in best practices. Only make direct API calls when no SDK exists for your language or SDK has specific limitations for your use case.",
    difficulty: "easy"
  },
  {
    week: 11,
    domain: "Integration & Production Best Practices",
    topic: "Integration & Best Practices",
    question: "How do SDKs handle API version changes?",
    option_a: "They don't handle version changes",
    option_b: "SDKs are updated by Anthropic to maintain compatibility",
    option_c: "You must manually update for every API change",
    option_d: "Version changes break SDKs permanently",
    correct_answer: "B",
    explanation: "Official SDKs are maintained by Anthropic and updated to handle API version changes, providing a more stable integration layer than direct API calls which require manual updates.",
    difficulty: "medium"
  }
];
