export interface Question {
  week?: number;
  domain: string;
  topic: string;
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_answer: string;
  explanation: string;
  difficulty?: string;
}

export const topic8Questions: Question[] = [
  // Input/Output Validation Techniques (15 questions)
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the primary benefit of using Structured Outputs for validation in Claude applications?',
    option_a: 'Faster response times',
    option_b: 'Guaranteed schema compliance',
    option_c: 'Lower API costs',
    option_d: 'Better creative outputs',
    correct_answer: 'B',
    explanation: 'Structured Outputs guarantee that Claude\'s responses conform to a specified schema, ensuring schema compliance and making validation more reliable.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Which Claude model is recommended for pre-screening user input as a validation layer?',
    option_a: 'Claude Opus 4',
    option_b: 'Claude Sonnet 4',
    option_c: 'Claude Haiku 4.5',
    option_d: 'Claude 3 Opus',
    correct_answer: 'C',
    explanation: 'Claude Haiku 4.5 is cost-effective and fast, making it ideal for input validation tasks like pre-screening user input before it reaches more expensive models.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What technique can be used to enforce output format and bypass Claude\'s preamble?',
    option_a: 'System prompts',
    option_b: 'Prefilling the Assistant turn',
    option_c: 'Temperature settings',
    option_d: 'Top-k sampling',
    correct_answer: 'B',
    explanation: 'Prefilling the Assistant turn allows you to start Claude\'s response with specific text, enforcing format and bypassing the typical preamble.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'When implementing input validation, what should be filtered before reaching Claude?',
    option_a: 'Long text passages',
    option_b: 'Injection patterns',
    option_c: 'Technical terminology',
    option_d: 'User preferences',
    correct_answer: 'B',
    explanation: 'Injection patterns (such as prompt injection attempts) should be filtered out during input validation to prevent security vulnerabilities.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the primary purpose of output monitoring in a Claude application?',
    option_a: 'Track API usage costs',
    option_b: 'Analyze for injection signs and iteratively refine',
    option_c: 'Measure response latency',
    option_d: 'Count token usage',
    correct_answer: 'B',
    explanation: 'Output monitoring involves analyzing Claude\'s responses for signs of injection attacks or policy violations, allowing for iterative refinement of the system.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'In a multi-layered validation approach, which component is responsible for PII redaction?',
    option_a: 'The Claude model itself',
    option_b: 'Client-side JavaScript',
    option_c: 'Gateway controls and pre-processing layers',
    option_d: 'Post-processing formatters',
    correct_answer: 'C',
    explanation: 'PII redaction is typically handled at the gateway or pre-processing layer as part of a layered security approach, before sensitive data reaches the model.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the advantage of using schema validation with Structured Outputs versus post-hoc validation?',
    option_a: 'Cheaper API calls',
    option_b: 'Compliance is guaranteed during generation, not after',
    option_c: 'Faster token generation',
    option_d: 'Better multilingual support',
    correct_answer: 'B',
    explanation: 'Structured Outputs guarantee schema compliance during generation, eliminating the need for post-hoc validation and retry logic.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'When implementing validation, what should you do if Claude\'s output contains potential policy violations?',
    option_a: 'Immediately return the response to the user',
    option_b: 'Block the response and log the incident',
    option_c: 'Modify the response client-side',
    option_d: 'Ignore minor violations',
    correct_answer: 'B',
    explanation: 'Policy violations should trigger blocking of the response and logging for security audit purposes, preventing problematic content from reaching users.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Which validation technique combines format enforcement with schema compliance?',
    option_a: 'Regex pattern matching',
    option_b: 'Structured Outputs with prefilling',
    option_c: 'JSON parsing only',
    option_d: 'Temperature reduction',
    correct_answer: 'B',
    explanation: 'Combining Structured Outputs (for schema compliance) with prefilling (for format enforcement) provides comprehensive validation control.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the purpose of iterative refinement in output validation?',
    option_a: 'Reduce API costs',
    option_b: 'Improve output quality through repeated review and revision',
    option_c: 'Speed up response generation',
    option_d: 'Cache more responses',
    correct_answer: 'B',
    explanation: 'Iterative refinement involves generating, reviewing, and revising outputs repeatedly to improve quality and ensure compliance with requirements.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'In a validation pipeline, what is the role of automated validation checks?',
    option_a: 'Replace human review entirely',
    option_b: 'Provide clear completion criteria for iterative refinement',
    option_c: 'Generate new prompts',
    option_d: 'Manage API keys',
    correct_answer: 'B',
    explanation: 'Automated validation checks provide objective criteria to determine when iterative refinement is complete, enabling systematic quality improvement.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What type of validation is best handled by prefilling the Assistant turn?',
    option_a: 'Content policy compliance',
    option_b: 'Format and structure validation',
    option_c: 'Factual accuracy',
    option_d: 'Language detection',
    correct_answer: 'B',
    explanation: 'Prefilling is particularly effective for format and structure validation, as it directly controls how Claude\'s response begins and is structured.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'When should you use Claude Haiku 4.5 for validation versus Claude Sonnet 4?',
    option_a: 'Never use Haiku for validation',
    option_b: 'Use Haiku for simple input screening, Sonnet for complex validation',
    option_c: 'Always use Sonnet for any validation',
    option_d: 'Use Haiku only for output validation',
    correct_answer: 'B',
    explanation: 'Haiku 4.5 is cost-effective for simple input screening and pattern detection, while Sonnet 4 is better for complex validation requiring nuanced understanding.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is a key challenge when validating unstructured text outputs from Claude?',
    option_a: 'Claude never produces unstructured text',
    option_b: 'Lack of guaranteed schema makes parsing and validation harder',
    option_c: 'Unstructured text is always invalid',
    option_d: 'API costs are higher',
    correct_answer: 'B',
    explanation: 'Without structured output guarantees, validating unstructured text requires more complex parsing logic and may need retry mechanisms.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How does validation relate to the "prompt, observe, reprompt" pattern?',
    option_a: 'Validation replaces observation',
    option_b: 'Observation includes validation checks that inform reprompting',
    option_c: 'Validation only happens after reprompting',
    option_d: 'They are unrelated concepts',
    correct_answer: 'B',
    explanation: 'In the "prompt, observe, reprompt" pattern, observation includes validation checks whose results inform whether and how to reprompt.',
    difficulty: 'hard'
  },

  // Guardrails and Security (15 questions)
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the purpose of a layered security approach in Claude applications?',
    option_a: 'Reduce API latency',
    option_b: 'Provide multiple defense layers including gateway controls, validation, and audit logging',
    option_c: 'Increase token limits',
    option_d: 'Enable caching',
    correct_answer: 'B',
    explanation: 'Layered security uses multiple defensive mechanisms (gateway controls, PII redaction, validation, policy-as-code, audit logging) to protect against various threats.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What are real-time guardrails in the context of Claude applications?',
    option_a: 'API rate limits',
    option_b: 'Prompted or fine-tuned classifiers that detect policy violations',
    option_c: 'Network firewalls',
    option_d: 'Database backup systems',
    correct_answer: 'B',
    explanation: 'Real-time guardrails are classifiers (either prompted or fine-tuned) that detect policy violations in real-time as content flows through the system.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is a PreToolUse hook used for?',
    option_a: 'Speed up tool execution',
    option_b: 'Authorization gates before risky operations',
    option_c: 'Cache tool results',
    option_d: 'Format tool outputs',
    correct_answer: 'B',
    explanation: 'PreToolUse hooks act as authorization gates, allowing you to validate permissions and parameters before Claude executes potentially risky tool operations.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Which security layer is responsible for filtering injection patterns?',
    option_a: 'Audit logging',
    option_b: 'Gateway controls and input validation',
    option_c: 'Output formatting',
    option_d: 'Token counting',
    correct_answer: 'B',
    explanation: 'Gateway controls and input validation layers filter injection patterns before they reach the Claude API, preventing prompt injection attacks.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the role of audit logging in a guardrail system?',
    option_a: 'Speed up API calls',
    option_b: 'Track security events and policy violations for compliance and analysis',
    option_c: 'Generate user reports',
    option_d: 'Format responses',
    correct_answer: 'B',
    explanation: 'Audit logging records security events, policy violations, and access patterns for compliance, incident investigation, and system improvement.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How do prompted classifiers differ from fine-tuned classifiers for guardrails?',
    option_a: 'Prompted classifiers are always more accurate',
    option_b: 'Prompted classifiers use prompts to detect violations, fine-tuned are trained on examples',
    option_c: 'Fine-tuned classifiers are always cheaper',
    option_d: 'There is no difference',
    correct_answer: 'B',
    explanation: 'Prompted classifiers use carefully crafted prompts to detect policy violations, while fine-tuned classifiers are trained on labeled examples for specific detection tasks.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is policy-as-code in the context of Claude guardrails?',
    option_a: 'Writing policies in documentation',
    option_b: 'Encoding business rules and policies as executable code for automated enforcement',
    option_c: 'Using Claude to write code',
    option_d: 'Storing policies in databases',
    correct_answer: 'B',
    explanation: 'Policy-as-code means encoding business rules, compliance requirements, and security policies as executable code for consistent, automated enforcement.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'When implementing PII redaction, at which stage should it occur?',
    option_a: 'After Claude generates the response',
    option_b: 'Before data reaches Claude (pre-processing)',
    option_c: 'During token counting',
    option_d: 'Only in the client application',
    correct_answer: 'B',
    explanation: 'PII redaction should occur in pre-processing before data reaches Claude to prevent sensitive information from being processed by the model.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the benefit of using multiple guardrail layers versus a single validation check?',
    option_a: 'Faster processing',
    option_b: 'Defense in depth - if one layer fails, others provide protection',
    option_c: 'Lower costs',
    option_d: 'Simpler architecture',
    correct_answer: 'B',
    explanation: 'Multiple guardrail layers provide defense in depth, ensuring that if one security control fails or is bypassed, other layers still provide protection.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How should PreToolUse hooks handle authorization failures?',
    option_a: 'Allow the operation but log a warning',
    option_b: 'Block the tool execution and return an error',
    option_c: 'Modify the tool parameters automatically',
    option_d: 'Ignore the authorization check',
    correct_answer: 'B',
    explanation: 'PreToolUse hooks should block unauthorized tool execution and return clear error messages to prevent risky operations from proceeding.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What type of threats do gateway controls primarily protect against?',
    option_a: 'Hardware failures',
    option_b: 'Malicious inputs, injection attacks, and unauthorized access',
    option_c: 'Network latency',
    option_d: 'API version incompatibilities',
    correct_answer: 'B',
    explanation: 'Gateway controls act as the first line of defense, protecting against malicious inputs, injection attacks, and unauthorized access attempts.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Why is it important to analyze outputs for injection signs even after input validation?',
    option_a: 'Input validation is not necessary',
    option_b: 'Sophisticated attacks may bypass input filters or be embedded in context',
    option_c: 'Output analysis is cheaper than input validation',
    option_d: 'Claude always sanitizes outputs automatically',
    correct_answer: 'B',
    explanation: 'Even with input validation, sophisticated attacks may bypass filters or be embedded in context, making output monitoring essential for comprehensive security.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the relationship between guardrails and iterative refinement?',
    option_a: 'They are mutually exclusive',
    option_b: 'Guardrails can trigger iterative refinement when violations are detected',
    option_c: 'Iterative refinement replaces guardrails',
    option_d: 'They apply to different domains',
    correct_answer: 'B',
    explanation: 'Guardrails can detect policy violations or quality issues that trigger iterative refinement processes to improve outputs before delivery.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'In a layered security approach, what happens between gateway controls and the Claude API?',
    option_a: 'Nothing - direct connection',
    option_b: 'PII redaction, validation, and policy enforcement layers',
    option_c: 'Only token counting',
    option_d: 'Caching only',
    correct_answer: 'B',
    explanation: 'Between gateway controls and the Claude API, multiple layers handle PII redaction, validation, and policy enforcement to ensure secure and compliant processing.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What makes a guardrail system "real-time"?',
    option_a: 'It uses WebSockets',
    option_b: 'It detects and responds to violations as content flows through the system',
    option_c: 'It has zero latency',
    option_d: 'It only runs during business hours',
    correct_answer: 'B',
    explanation: 'Real-time guardrails analyze content as it flows through the system, detecting and responding to policy violations immediately rather than in batch or post-processing.',
    difficulty: 'medium'
  },

  // Structured Outputs for Validation (10 questions)
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the primary guarantee provided by Structured Outputs?',
    option_a: 'Faster generation',
    option_b: 'Schema compliance',
    option_c: 'Lower token usage',
    option_d: 'Better creativity',
    correct_answer: 'B',
    explanation: 'Structured Outputs guarantee that Claude\'s responses will conform to the specified schema, eliminating schema validation failures.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How do Structured Outputs reduce the need for retry logic?',
    option_a: 'By making Claude faster',
    option_b: 'By guaranteeing valid structure on first attempt',
    option_c: 'By caching responses',
    option_d: 'By lowering API costs',
    correct_answer: 'B',
    explanation: 'Since Structured Outputs guarantee schema compliance, there\'s no need for retry logic to handle malformed responses that fail validation.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Can Structured Outputs be combined with prefilling?',
    option_a: 'No, they are mutually exclusive',
    option_b: 'Yes, for comprehensive format and schema control',
    option_c: 'Only in batch requests',
    option_d: 'Only with Claude Opus',
    correct_answer: 'B',
    explanation: 'Structured Outputs and prefilling can be combined to provide both schema compliance and format control, offering comprehensive validation.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What type of validation is NOT needed when using Structured Outputs?',
    option_a: 'Content policy validation',
    option_b: 'Schema structure validation',
    option_c: 'Factual accuracy validation',
    option_d: 'Business logic validation',
    correct_answer: 'B',
    explanation: 'Structured Outputs guarantee schema structure compliance, eliminating the need for schema validation. Other types of validation (content, facts, business logic) are still necessary.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How do Structured Outputs affect the "generate and validate" workflow?',
    option_a: 'No impact',
    option_b: 'Eliminate schema validation step, simplify the workflow',
    option_c: 'Make it more complex',
    option_d: 'Only work with batch processing',
    correct_answer: 'B',
    explanation: 'Structured Outputs eliminate the need for schema validation and retry logic, significantly simplifying the generate-and-validate workflow.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What happens if Claude cannot generate content that fits the required schema with Structured Outputs?',
    option_a: 'Claude returns malformed JSON',
    option_b: 'The API returns an error',
    option_c: 'Claude modifies the schema',
    option_d: 'The response is cached',
    correct_answer: 'B',
    explanation: 'If Claude cannot generate content that fits the required schema, the API will return an error rather than producing non-compliant output.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'When should you use Structured Outputs versus post-hoc JSON parsing?',
    option_a: 'Never use Structured Outputs',
    option_b: 'Use Structured Outputs when schema compliance is critical',
    option_c: 'Always use post-hoc parsing',
    option_d: 'Only for simple schemas',
    correct_answer: 'B',
    explanation: 'Structured Outputs should be used when schema compliance is critical and you want to avoid retry logic, as they guarantee valid structure.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Do Structured Outputs guarantee factual accuracy of the content?',
    option_a: 'Yes, all content is verified',
    option_b: 'No, only schema structure is guaranteed',
    option_c: 'Only for numeric values',
    option_d: 'Only when combined with citations',
    correct_answer: 'B',
    explanation: 'Structured Outputs only guarantee that the response conforms to the schema structure; they do not verify factual accuracy of the content itself.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How do Structured Outputs improve application reliability?',
    option_a: 'By reducing API latency',
    option_b: 'By eliminating parsing failures and reducing retry needs',
    option_c: 'By caching all responses',
    option_d: 'By increasing rate limits',
    correct_answer: 'B',
    explanation: 'Structured Outputs improve reliability by guaranteeing schema compliance, which eliminates parsing failures and reduces the need for retry logic.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Can Structured Outputs enforce business logic rules?',
    option_a: 'Yes, all business logic is automatically enforced',
    option_b: 'No, only schema structure - business logic requires additional validation',
    option_c: 'Only simple arithmetic rules',
    option_d: 'Only in batch mode',
    correct_answer: 'B',
    explanation: 'Structured Outputs only enforce schema structure. Complex business logic rules (e.g., value constraints, cross-field validation) require additional validation layers.',
    difficulty: 'hard'
  },

  // Message Batches API Mechanics (20 questions)
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the primary benefit of the Message Batches API?',
    option_a: 'Faster synchronous responses',
    option_b: '50% cost reduction for most batches',
    option_c: 'Unlimited rate limits',
    option_d: 'Real-time processing',
    correct_answer: 'B',
    explanation: 'The Message Batches API provides a 50% cost reduction for most batches that finish within 1 hour, making it cost-effective for large-volume processing.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the maximum number of requests allowed in a single batch?',
    option_a: '10,000 requests',
    option_b: '50,000 requests',
    option_c: '100,000 requests',
    option_d: 'Unlimited',
    correct_answer: 'C',
    explanation: 'The Message Batches API allows up to 100,000 requests per batch, with an additional limit of 256 MB total size.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How long are batch results available after creation?',
    option_a: '7 days',
    option_b: '14 days',
    option_c: '29 days',
    option_d: 'Forever',
    correct_answer: 'C',
    explanation: 'Batch results are available for 29 days after creation, after which they are deleted from Anthropic\'s systems.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the guaranteed completion time for Message Batches?',
    option_a: '1 hour',
    option_b: '12 hours',
    option_c: '24 hours',
    option_d: '48 hours',
    correct_answer: 'C',
    explanation: 'Message Batches have a 24-hour completion guarantee, though most batches finish in less than 1 hour.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How do batch requests affect standard API rate limits?',
    option_a: 'They reduce standard limits',
    option_b: 'They share the same limits',
    option_c: 'They do not impact standard API limits',
    option_d: 'They eliminate standard limits',
    correct_answer: 'C',
    explanation: 'Batch requests have their own higher rate limits and do not impact standard API rate limits, allowing parallel usage.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the maximum total size for a batch?',
    option_a: '128 MB',
    option_b: '256 MB',
    option_c: '512 MB',
    option_d: '1 GB',
    correct_answer: 'B',
    explanation: 'In addition to the 100,000 request limit, batches are also limited to a total size of 256 MB.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How should you monitor the progress of a batch?',
    option_a: 'Real-time streaming',
    option_b: 'Poll for status updates',
    option_c: 'Email notifications only',
    option_d: 'Automatic callbacks',
    correct_answer: 'B',
    explanation: 'Batch progress is monitored by polling the API for status updates, as batches are asynchronous and don\'t provide real-time streaming.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Does the Message Batches API support prompt caching?',
    option_a: 'No, caching is disabled for batches',
    option_b: 'Yes, with best-effort support due to concurrent processing',
    option_c: 'Yes, with guaranteed caching',
    option_d: 'Only for batches under 1000 requests',
    correct_answer: 'B',
    explanation: 'The Message Batches API supports prompt caching on a best-effort basis, though concurrent processing may reduce cache effectiveness.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What processing model does the Message Batches API use?',
    option_a: 'Synchronous sequential processing',
    option_b: 'Asynchronous concurrent processing',
    option_c: 'Real-time streaming',
    option_d: 'Manual processing',
    correct_answer: 'B',
    explanation: 'The Message Batches API uses asynchronous concurrent processing to handle large volumes of requests efficiently.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'When do you get the 50% cost discount on batches?',
    option_a: 'Always, for all batches',
    option_b: 'For batches that finish within 1 hour',
    option_c: 'Only for batches over 10,000 requests',
    option_d: 'Never, the discount was removed',
    correct_answer: 'B',
    explanation: 'The 50% cost discount applies to most batches that finish within 1 hour, incentivizing efficient batch usage.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What happens to batch results after 29 days?',
    option_a: 'They are archived',
    option_b: 'They are deleted',
    option_c: 'They are compressed',
    option_d: 'They remain available indefinitely',
    correct_answer: 'B',
    explanation: 'Batch results are automatically deleted after 29 days and cannot be retrieved after that point.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Can you cancel a batch that is currently processing?',
    option_a: 'No, batches cannot be cancelled',
    option_b: 'Yes, using the batch cancellation API',
    option_c: 'Only within the first 5 minutes',
    option_d: 'Only if less than 50% complete',
    correct_answer: 'B',
    explanation: 'The Batches API provides functionality to cancel batches that are in progress, though some requests may have already been processed.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How are individual request failures handled in a batch?',
    option_a: 'The entire batch fails',
    option_b: 'Failed requests are returned with error details, successful ones complete',
    option_c: 'Failed requests are automatically retried',
    option_d: 'Failures are ignored',
    correct_answer: 'B',
    explanation: 'Individual request failures don\'t cause the entire batch to fail. Each request\'s result (success or error) is included in the batch results.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the advantage of higher rate limits for batch processing?',
    option_a: 'Faster individual responses',
    option_b: 'Ability to submit more batch requests concurrently',
    option_c: 'Lower costs',
    option_d: 'Better model quality',
    correct_answer: 'B',
    explanation: 'Higher rate limits for batch processing allow you to submit more batch requests concurrently without hitting rate limits.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Why might prompt caching be less effective in batch processing?',
    option_a: 'Caching is disabled for batches',
    option_b: 'Concurrent processing may spread requests across different cache contexts',
    option_c: 'Batches are too large for caching',
    option_d: 'Cache time-to-live is shorter',
    correct_answer: 'B',
    explanation: 'Concurrent processing of batch requests may distribute them across different servers or time windows, reducing cache hit rates compared to sequential processing.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What information is included when you poll for batch status?',
    option_a: 'Only completion percentage',
    option_b: 'Processing status, counts of completed/failed/in-progress requests',
    option_c: 'Just a boolean complete flag',
    option_d: 'Full results of all requests',
    correct_answer: 'B',
    explanation: 'Polling for batch status returns detailed information including processing status and counts of completed, failed, and in-progress requests.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How should you structure requests in a batch to maximize cache effectiveness?',
    option_a: 'Randomize request order',
    option_b: 'Group requests with similar prefixes together',
    option_c: 'Use different system prompts for each',
    option_d: 'Caching cannot be optimized in batches',
    correct_answer: 'B',
    explanation: 'Grouping requests with similar prefixes (system prompts, shared context) together can improve cache hit rates even in concurrent processing.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What happens if a batch exceeds the 100,000 request limit?',
    option_a: 'Extra requests are queued for next batch',
    option_b: 'The batch submission is rejected',
    option_c: 'Only first 100,000 are processed',
    option_d: 'Automatic splitting into multiple batches',
    correct_answer: 'B',
    explanation: 'Attempting to submit a batch exceeding the 100,000 request or 256 MB limit will result in rejection. You must split it into multiple batches.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Can you retrieve partial results before a batch completes?',
    option_a: 'No, must wait for full completion',
    option_b: 'Yes, completed requests are available as the batch processes',
    option_c: 'Only for failed requests',
    option_d: 'Only in the first hour',
    correct_answer: 'B',
    explanation: 'You can retrieve results for completed requests even while the batch is still processing, allowing for progressive result consumption.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the relationship between batch completion time and cost discount?',
    option_a: 'No relationship',
    option_b: 'Faster completion (<1 hour) typically qualifies for 50% discount',
    option_c: 'Slower batches get larger discounts',
    option_d: 'All batches have the same cost',
    correct_answer: 'B',
    explanation: 'Batches that complete within 1 hour typically qualify for the 50% cost discount, incentivizing appropriately-sized batch submissions.',
    difficulty: 'medium'
  },

  // Batch API Use Cases and Limitations (10 questions)
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Which of the following is a recommended use case for Message Batches API?',
    option_a: 'Real-time chatbot responses',
    option_b: 'Running evaluations on large datasets',
    option_c: 'Live customer support',
    option_d: 'Interactive code completion',
    correct_answer: 'B',
    explanation: 'Running evaluations on large datasets is ideal for batch processing as it doesn\'t require real-time responses and benefits from cost reduction.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Why is content moderation a good use case for batch processing?',
    option_a: 'It requires real-time processing',
    option_b: 'It involves processing large volumes of content asynchronously',
    option_c: 'It needs immediate user feedback',
    option_d: 'It requires streaming responses',
    correct_answer: 'B',
    explanation: 'Content moderation often involves processing large volumes of content where some delay is acceptable, making it ideal for cost-effective batch processing.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What type of task is NOT suitable for batch processing?',
    option_a: 'Bulk document analysis',
    option_b: 'Interactive conversation',
    option_c: 'Dataset evaluation',
    option_d: 'Content generation at scale',
    correct_answer: 'B',
    explanation: 'Interactive conversations require real-time responses, making them unsuitable for asynchronous batch processing which may take up to 24 hours.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How can batch processing be used for data analysis?',
    option_a: 'Real-time dashboard updates',
    option_b: 'Processing large datasets for insights, classifications, or summaries',
    option_c: 'Live query responses',
    option_d: 'Interactive data exploration',
    correct_answer: 'B',
    explanation: 'Batch processing is excellent for analyzing large datasets to extract insights, perform classifications, or generate summaries where immediate results aren\'t required.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is a limitation of using batches for prompt caching strategies?',
    option_a: 'Caching is completely disabled',
    option_b: 'Concurrent processing reduces cache effectiveness',
    option_c: 'Caching only works for small batches',
    option_d: 'Cache results are not returned',
    correct_answer: 'B',
    explanation: 'The concurrent nature of batch processing means requests may be processed at different times or on different servers, reducing cache hit rates.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Why is bulk content generation a good fit for batch processing?',
    option_a: 'It requires user interaction',
    option_b: 'Large volume generation benefits from cost reduction and doesn\'t need real-time delivery',
    option_c: 'It needs streaming responses',
    option_d: 'It requires immediate feedback',
    correct_answer: 'B',
    explanation: 'Bulk content generation (articles, descriptions, summaries) benefits from batch processing\'s cost reduction and can tolerate asynchronous delivery.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the main trade-off when choosing batch processing over standard API?',
    option_a: 'Higher costs for lower latency',
    option_b: 'Lower costs for higher latency',
    option_c: 'Same costs, different rate limits',
    option_d: 'No trade-offs exist',
    correct_answer: 'B',
    explanation: 'Batch processing offers 50% cost reduction in exchange for asynchronous processing with higher latency (up to 24 hours vs. immediate responses).',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How can batches be used for running evaluations?',
    option_a: 'Only for small test sets',
    option_b: 'Process large evaluation datasets cost-effectively with detailed results',
    option_c: 'Real-time A/B testing only',
    option_d: 'Interactive prompt testing',
    correct_answer: 'B',
    explanation: 'Batches are ideal for running evaluations on large datasets, providing cost-effective processing and detailed results for each test case.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What makes batch processing particularly useful for offline workflows?',
    option_a: 'Faster processing than standard API',
    option_b: 'Can process large volumes overnight or during off-peak times at lower cost',
    option_c: 'Provides real-time monitoring',
    option_d: 'Requires no internet connection',
    correct_answer: 'B',
    explanation: 'Batch processing is ideal for offline workflows where processing can happen overnight or during off-peak times, leveraging cost savings for non-urgent tasks.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'When would you choose standard API over batch processing despite higher costs?',
    option_a: 'Processing 100,000 documents',
    option_b: 'Real-time user interactions requiring immediate responses',
    option_c: 'Monthly report generation',
    option_d: 'Overnight data analysis',
    correct_answer: 'B',
    explanation: 'Standard API is necessary for real-time user interactions where immediate responses are required, despite the higher costs compared to batch processing.',
    difficulty: 'medium'
  },

  // Multi-pass Prompting Patterns (15 questions)
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the basic pattern of multi-pass prompting?',
    option_a: 'Single prompt with multiple outputs',
    option_b: 'Generate, then review/refine in separate API calls',
    option_c: 'Parallel processing of prompts',
    option_d: 'Caching previous responses',
    correct_answer: 'B',
    explanation: 'Multi-pass prompting involves generating an initial output, then using separate API calls to review and refine it, allowing for iteration and improvement.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the "prompt, observe, reprompt" core loop?',
    option_a: 'A caching strategy',
    option_b: 'An iterative pattern where you prompt, analyze the response, then prompt again',
    option_c: 'A batch processing technique',
    option_d: 'A rate limiting approach',
    correct_answer: 'B',
    explanation: 'The "prompt, observe, reprompt" loop is the core of multi-pass prompting: send a prompt, observe/analyze the output, then send another prompt based on that analysis.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Why use separate API calls for each step in multi-pass prompting?',
    option_a: 'To increase costs',
    option_b: 'Enables logging, evaluation, and branching between steps',
    option_c: 'Required by the API',
    option_d: 'Faster processing',
    correct_answer: 'B',
    explanation: 'Separate API calls allow you to log each step, evaluate outputs, make branching decisions, and insert business logic between generation and refinement.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How does Claude respond to follow-up instructions in multi-pass workflows?',
    option_a: 'Ignores them',
    option_b: 'Adapts strongly to follow-up instructions',
    option_c: 'Only responds to the first instruction',
    option_d: 'Requires system prompt changes',
    correct_answer: 'B',
    explanation: 'Claude adapts strongly to follow-up instructions, making multi-pass workflows effective for iterative refinement and improvement.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is a key advantage of multi-pass prompting over single-pass generation?',
    option_a: 'Always faster',
    option_b: 'Enables quality improvement through iteration and specialized focus per step',
    option_c: 'Always cheaper',
    option_d: 'Requires less context',
    correct_answer: 'B',
    explanation: 'Multi-pass prompting allows each step to focus on a specific aspect (generation, review, refinement), leading to higher quality outputs through iteration.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the "self-correction pattern" in multi-pass prompting?',
    option_a: 'Claude automatically fixes all errors',
    option_b: 'Generate draft, review against criteria, then refine in separate calls',
    option_c: 'Using error codes to retry',
    option_d: 'Parallel validation checks',
    correct_answer: 'B',
    explanation: 'The self-correction pattern involves generating a draft, explicitly reviewing it against criteria in a separate call, then refining based on that review.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'When should you stop iterating in a multi-pass workflow?',
    option_a: 'After exactly 3 passes',
    option_b: 'When clear completion criteria are met',
    option_c: 'Never stop iterating',
    option_d: 'After 1 hour of processing',
    correct_answer: 'B',
    explanation: 'Iteration should stop when clear, predefined completion criteria are met, such as passing validation checks or meeting quality thresholds.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What can be inserted between passes in a multi-pass workflow?',
    option_a: 'Nothing - passes must be sequential',
    option_b: 'Business logic, validation, logging, and conditional branching',
    option_c: 'Only logging',
    option_d: 'Only caching',
    correct_answer: 'B',
    explanation: 'Between passes, you can insert business logic, run validation checks, log results, make conditional decisions, and branch to different paths.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How does multi-pass prompting relate to the iterative refinement loop?',
    option_a: 'They are unrelated concepts',
    option_b: 'Multi-pass provides the technical framework for iterative refinement',
    option_c: 'They are mutually exclusive',
    option_d: 'Iterative refinement is faster',
    correct_answer: 'B',
    explanation: 'Multi-pass prompting provides the technical framework (separate API calls) that enables iterative refinement workflows (generate, review, revise, repeat).',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is a potential downside of multi-pass prompting?',
    option_a: 'Lower quality outputs',
    option_b: 'Higher token costs and latency from multiple API calls',
    option_c: 'Cannot use structured outputs',
    option_d: 'Incompatible with caching',
    correct_answer: 'B',
    explanation: 'Multi-pass prompting requires multiple API calls, increasing both token costs and total latency compared to single-pass generation.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How can prompt caching optimize multi-pass workflows?',
    option_a: 'Caching is not useful for multi-pass',
    option_b: 'Cache shared context (instructions, examples) across passes to reduce costs',
    option_c: 'Only the final output can be cached',
    option_d: 'Caching slows down multi-pass',
    correct_answer: 'B',
    explanation: 'Caching shared context like instructions and examples across multiple passes significantly reduces the token costs of multi-pass workflows.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'In a multi-pass workflow, what should the "observe" step include?',
    option_a: 'Just reading the output',
    option_b: 'Analysis, validation, quality assessment, and decision-making',
    option_c: 'Only error checking',
    option_d: 'Automatic reformatting',
    correct_answer: 'B',
    explanation: 'The observe step should include thorough analysis, validation checks, quality assessment, and decision-making about whether to refine or what to refine.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What makes a task well-suited for multi-pass prompting?',
    option_a: 'Simple, straightforward tasks',
    option_b: 'Complex tasks where quality benefits from review and refinement',
    option_c: 'Tasks requiring real-time responses',
    option_d: 'Tasks with no quality criteria',
    correct_answer: 'B',
    explanation: 'Multi-pass prompting is ideal for complex tasks where quality significantly benefits from iterative review and refinement, justifying the extra API calls.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Can multi-pass prompting be combined with structured outputs?',
    option_a: 'No, they are incompatible',
    option_b: 'Yes, each pass can use structured outputs for reliable parsing',
    option_c: 'Only on the final pass',
    option_d: 'Only on the first pass',
    correct_answer: 'B',
    explanation: 'Structured outputs can be used in each pass of multi-pass prompting, ensuring reliable parsing of both drafts and refinements.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How does multi-pass prompting enable specialized processing?',
    option_a: 'By using different models',
    option_b: 'Each pass can focus on a specific aspect (content, style, accuracy, etc.)',
    option_c: 'By reducing context',
    option_d: 'By eliminating validation',
    correct_answer: 'B',
    explanation: 'Multi-pass prompting allows each pass to specialize: one for content generation, another for style refinement, another for fact-checking, etc.',
    difficulty: 'hard'
  },

  // Iterative Refinement Techniques (10 questions)
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What are the basic steps in an iterative refinement loop?',
    option_a: 'Generate only',
    option_b: 'Generate, review, annotate, refine',
    option_c: 'Review and refine only',
    option_d: 'Generate and cache',
    correct_answer: 'B',
    explanation: 'The iterative refinement loop consists of: generate initial output, review against criteria, annotate issues, then refine to address those issues.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the "Ralph Wiggum technique"?',
    option_a: 'A caching strategy',
    option_b: 'A while loop feeding prompt until completion criteria met',
    option_c: 'A batch processing method',
    option_d: 'A validation algorithm',
    correct_answer: 'B',
    explanation: 'The Ralph Wiggum technique uses a while loop that repeatedly prompts Claude until specific completion criteria are satisfied.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is essential for effective iterative refinement?',
    option_a: 'Using the most expensive model',
    option_b: 'Clear completion criteria and automated validation',
    option_c: 'Unlimited iterations',
    option_d: 'Human review of each iteration',
    correct_answer: 'B',
    explanation: 'Effective iterative refinement requires clear completion criteria and automated validation to determine when quality standards are met.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'When does iterative refinement work best?',
    option_a: 'For simple tasks',
    option_b: 'With clear criteria, automated validation, and structured workflows',
    option_c: 'For real-time applications only',
    option_d: 'Without any validation',
    correct_answer: 'B',
    explanation: 'Iterative refinement is most effective when combined with clear completion criteria, automated validation, and well-defined structured workflows.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What role does annotation play in iterative refinement?',
    option_a: 'No role - not needed',
    option_b: 'Identifies specific issues to address in the next refinement pass',
    option_c: 'Only for documentation',
    option_d: 'Replaces validation',
    correct_answer: 'B',
    explanation: 'Annotation identifies specific issues, gaps, or areas for improvement, providing clear guidance for the next refinement iteration.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How should you prevent infinite loops in iterative refinement?',
    option_a: 'Never limit iterations',
    option_b: 'Set maximum iteration count and clear exit criteria',
    option_c: 'Only allow single iteration',
    option_d: 'Use random stopping',
    correct_answer: 'B',
    explanation: 'Prevent infinite loops by setting a maximum iteration count and defining clear exit criteria that signal when refinement is complete.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the difference between iterative refinement and simple retry logic?',
    option_a: 'No difference',
    option_b: 'Refinement uses feedback to improve, retry just repeats the same prompt',
    option_c: 'Retry is more sophisticated',
    option_d: 'Refinement is always faster',
    correct_answer: 'B',
    explanation: 'Iterative refinement incorporates feedback from previous attempts to guide improvement, while retry logic simply repeats the same prompt hoping for better results.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Can you use different prompting strategies in different refinement iterations?',
    option_a: 'No, must use identical prompts',
    option_b: 'Yes, each iteration can use different strategies based on previous results',
    option_c: 'Only the first iteration can differ',
    option_d: 'Only with batch processing',
    correct_answer: 'B',
    explanation: 'Different iterations can use different prompting strategies, focusing on specific aspects or issues identified in previous iterations.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How does structured output validation fit into iterative refinement?',
    option_a: 'Not compatible',
    option_b: 'Provides reliable format checking to determine if refinement is complete',
    option_c: 'Only needed in the first iteration',
    option_d: 'Replaces all other validation',
    correct_answer: 'B',
    explanation: 'Structured output validation ensures each iteration produces parseable output and can serve as one criterion for determining refinement completion.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is a sophisticated approach to the review step in iterative refinement?',
    option_a: 'Skip the review step',
    option_b: 'Use Claude to review its own output against detailed criteria',
    option_c: 'Only use regex validation',
    option_d: 'Review is always manual',
    correct_answer: 'B',
    explanation: 'A sophisticated approach is to use Claude itself to review its own output against detailed criteria, leveraging its reasoning capabilities for quality assessment.',
    difficulty: 'hard'
  },

  // Self-correction Workflows (5 questions)
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the core principle of self-correction workflows?',
    option_a: 'Claude automatically corrects all outputs',
    option_b: 'Use Claude to generate, review, and refine its own outputs',
    option_c: 'External systems correct Claude\'s outputs',
    option_d: 'Outputs never need correction',
    correct_answer: 'B',
    explanation: 'Self-correction workflows leverage Claude to generate initial outputs, then review and refine its own work based on explicit criteria.',
    difficulty: 'easy'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'Why use separate API calls for generation and self-review?',
    option_a: 'Required by the API',
    option_b: 'Allows focused attention on each task and enables branching logic',
    option_c: 'To increase costs',
    option_d: 'No specific reason',
    correct_answer: 'B',
    explanation: 'Separate calls allow Claude to focus fully on generation in one pass and critical review in another, and enable conditional logic between steps.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What should be included in a self-review prompt?',
    option_a: 'Just "check your work"',
    option_b: 'Explicit criteria, examples of issues, and structured output format',
    option_c: 'No details needed',
    option_d: 'Only positive feedback',
    correct_answer: 'B',
    explanation: 'Effective self-review prompts include explicit evaluation criteria, examples of potential issues, and structured output formats for consistent analysis.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is a limitation of self-correction workflows?',
    option_a: 'They never work',
    option_b: 'Claude may not catch all errors, especially subtle ones or in domains requiring external knowledge',
    option_c: 'They are always too expensive',
    option_d: 'They require human review of every step',
    correct_answer: 'B',
    explanation: 'Self-correction has limitations: Claude may miss subtle errors, lack domain-specific knowledge, or not recognize issues without external context.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How can you enhance self-correction workflows?',
    option_a: 'Remove all validation criteria',
    option_b: 'Combine with external validation, fact-checking, and domain-specific tools',
    option_c: 'Use only self-correction',
    option_d: 'Eliminate the review step',
    correct_answer: 'B',
    explanation: 'Self-correction is most effective when combined with external validation sources, fact-checking tools, and domain-specific validators.',
    difficulty: 'hard'
  },

  // Advanced Integration Topics (20 questions mixing multiple concepts)
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How can you combine batch processing with iterative refinement?',
    option_a: 'Not possible to combine them',
    option_b: 'Run initial generation in batch, then refine individual results that need improvement',
    option_c: 'Only use batch OR refinement, never both',
    option_d: 'They work for different use cases',
    correct_answer: 'B',
    explanation: 'You can use batch processing for initial generation at scale, then apply iterative refinement to specific results that fail quality checks.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the optimal validation strategy for a batch job generating 50,000 product descriptions?',
    option_a: 'No validation needed',
    option_b: 'Use structured outputs in batch, then post-process to validate business rules',
    option_c: 'Manual review of all outputs',
    option_d: 'Only validate the first 100',
    correct_answer: 'B',
    explanation: 'Use structured outputs in the batch to guarantee schema compliance, then run automated post-processing to validate business rules and quality criteria.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'When should you use multi-pass prompting instead of a single batch job?',
    option_a: 'Always use multi-pass',
    option_b: 'When quality benefits from review justify higher costs, or when outputs depend on each other',
    option_c: 'Never use multi-pass',
    option_d: 'Only for small datasets',
    correct_answer: 'B',
    explanation: 'Choose multi-pass when quality improvements from review justify additional costs, or when outputs have dependencies requiring sequential processing.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How do PreToolUse hooks relate to multi-pass workflows?',
    option_a: 'Unrelated concepts',
    option_b: 'Hooks can trigger additional refinement passes when risky operations are detected',
    option_c: 'Hooks disable multi-pass',
    option_d: 'Hooks only work in single-pass',
    correct_answer: 'B',
    explanation: 'PreToolUse hooks can detect risky operations and trigger additional review or refinement passes before allowing the operation to proceed.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What validation approach works best for high-stakes outputs requiring accuracy?',
    option_a: 'Single-pass generation only',
    option_b: 'Multi-pass with structured outputs, external validation, and guardrails',
    option_c: 'No validation needed',
    option_d: 'Batch processing without checks',
    correct_answer: 'B',
    explanation: 'High-stakes outputs require multiple validation layers: multi-pass refinement, structured outputs for format, external validation for facts, and guardrails for policies.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How can you optimize costs when using iterative refinement at scale?',
    option_a: 'Skip validation',
    option_b: 'Use Haiku for refinement steps, cache shared context, batch when possible',
    option_c: 'Always use the most expensive model',
    option_d: 'Eliminate refinement',
    correct_answer: 'B',
    explanation: 'Optimize costs by using Haiku for simpler refinement steps, leveraging prompt caching for shared context, and batching independent refinement tasks.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the role of audit logging in a multi-pass validation workflow?',
    option_a: 'No role in multi-pass',
    option_b: 'Track each pass, validation results, and refinement decisions for debugging and compliance',
    option_c: 'Only log the final output',
    option_d: 'Logging slows down workflows',
    correct_answer: 'B',
    explanation: 'Audit logging should capture each pass, validation results, and refinement decisions, enabling debugging, compliance audits, and workflow optimization.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How should completion criteria differ between batch and iterative workflows?',
    option_a: 'No difference needed',
    option_b: 'Batch uses pass/fail per request; iterative uses improvement threshold across passes',
    option_c: 'Only batch needs criteria',
    option_d: 'Only iterative needs criteria',
    correct_answer: 'B',
    explanation: 'Batch workflows evaluate each request independently with pass/fail criteria, while iterative workflows assess improvement across multiple passes.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is a hybrid approach combining batch and real-time validation?',
    option_a: 'Not possible to combine',
    option_b: 'Batch process bulk content, real-time validate user-facing subset',
    option_c: 'Only use one approach',
    option_d: 'Always use real-time only',
    correct_answer: 'B',
    explanation: 'A hybrid approach uses batch processing for bulk content generation, then applies real-time validation with guardrails for user-facing outputs.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How do you handle refinement for failed requests in a batch job?',
    option_a: 'Ignore failures',
    option_b: 'Extract failures, apply targeted refinement, resubmit in new batch or real-time',
    option_c: 'Resubmit entire batch',
    option_d: 'Manual rewriting only',
    correct_answer: 'B',
    explanation: 'Extract failed requests from batch results, apply targeted refinement based on error analysis, then resubmit via batch or real-time API as appropriate.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What validation sequence optimizes both quality and cost?',
    option_a: 'Skip all validation',
    option_b: 'Structured outputs → Haiku validation → conditional Sonnet refinement → guardrails',
    option_c: 'Use most expensive model for everything',
    option_d: 'Random validation order',
    correct_answer: 'B',
    explanation: 'Optimal sequence: structured outputs for format, Haiku for quick validation, conditional Sonnet refinement for issues, and guardrails for final policy check.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How can prompt caching improve multi-pass validation workflows?',
    option_a: 'Caching doesn\'t help validation',
    option_b: 'Cache validation criteria, examples, and instructions across all refinement passes',
    option_c: 'Only cache the final output',
    option_d: 'Caching breaks validation',
    correct_answer: 'B',
    explanation: 'Cache validation criteria, rubrics, examples, and instructions so they\'re reused across all refinement passes, dramatically reducing token costs.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'When should validation trigger a switch from batch to real-time processing?',
    option_a: 'Never switch approaches',
    option_b: 'When batch results show high failure rates needing interactive refinement',
    option_c: 'Always use real-time',
    option_d: 'Always use batch',
    correct_answer: 'B',
    explanation: 'Switch from batch to real-time when initial batch results show high failure rates or complexity requiring interactive, context-aware refinement.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the best practice for handling PII in multi-pass workflows?',
    option_a: 'Check for PII only at the end',
    option_b: 'Redact PII before first pass, validate redaction after each pass',
    option_c: 'PII handling not needed',
    option_d: 'Only check PII in batch mode',
    correct_answer: 'B',
    explanation: 'Best practice is to redact PII before the first pass to Claude, then validate that redaction remains effective after each subsequent pass.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How do you validate that iterative refinement is actually improving outputs?',
    option_a: 'Assume it always improves',
    option_b: 'Track quantitative metrics (validation scores) across iterations',
    option_c: 'Visual inspection only',
    option_d: 'Count number of iterations',
    correct_answer: 'B',
    explanation: 'Track quantitative metrics like validation scores, error rates, or quality metrics across iterations to verify refinement is actually improving outputs.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What is the relationship between structured outputs and the Ralph Wiggum technique?',
    option_a: 'Incompatible approaches',
    option_b: 'Structured outputs provide reliable format for while-loop termination conditions',
    option_c: 'No relationship',
    option_d: 'Ralph Wiggum doesn\'t use structured outputs',
    correct_answer: 'B',
    explanation: 'Structured outputs ensure reliable, parseable format in each iteration, making it easier to implement clear termination conditions for the while loop.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How can guardrails inform iterative refinement priorities?',
    option_a: 'Guardrails and refinement are separate',
    option_b: 'Guardrail violations indicate which aspects need priority refinement',
    option_c: 'Only use guardrails OR refinement',
    option_d: 'Guardrails replace refinement',
    correct_answer: 'B',
    explanation: 'Guardrail violations provide specific feedback about policy or quality issues, informing which aspects should be prioritized in refinement iterations.',
    difficulty: 'medium'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'What architecture supports both batch processing and real-time multi-pass refinement?',
    option_a: 'Single-purpose architecture only',
    option_b: 'Modular architecture with shared validation, routing logic, and async queues',
    option_c: 'No architecture can support both',
    option_d: 'Separate systems required',
    correct_answer: 'B',
    explanation: 'A modular architecture with shared validation components, intelligent routing logic, and async queues can flexibly support both batch and real-time multi-pass workflows.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'When processing 100,000 requests with potential refinement needs, what\'s the optimal strategy?',
    option_a: 'Real-time for all requests',
    option_b: 'Batch initial pass, identify failures, apply refinement only to failures',
    option_c: 'Multi-pass refinement for each request',
    option_d: 'No strategy needed',
    correct_answer: 'B',
    explanation: 'Optimal strategy: batch process all requests for cost efficiency, identify failures or quality issues, then apply targeted refinement only where needed.',
    difficulty: 'hard'
  },
  {
    week: 8,
    domain: 'Context Management & Reliability',
    topic: 'Validation, Batch & Multi-Pass',
    question: 'How should validation criteria evolve across refinement iterations?',
    option_a: 'Keep identical criteria',
    option_b: 'Start broad, then focus on specific issues identified in previous iterations',
    option_c: 'Random criteria each time',
    option_d: 'Remove criteria over time',
    correct_answer: 'B',
    explanation: 'Effective refinement starts with broad quality criteria, then narrows focus to specific issues or gaps identified in previous iterations.',
    difficulty: 'medium'
  }
];
